import { randomUUID } from "node:crypto";
import { validateStoredFireAlarmDetail } from "../inspections/fireAlarmAccepted.js";
import { resolveFireAlarmControls } from "../inspections/templates/fireAlarmDefinitionControls.js";
import { fireAlarmDetectorV3 } from "../inspections/templates/masterServiceReportV3.js";

const id=()=>randomUUID();const templateId=id(),revisionId=id(),jobId=id(),customerId=id(),enabledSystemId=id(),zoneId=id(),primaryId=id(),secondaryId=id();
const definition=fireAlarmDetectorV3;
const system={enabledSystemId,systemKey:"fire_alarm_detector",displayName:"Fire Alarm / Detector System",sortOrder:5,definitionStatus:"confirmed",zones:[{id:zoneId,enabledSystemId,key:"zone-1",displayName:"Zone 1",sortOrder:1}],locations:[{id:primaryId,enabledSystemId,zoneId,key:"primary",displayName:"Lobby",presetRowCount:1,rowPreset:{fireAlarmTable:"primary",assetReference:"FA-01"},sortOrder:1},{id:secondaryId,enabledSystemId,zoneId:null,key:"secondary",displayName:"Plant Room",presetRowCount:1,rowPreset:{fireAlarmTable:"secondary",assetReference:"AB-01"},sortOrder:2}],definition,resolvedControls:resolveFireAlarmControls(definition,"MFE-FSSR",3),repetitionMode:"single_with_two_repeatable_tables"};
const good=()=>({result:"good",remarks:""});
const responses={schemaVersion:1,controlPanelLocation:"Ground Floor Panel",primaryDeviceRows:[{rowUuid:id(),source:"configured",configuredLocationId:primaryId,configuredRowOrdinal:1,zoneSnapshot:{id:zoneId,displayName:"Zone 1"},locationSnapshot:{id:primaryId,displayName:"Lobby"},displaySequence:1,assetReference:"FA-01",alarmZone:"Zone 1",location:"Lobby",manualCallPoint:"normal",flowSwitch:"test",heatDetector:"isolation",smokeDetector:"normal",remarks:""}],chargerAndBatteries:{main_supply:good(),battery:good(),charger:good()},mainFunctionKeys:{main_alarm_reset:good(),lamp_test:good(),evacuate:good(),ac_supply:good(),dc_supply:good(),spka_system:good(),alarm_lift_trip:good(),signal_gas_discharge:good()},secondaryAlarmDeviceRows:[{rowUuid:id(),source:"configured",configuredLocationId:secondaryId,configuredRowOrdinal:1,zoneSnapshot:null,locationSnapshot:{id:secondaryId,displayName:"Plant Room"},displaySequence:1,assetReference:"AB-01",location:"Plant Room",alarmBell:"good",manualCallPoint:"poor",remarks:""}],comments:"Validated"};
const row={jobId,jobReference:"VALIDATION-FIRE-DETAIL",jobTitle:"Disposable Fire Alarm Detail",customerId,customerCode:"VALIDATION",customerName:"Disposable Validation",templateId,configurationRevisionId:revisionId,performedAt:"2026-08-07T00:00:00.000000Z",receivedAt:"2026-08-07T00:01:00.000000Z",originalCreatorSnapshot:{source:"device_reported",userId:1,username:"device-inspector",role:"inspector",capturedAt:"2026-08-07T00:00:00.000Z"},inspectionSnapshot:{schemaVersion:1,acceptedAt:"2026-08-07T00:00:00.000Z",job:{id:jobId,reference:"VALIDATION-FIRE-DETAIL",title:"Disposable Fire Alarm Detail"},customer:{id:customerId,code:"VALIDATION",displayName:"Disposable Validation"},configuration:{revisionId,revisionNumber:1},template:{id:templateId,code:"MFE-FSSR",version:3},system,instance:{instanceKey:"primary",displaySequence:1,zone:null,location:null}},responses};
const clone=<T>(value:T):T=>structuredClone(value);const assert=(ok:unknown,message:string)=>{if(!ok)throw new Error(message);};
assert(validateStoredFireAlarmDetail(row),"valid atomic Fire Alarm detail rejected");
const mutations:Array<[string,(value:any)=>void]>=[
 ["extra response key",v=>v.responses.extra=true],["duplicate row UUID",v=>v.responses.secondaryAlarmDeviceRows[0].rowUuid=v.responses.primaryDeviceRows[0].rowUuid],["invalid enum",v=>v.responses.primaryDeviceRows[0].smokeDetector="bad"],["malformed parent identity",v=>v.inspectionSnapshot.job.id=id()],["malformed child instance",v=>v.inspectionSnapshot.instance.instanceKey="other"],["malformed zone",v=>v.inspectionSnapshot.instance.zone={}],["malformed location",v=>v.inspectionSnapshot.instance.location={}],["malformed sequence",v=>v.inspectionSnapshot.instance.displaySequence=2],["malformed creator",v=>v.originalCreatorSnapshot.extra=true],["invalid performed calendar date",v=>v.performedAt="2026-02-31T00:00:00.000000Z"],["impossible received leap date",v=>v.receivedAt="2025-02-29T00:00:00.000000Z"],["acceptedAt must be a string",v=>v.inspectionSnapshot.acceptedAt=1],["invalid accepted calendar date",v=>v.inspectionSnapshot.acceptedAt="2026-02-31T00:00:00.000Z"],["malformed accepted timezone",v=>v.inspectionSnapshot.acceptedAt="2026-08-07T00:00:00.000+00:00"],["non-canonical accepted timestamp",v=>v.inspectionSnapshot.acceptedAt="2026-08-07T00:00:00Z"],["impossible creator leap date",v=>v.originalCreatorSnapshot.capturedAt="2025-02-29T00:00:00.000Z"],["creator timestamp offset rejected",v=>v.originalCreatorSnapshot.capturedAt="2026-08-07T00:00:00.000+00:00"],["wrong template",v=>v.inspectionSnapshot.template.version=2],["wrong configuration",v=>v.inspectionSnapshot.configuration.revisionId=id()],["configured row after technician",v=>v.responses.primaryDeviceRows.unshift({...v.responses.primaryDeviceRows[0],rowUuid:id(),source:"technician",configuredLocationId:null,configuredRowOrdinal:null,zoneSnapshot:null,locationSnapshot:null,displaySequence:1,assetReference:"",alarmZone:"Technician",location:"Technician"})]
];
for(const [name,change] of mutations){const value=clone(row);change(value);assert(!validateStoredFireAlarmDetail(value),`${name} rendered instead of failing closed`);}
console.log(JSON.stringify({status:"PASS",checks:mutations.length+1,atomicTables:true,noInternalFingerprint:true,note:"HTTP authentication/404 behavior is enforced by requireRole and the focused route; integration is exercised against Docker separately."},null,2));
