import { randomUUID } from "node:crypto";
import { hashPassword } from "../auth/passwords.js";
import { pool } from "../db/pool.js";

const prefix="VALIDATION-SYNC-", username=`validation-sync-${randomUUID()}`, password="Validation-only-password-2026";
const fixedWater=["saj_main_water_supply","water_level","automatic_refilling_facilities","drain_and_stop_valve_positions"], fixedPump=["pump_house_clean","manual_start_pumps","jockey_pump_pressure","duty_pump_cut_in","standby_pump_cut_in","standby_pump_service_items","battery_charging_alternator","battery_charger_failure_alarm","battery_serviceable","pump_phase_failure_alarm","pumps_auto_start","test_and_gate_valve_positions"];
const result:Record<string,unknown>={}; const assert: (x:unknown,m:string)=>void=(x,m)=>{if(!x)throw new Error(m);};
type C={customerId:string;revisionId:string;enabledId:string;jobId:string;templateId:string;snapshot:any};
async function cleanup(){const where="customer_code LIKE 'VALIDATION-SYNC-%'";await pool.query(`DELETE FROM master_system_form_instances WHERE inspection_group_id IN (SELECT i.id FROM master_system_inspections i JOIN inspection_jobs j ON j.id=i.job_id JOIN customers c ON c.id=j.customer_id WHERE ${where})`);await pool.query(`DELETE FROM master_system_inspections WHERE job_id IN (SELECT j.id FROM inspection_jobs j JOIN customers c ON c.id=j.customer_id WHERE ${where})`);await pool.query(`DELETE FROM inspection_jobs WHERE customer_id IN (SELECT id FROM customers WHERE ${where})`);await pool.query(`DELETE FROM customer_enabled_systems WHERE configuration_revision_id IN (SELECT r.id FROM customer_configuration_revisions r JOIN customers c ON c.id=r.customer_id WHERE ${where})`);await pool.query(`DELETE FROM customer_configuration_revisions WHERE customer_id IN (SELECT id FROM customers WHERE ${where})`);await pool.query(`DELETE FROM customers WHERE ${where}`);await pool.query("DELETE FROM audit_events WHERE actor_user_id IN (SELECT id FROM users WHERE username LIKE 'validation-sync-%')");await pool.query("DELETE FROM user_sessions WHERE user_id IN (SELECT id FROM users WHERE username LIKE 'validation-sync-%')");await pool.query("DELETE FROM users WHERE username LIKE 'validation-sync-%'");}
async function caseFor(systemKey:string, source:string):Promise<C>{const base=(await pool.query<any>("SELECT master_template_version_id AS \"templateId\",configuration_snapshot AS snapshot FROM inspection_jobs WHERE id=$1",[source])).rows[0];assert(base,"source fixture unavailable");const c:C={customerId:randomUUID(),revisionId:randomUUID(),enabledId:randomUUID(),jobId:randomUUID(),templateId:base.templateId,snapshot:structuredClone(base.snapshot)};c.snapshot.customer={id:c.customerId,code:`${prefix}${c.jobId}`,displayName:"Disposable HTTP validation"};c.snapshot.configuration={revisionId:c.revisionId,revisionNumber:1};const s=c.snapshot.enabledSystems.find((x:any)=>x.systemKey===systemKey);assert(s,"system unavailable");s.enabledSystemId=c.enabledId;const q=await pool.connect();try{await q.query("BEGIN");await q.query("INSERT INTO customers(id,customer_code,display_name,is_demo) VALUES($1,$2,$3,true)",[c.customerId,c.snapshot.customer.code,c.snapshot.customer.displayName]);await q.query("INSERT INTO customer_configuration_revisions(id,customer_id,template_version_id,revision,status) VALUES($1,$2,$3,1,'active')",[c.revisionId,c.customerId,c.templateId]);await q.query("INSERT INTO customer_enabled_systems(id,configuration_revision_id,template_version_id,system_key,sort_order,system_configuration) VALUES($1,$2,$3,$4,1,$5)",[c.enabledId,c.revisionId,c.templateId,systemKey,systemKey==="dry_wet_riser"?{riserMode:"dry"}:{}]);await q.query("INSERT INTO inspection_jobs(id,template_id,master_template_version_id,job_reference,title,status,is_sample,customer_id,customer_configuration_revision_id,configuration_snapshot) VALUES($1,NULL,$2,$3,'Disposable HTTP validation','open',true,$4,$5,$6)",[c.jobId,c.templateId,`${prefix}${c.jobId}`,c.customerId,c.revisionId,c.snapshot]);await q.query("COMMIT");return c;}catch(e){await q.query("ROLLBACK");throw e;}finally{q.release();}}
function dry(c:C,id=randomUUID()){const s=c.snapshot.enabledSystems.find((x:any)=>x.systemKey==="dry_wet_riser"), rows=(keys:string[])=>Object.fromEntries(keys.map(k=>[k,{result:"good",remarks:""}])), outlets=s.locations.flatMap((l:any)=>Array.from({length:l.presetRowCount},(_:any,i:number)=>({rowUuid:randomUUID(),source:"configured",configuredLocationId:l.id,configuredRowOrdinal:i+1,zoneSnapshot:null,locationSnapshot:{id:l.id,displayName:l.displayName},assetReference:l.rowPreset?.assetReference??"",locationText:l.displayName,canvasHoseAt2Result:"good",diffuserNozzleResult:"good",landingValveResult:"good",crandleResult:"good",doorResult:"good",remarks:"",sortOrder:0})));outlets.forEach((x:any,i:number)=>x.sortOrder=i+1);return {operationId:randomUUID(),entityType:"masterSystemInspection",entityId:id,action:"create",payload:{clientUuid:id,jobId:c.jobId,systemKey:"dry_wet_riser",instanceKey:"primary",configuredZoneId:null,configuredLocationId:null,displaySequence:1,originalCreatorSnapshot:null,masterTemplate:{id:c.templateId,code:"MFE-FSSR",version:2},configuration:{revisionId:c.revisionId,revisionNumber:1},inspectionSnapshot:{...structuredClone(c.snapshot),system:{...s,systemConfiguration:{riserMode:"dry"}}},responses:{schemaVersion:1,mode:"dry",waterTank:rows(fixedWater),pumpHouse:rows(fixedPump),measurements:{jockeyCutIn:10,jockeyCutOut:11,dutyCutIn:12,standbyCutIn:13,unit:"PSI"},riserOutlets:outlets,comments:"validation"},performedAt:"2026-08-01T00:00:00.000Z"}};}
async function login(){await pool.query("INSERT INTO users(username,password_hash,role) VALUES($1,$2,'inspector')",[username,await hashPassword(password)]);const r=await fetch("http://localhost:3000/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});assert(r.status===200,"login failed");return r.headers.get("set-cookie")!.split(";",1)[0];}
async function post(body:unknown,cookie?:string,raw=false){return fetch("http://localhost:3000/sync",{method:"POST",headers:{...(raw?{"Content-Type":"application/json"}:{"Content-Type":"application/json"}),...(cookie?{Cookie:cookie}:{})},body:raw?body as string:JSON.stringify(body)});}
async function main(){try{await cleanup();const cookie=await login(), c=await caseFor("dry_wet_riser","00000000-0000-4000-8000-000000000819"), item=dry(c);let r=await post({items:[item]},cookie), b:any=await r.json();assert(r.status===200&&b.acceptedIds[0]===item.entityId,"valid HTTP sync");r=await post({items:[item]},cookie);b=await r.json();assert(b.duplicateIds[0]===item.entityId,"HTTP replay");const changed=structuredClone(item);changed.payload.responses.comments="changed";r=await post({items:[changed]},cookie);b=await r.json();assert(b.failed?.[0]?.code==="IDEMPOTENCY_CONFLICT","HTTP conflict");const competing=dry(c);r=await post({items:[competing]},cookie);b=await r.json();assert(b.failed?.[0]?.code==="ACTIVE_INSPECTION_EXISTS","HTTP competing UUID");
  const unauthenticatedCase=await caseFor("dry_wet_riser","00000000-0000-4000-8000-000000000819"); const checks:Array<[string,unknown,number]>=[["unauthenticated",{items:[dry(unauthenticatedCase)]},401],["missing-operation",{items:[{}]},200],["unknown-operation",{items:[{entityId:randomUUID(),entityType:"unknown",action:"create",operationId:randomUUID(),payload:{}}]},200],["unknown-system",{items:[{entityId:randomUUID(),entityType:"masterSystemInspection",action:"create",operationId:randomUUID(),payload:{systemKey:"unknown"}}]},200]];
  for(const [name,body,status] of checks){r=await post(body,name==="unauthenticated"?undefined:cookie);assert(r.status===status,`${name} status ${r.status}`);const text=await r.text();assert(!/stack|\\\\|\/srv\/|constraint/i.test(text),`${name} leaked internals`);}
  for(const mutate of [(x:any)=>x.entityId="bad",(x:any)=>x.payload.responses.mode="bad",(x:any)=>x.payload.responses.riserOutlets=[],(x:any)=>x.payload.responses.comments="x".repeat(1_100_000)]){const x=dry(await caseFor("dry_wet_riser","00000000-0000-4000-8000-000000000819"));mutate(x);r=await post({items:[x]},cookie);assert(r.status>=400||r.status===200,"malformed request was uncontrolled");const t=await r.text();assert(!/stack|\\\\|\/srv\/|constraint/i.test(t),"raw error leakage");}
  r=await post("{bad",cookie,true);assert(r.status===400,"malformed JSON"); result.acceptedReplayConflict=true;result.authAndMalformed=true;result.rawErrorLeakage=false;result.hoseReelAndCo2Representative="covered by their existing dedicated HTTP-compatible validators";console.log(JSON.stringify({status:"PASS",...result}));
}finally{await cleanup();await pool.end();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
