// @ts-nocheck
import { randomUUID } from "node:crypto";
import { pool } from "../db/pool.js";
import {
  assertDryWetRiserFixture,
  assertPublishedMasterServiceReportTemplate,
  seedMasterServiceReport
} from "../db/seedMasterServiceReport.js";
import { masterServiceReportV2 } from "../inspections/templates/masterServiceReportV2.js";
import { setDryWetRiserSyncTestBarrier, syncDryWetRiserInspections } from "../sync/dryWetRiserInspectionSync.js";
import { createSession, hashSessionToken } from "../auth/sessionTokens.js";

type Mode = "dry" | "wet";
type Case = { customerId:string; revisionId:string; enabledId:string; jobId:string; templateId:string; snapshot:Record<string, any> };
const fixedWater=["saj_main_water_supply","water_level","automatic_refilling_facilities","drain_and_stop_valve_positions"];
const fixedPump=["pump_house_clean","manual_start_pumps","jockey_pump_pressure","duty_pump_cut_in","standby_pump_cut_in","standby_pump_service_items","battery_charging_alternator","battery_charger_failure_alarm","battery_serviceable","pump_phase_failure_alarm","pumps_auto_start","test_and_gate_valve_positions"];
const created:Case[]=[];
const result:Record<string, unknown>={};
let actorUserId: number | undefined;
let validationSessionToken: string | undefined;
const assert=(ok:unknown,message:string)=>{if(!ok)throw new Error(message);};
const failureCode=(r:any)=>r.failed?.[0]?.code;

async function createCase(mode:Mode, dbConfig:unknown={riserMode:mode}, frozenConfig:unknown={riserMode:mode}) {
  const base=(await pool.query<any>("SELECT master_template_version_id AS \"templateId\",configuration_snapshot AS snapshot FROM inspection_jobs WHERE id='00000000-0000-4000-8000-000000000819'")).rows[0];
  if(!base)throw new Error("Dry/Wet source fixture is unavailable");
  const c:Case={customerId:randomUUID(),revisionId:randomUUID(),enabledId:randomUUID(),jobId:randomUUID(),templateId:base.templateId,snapshot:structuredClone(base.snapshot)};
  c.snapshot.customer={id:c.customerId,code:`VALIDATION-RISER-${c.jobId}`,displayName:"Disposable Riser Validation"};
  c.snapshot.configuration={revisionId:c.revisionId,revisionNumber:1};
  const system=c.snapshot.enabledSystems.find((x:any)=>x.systemKey==="dry_wet_riser");
  system.enabledSystemId=c.enabledId; system.systemConfiguration=frozenConfig;
  const client=await pool.connect();try{await client.query("BEGIN");await client.query("INSERT INTO customers(id,customer_code,display_name,is_demo) VALUES($1,$2,'Disposable Riser Validation',true)",[c.customerId,`VALIDATION-RISER-${c.jobId}`]);await client.query("INSERT INTO customer_configuration_revisions(id,customer_id,template_version_id,revision,status) VALUES($1,$2,$3,1,'active')",[c.revisionId,c.customerId,c.templateId]);await client.query("INSERT INTO customer_enabled_systems(id,configuration_revision_id,template_version_id,system_key,sort_order,system_configuration) VALUES($1,$2,$3,'dry_wet_riser',1,$4)",[c.enabledId,c.revisionId,c.templateId,dbConfig]);await client.query("INSERT INTO inspection_jobs(id,template_id,master_template_version_id,job_reference,title,status,is_sample,customer_id,customer_configuration_revision_id,configuration_snapshot) VALUES($1,NULL,$2,$3,'Disposable Riser Validation','open',true,$4,$5,$6)",[c.jobId,c.templateId,`VALIDATION-RISER-${c.jobId}`,c.customerId,c.revisionId,c.snapshot]);await client.query("COMMIT");created.push(c);return c;}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
function payload(c:Case, mode:unknown, submittedConfig:unknown={riserMode:mode}, id=randomUUID()) { const system=c.snapshot.enabledSystems.find((x:any)=>x.systemKey==="dry_wet_riser"); const rows=(keys:string[])=>Object.fromEntries(keys.map(k=>[k,{result:"good",remarks:""}])); const outlets=system.locations.flatMap((l:any)=>Array.from({length:l.presetRowCount},(_:unknown,i:number)=>({rowUuid:randomUUID(),source:"configured",configuredLocationId:l.id,configuredRowOrdinal:i+1,zoneSnapshot:null,locationSnapshot:{id:l.id,displayName:l.displayName},assetReference:l.rowPreset?.assetReference??"",locationText:l.displayName,canvasHoseAt2Result:"good",diffuserNozzleResult:"good",landingValveResult:"good",crandleResult:"good",doorResult:"good",remarks:"",sortOrder:0})));outlets.forEach((row:any,index:number)=>row.sortOrder=index+1); return {operationId:randomUUID(),entityType:"masterSystemInspection",entityId:id,action:"create",payload:{clientUuid:id,jobId:c.jobId,systemKey:"dry_wet_riser",instanceKey:"primary",configuredZoneId:null,configuredLocationId:null,displaySequence:1,originalCreatorSnapshot:null,masterTemplate:{id:c.templateId,code:"MFE-FSSR",version:2},configuration:{revisionId:c.revisionId,revisionNumber:1},inspectionSnapshot:{...structuredClone(c.snapshot),system:{...system,systemConfiguration:submittedConfig}},responses:{schemaVersion:1,mode,waterTank:rows(fixedWater),pumpHouse:rows(fixedPump),measurements:{jockeyCutIn:10,jockeyCutOut:11,dutyCutIn:12,standbyCutIn:13,unit:"PSI"},riserOutlets:outlets,comments:"validation"},performedAt:"2026-07-29T00:00:00.000Z"}}; }
function technicianRow(from:any, locationText:string){return {...from,rowUuid:randomUUID(),source:"technician",configuredLocationId:null,configuredRowOrdinal:null,zoneSnapshot:null,locationSnapshot:null,assetReference:"",locationText};}
async function submit(item:any){return syncDryWetRiserInspections([item],actorUserId);}
async function cleanupValidationData(){await pool.query("DELETE FROM master_system_form_instances WHERE inspection_group_id IN (SELECT inspection.id FROM master_system_inspections inspection INNER JOIN inspection_jobs job ON job.id=inspection.job_id INNER JOIN customers customer ON customer.id=job.customer_id WHERE customer.customer_code LIKE 'VALIDATION-RISER-%')");await pool.query("DELETE FROM master_system_inspections WHERE job_id IN (SELECT job.id FROM inspection_jobs job INNER JOIN customers customer ON customer.id=job.customer_id WHERE customer.customer_code LIKE 'VALIDATION-RISER-%')");await pool.query("DELETE FROM inspection_jobs WHERE customer_id IN (SELECT id FROM customers WHERE customer_code LIKE 'VALIDATION-RISER-%')");await pool.query("DELETE FROM customer_enabled_systems WHERE configuration_revision_id IN (SELECT id FROM customer_configuration_revisions WHERE customer_id IN (SELECT id FROM customers WHERE customer_code LIKE 'VALIDATION-RISER-%'))");await pool.query("DELETE FROM customer_configuration_revisions WHERE customer_id IN (SELECT id FROM customers WHERE customer_code LIKE 'VALIDATION-RISER-%')");await pool.query("DELETE FROM customers WHERE customer_code LIKE 'VALIDATION-RISER-%'");}
async function accepted(mode:Mode){const c=await createCase(mode);const item=payload(c,mode);const r=await submit(item);assert(r.acceptedIds[0]===item.entityId,`${mode} was not accepted: ${JSON.stringify(r)}`);const stored=(await pool.query<any>("SELECT response_payload,inspection_snapshot FROM master_system_form_instances WHERE client_uuid=$1",[item.entityId])).rows[0];assert(stored.response_payload.mode===mode&&stored.inspection_snapshot.system.systemConfiguration.riserMode===mode,`${mode} was not canonical`);return {c,item};}
async function endpoint(path:string, authenticated=true){return fetch(`http://localhost:3000${path}`,authenticated?{headers:{Cookie:`inspection_session=${validationSessionToken}`}}:undefined);}
async function validateServerDetail(acceptedCase:{c:Case;item:any}){const id=acceptedCase.item.entityId;const response=await endpoint(`/dry-wet-riser-inspections/${id}`);assert(response.status===200,`accepted detail status ${response.status}`);const body=await response.json() as any;const detail=body.inspection;assert(detail.clientUuid===id&&detail.responses.riserOutlets.length>0&&detail.responses.mode===detail.systemConfiguration.riserMode&&typeof detail.syncedByUsername==='string','accepted detail was not canonical');assert((await endpoint(`/dry-wet-riser-inspections/${randomUUID()}`)).status===404,'unknown detail did not return 404');assert((await endpoint(`/dry-wet-riser-inspections/${id}`,false)).status===401,'unauthenticated detail did not return 401');const original=(await pool.query<{responsePayload:any}>('SELECT response_payload AS "responsePayload" FROM master_system_form_instances WHERE client_uuid=$1',[id])).rows[0]?.responsePayload;assert(original,'accepted detail payload is missing');const swapped=structuredClone(original);[swapped.riserOutlets[0],swapped.riserOutlets[1]]=[swapped.riserOutlets[1],swapped.riserOutlets[0]];const malformed=[{}, {...structuredClone(original),mode:"wet"}, {...structuredClone(original),riserOutlets:[]}, {...structuredClone(original),riserOutlets:[{...original.riserOutlets[0],locationSnapshot:{id:original.riserOutlets[0].configuredLocationId,displayName:"forged"},sortOrder:1},...original.riserOutlets.slice(1)]}, swapped, {...structuredClone(original),riserOutlets:original.riserOutlets.map((row:any,index:number)=>({...row,sortOrder:index+2}))}];try{for(const value of malformed){await pool.query('UPDATE master_system_form_instances SET response_payload=$1 WHERE client_uuid=$2',[value,id]);assert((await endpoint(`/dry-wet-riser-inspections/${id}`)).status===404,'malformed detail did not fail closed');}}finally{await pool.query('UPDATE master_system_form_instances SET response_payload=$1 WHERE client_uuid=$2',[original,id]);}result.serverDetail={accepted:true,unknown404:true,unauthenticated401:true,modeAndOrderingFailures:true};}
async function v2TemplateConflict(label:string, mutate:(client:any)=>Promise<void>){const client=await pool.connect();try{await client.query("BEGIN");await mutate(client);let rejected=false;try{await assertPublishedMasterServiceReportTemplate(client,"Published Master V2",masterServiceReportV2);}catch{rejected=true;}assert(rejected,`V2 template conflict was silently accepted: ${label}`);await client.query("ROLLBACK");await assertPublishedMasterServiceReportTemplate(client,"Published Master V2",masterServiceReportV2);result[`v2TemplateConflict:${label}`]={rejected:true,repaired:false};}catch(error){await client.query("ROLLBACK").catch(()=>undefined);throw error;}finally{client.release();}}
async function deterministicRace(boundary:"beforeParentInsert"|"beforeFormInsert", left:any, right:any) { let reached=0; let release!:()=>void; const ready=new Promise<void>(resolve=>{release=resolve;}); setDryWetRiserSyncTestBarrier(async point=>{if(point!==boundary)return;reached+=1;if(reached===2)release();await ready;}); try { const outcomes=await Promise.all([submit(left),submit(right)]); assert(reached===2,`both transactions did not reach ${boundary}`); return outcomes; } finally { setDryWetRiserSyncTestBarrier(undefined); } }
function outcomeCodes(outcomes:any[]){return outcomes.map(value=>value.acceptedIds.length?"ACCEPTED":value.duplicateIds.length?"DUPLICATE":failureCode(value));}
async function parentAndFormCounts(jobId:string){const parent=(await pool.query<any>("SELECT count(*)::int count FROM master_system_inspections WHERE job_id=$1 AND system_key='dry_wet_riser'",[jobId])).rows[0].count;const form=(await pool.query<any>("SELECT count(*)::int count FROM master_system_form_instances form JOIN master_system_inspections inspection ON inspection.id=form.inspection_group_id WHERE inspection.job_id=$1 AND inspection.system_key='dry_wet_riser'",[jobId])).rows[0].count;return{parent,form};}
async function main(){try{await cleanupValidationData();actorUserId=(await pool.query<{id:number}>("SELECT id FROM users WHERE is_active=true ORDER BY id LIMIT 1")).rows[0]?.id;assert(actorUserId,"validation actor is unavailable");
  validationSessionToken=(await createSession(actorUserId)).token;const dry=await accepted("dry"),wet=await accepted("wet");result.dryAccepted=true;result.wetAccepted=true;await validateServerDetail(dry);
  const altered=await createCase("dry");assert(failureCode(await submit(payload(altered,"wet",{riserMode:"dry"})))==="VALIDATION_ERROR","altered response mode");
  const alteredSnapshot=await createCase("dry");assert(failureCode(await submit(payload(alteredSnapshot,"dry",{riserMode:"wet"})))==="VALIDATION_ERROR","altered snapshot mode");
  const missingDb=await createCase("dry",{});assert(failureCode(await submit(payload(missingDb,"dry")))==="CONFIGURATION_ERROR","missing db mode");
  const missingFrozen=await createCase("dry",{riserMode:"dry"},{});assert(failureCode(await submit(payload(missingFrozen,"dry")))==="CONFIGURATION_ERROR","missing frozen mode");
  const invalid=await createCase("dry");assert(failureCode(await submit(payload(invalid,"other",{riserMode:"other"})))==="VALIDATION_ERROR","invalid mode");
  const extra=await createCase("dry");assert(failureCode(await submit(payload(extra,"dry",{riserMode:"dry",extra:true})))==="VALIDATION_ERROR","extra configuration key");result.modeRejections=true;
  const reject=async (label:string, change:(item:any)=>void)=>{const c=await createCase("dry"),item=payload(c,"dry");change(item);assert(failureCode(await submit(item))==="VALIDATION_ERROR",label);};
  await reject("forged configured location",x=>x.payload.responses.riserOutlets[0].locationSnapshot.displayName="forged");
  await reject("forged configured location text",x=>x.payload.responses.riserOutlets[0].locationText="forged");
  await reject("forged preset provenance",x=>x.payload.responses.riserOutlets[0].assetReference="forged");
  await reject("forged location id",x=>x.payload.responses.riserOutlets[0].configuredLocationId=randomUUID());
  await reject("technician configured ids",x=>Object.assign(x.payload.responses.riserOutlets[0],{source:"technician",configuredLocationId:x.payload.responses.riserOutlets[0].configuredLocationId,configuredRowOrdinal:1}));
  await reject("technician location snapshot",x=>Object.assign(x.payload.responses.riserOutlets[0],{source:"technician",configuredLocationId:null,configuredRowOrdinal:null,locationSnapshot:{id:randomUUID(),displayName:"forged"},zoneSnapshot:null,assetReference:""}));
  await reject("unknown creator field",x=>x.payload.originalCreatorSnapshot={source:"device_reported",userId:1,username:"x",role:"inspector",capturedAt:"2026-07-29T00:00:00.000Z",extra:true});
  await reject("malformed creator",x=>x.payload.originalCreatorSnapshot={source:"device_reported",userId:"bad",username:"x",role:"inspector",capturedAt:"bad"});
  await reject("oversized creator",x=>x.payload.originalCreatorSnapshot={source:"device_reported",userId:1,username:"x".repeat(161),role:"inspector",capturedAt:"2026-07-29T00:00:00.000Z"});
  await reject("wrong template code",x=>x.payload.masterTemplate.code="wrong"); await reject("wrong template version",x=>x.payload.masterTemplate.version=3); await reject("wrong template id",x=>x.payload.masterTemplate.id=randomUUID());
  await reject("wrong revision id",x=>x.payload.configuration.revisionId=randomUUID()); await reject("wrong revision number",x=>x.payload.configuration.revisionNumber=99);
  await reject("zero outlets",x=>x.payload.responses.riserOutlets=[]); await reject("outlet maximum",x=>{const row=x.payload.responses.riserOutlets[0];x.payload.responses.riserOutlets=Array.from({length:251},(_,i)=>({...row,rowUuid:randomUUID(),sortOrder:i+1,source:"technician",configuredLocationId:null,configuredRowOrdinal:null,locationSnapshot:null,zoneSnapshot:null,assetReference:"",locationText:`technician ${i}`}));}); result.canonicalRejections=true;
  await reject("creator zero user id",x=>x.payload.originalCreatorSnapshot={source:"device_reported",userId:0,username:"x",role:"inspector",capturedAt:"2026-07-29T00:00:00.000Z"}); await reject("creator negative user id",x=>x.payload.originalCreatorSnapshot={source:"device_reported",userId:-1,username:"x",role:"inspector",capturedAt:"2026-07-29T00:00:00.000Z"}); await reject("creator unsafe user id",x=>x.payload.originalCreatorSnapshot={source:"device_reported",userId:Number.MAX_SAFE_INTEGER+1,username:"x",role:"inspector",capturedAt:"2026-07-29T00:00:00.000Z"}); await reject("creator blank username",x=>x.payload.originalCreatorSnapshot={source:"device_reported",userId:1,username:"",role:"inspector",capturedAt:"2026-07-29T00:00:00.000Z"}); await reject("creator whitespace username",x=>x.payload.originalCreatorSnapshot={source:"device_reported",userId:1,username:"   ",role:"inspector",capturedAt:"2026-07-29T00:00:00.000Z"}); await reject("creator date only",x=>x.payload.originalCreatorSnapshot={source:"device_reported",userId:1,username:"x",role:"inspector",capturedAt:"2026-07-29"}); await reject("creator locale timestamp",x=>x.payload.originalCreatorSnapshot={source:"device_reported",userId:1,username:"x",role:"inspector",capturedAt:"07/29/2026 00:00"}); await reject("creator timezone missing",x=>x.payload.originalCreatorSnapshot={source:"device_reported",userId:1,username:"x",role:"inspector",capturedAt:"2026-07-29T00:00:00.000"}); await reject("creator malformed timestamp",x=>x.payload.originalCreatorSnapshot={source:"device_reported",userId:1,username:"x",role:"inspector",capturedAt:"2026-02-30T00:00:00.000Z"}); await reject("creator oversized timestamp",x=>x.payload.originalCreatorSnapshot={source:"device_reported",userId:1,username:"x",role:"inspector",capturedAt:"2026-07-29T00:00:00.000Zx"}); const creatorCase=await createCase("dry"),creatorItem=payload(creatorCase,"dry");creatorItem.payload.originalCreatorSnapshot={source:"device_reported",userId:1,username:"  device technician  ",role:"inspector",capturedAt:"2026-07-29T00:00:00.000Z"};assert(creatorItem.entityId===(await submit(creatorItem)).acceptedIds[0],"valid creator snapshot was rejected");assert((await pool.query<any>('SELECT original_creator_snapshot AS "creator" FROM master_system_form_instances WHERE client_uuid=$1',[creatorItem.entityId])).rows[0].creator.username==="device technician","creator snapshot was not canonicalized");result.creatorValidation=true;
  const orderingCase=await createCase("dry"),orderingItem=payload(orderingCase,"dry"),configured=orderingItem.payload.responses.riserOutlets.reverse(),first=configured[0],technicians=[technicianRow(first,"Technician A"),technicianRow(first,"Technician B")];orderingItem.payload.responses.riserOutlets=[technicians[0],...configured,technicians[1]];orderingItem.payload.responses.riserOutlets.forEach((row:any,index:number)=>row.sortOrder=index+1);assert(orderingItem.entityId===(await submit(orderingItem)).acceptedIds[0],"reordered configured rows were rejected");const ordered=(await pool.query<any>('SELECT response_payload AS "responses" FROM master_system_form_instances WHERE client_uuid=$1',[orderingItem.entityId])).rows[0].responses.riserOutlets,expectedLocations=orderingCase.snapshot.enabledSystems.find((s:any)=>s.systemKey==="dry_wet_riser").locations.slice().sort((a:any,b:any)=>a.sortOrder-b.sortOrder||String(a.id).localeCompare(String(b.id))).flatMap((location:any)=>Array.from({length:location.presetRowCount},(_:any,index:number)=>`${location.id}:${index+1}`));assert(JSON.stringify(ordered.filter((row:any)=>row.source==="configured").map((row:any)=>`${row.configuredLocationId}:${row.configuredRowOrdinal}`))===JSON.stringify(expectedLocations)&&ordered.slice(expectedLocations.length).map((row:any)=>row.locationText).join(",")==="Technician A,Technician B"&&ordered.every((row:any,index:number)=>row.sortOrder===index+1),"stored outlet order was not canonical");const orderedReplay=structuredClone(orderingItem);orderedReplay.operationId=randomUUID();orderedReplay.payload.responses.riserOutlets=[...configured.reverse(),...technicians].map((row:any,index:number)=>({...row,sortOrder:index+1}));assert((await submit(orderedReplay)).duplicateIds[0]===orderingItem.entityId,"reordered equivalent replay was not duplicate");const orderedChanged=structuredClone(orderedReplay);orderedChanged.operationId=randomUUID();orderedChanged.payload.responses.riserOutlets[0].remarks="changed";assert(failureCode(await submit(orderedChanged))==="IDEMPOTENCY_CONFLICT","changed normalized replay did not conflict");await reject("missing configured identity",x=>x.payload.responses.riserOutlets.splice(0,1));await reject("duplicate configured identity",x=>x.payload.responses.riserOutlets.push({...x.payload.responses.riserOutlets[0],rowUuid:randomUUID(),sortOrder:x.payload.responses.riserOutlets.length+1}));result.canonicalOrdering=true;
  const replay=await accepted("dry");const duplicate=await submit(replay.item);assert(duplicate.duplicateIds[0]===replay.item.entityId,"duplicate replay");const changed=structuredClone(replay.item);changed.payload.responses.comments="changed";assert(failureCode(await submit(changed))==="IDEMPOTENCY_CONFLICT","changed replay");const changedMode=structuredClone(replay.item);changedMode.payload.responses.mode="wet";assert(failureCode(await submit(changedMode))==="VALIDATION_ERROR","changed mode replay");const storedReplay=(await pool.query<any>("SELECT response_payload,inspection_snapshot FROM master_system_form_instances WHERE client_uuid=$1",[replay.item.entityId])).rows[0];assert(storedReplay.response_payload.riserOutlets.every((r:any)=>r.source==="configured"?r.locationText===r.locationSnapshot.displayName&&r.assetReference===replay.c.snapshot.enabledSystems.find((s:any)=>s.systemKey==="dry_wet_riser").locations.find((l:any)=>l.id===r.configuredLocationId).rowPreset.assetReference:r.locationSnapshot===null&&r.zoneSnapshot===null&&r.assetReference===""),"stored provenance was not canonical");const count=(await pool.query<any>("SELECT count(*)::int AS count FROM master_system_inspections WHERE job_id=$1",[replay.c.jobId])).rows[0].count;assert(count===1,"duplicate added parent");result.idempotency=true;
  const competing=await accepted("wet");assert(failureCode(await submit(payload(competing.c,"wet")))==="ACTIVE_INSPECTION_EXISTS","competing UUID");result.competingUuid=true;
  const concurrent=await createCase("dry");const differentLeft=payload(concurrent,"dry"),differentRight=payload(concurrent,"dry");const different=await deterministicRace("beforeParentInsert",differentLeft,differentRight),differentCodes=outcomeCodes(different),differentCounts=await parentAndFormCounts(concurrent.jobId);assert(differentCodes.filter(x=>x==="ACCEPTED").length===1&&differentCodes.filter(x=>x==="ACTIVE_INSPECTION_EXISTS").length===1&&!differentCodes.includes("SERVER_ERROR")&&differentCounts.parent===1&&differentCounts.form===1,"deterministic different UUID race");result.deterministicDifferentUuid={codes:differentCodes,counts:differentCounts};
  const identical=await createCase("dry"),sameUuid=randomUUID(),sameLeft=payload(identical,"dry",undefined,sameUuid),sameRight=structuredClone(sameLeft);sameRight.operationId=randomUUID();const identicalOutcomes=await deterministicRace("beforeParentInsert",sameLeft,sameRight),identicalCodes=outcomeCodes(identicalOutcomes),identicalCounts=await parentAndFormCounts(identical.jobId);assert(identicalCodes.filter(x=>x==="ACCEPTED").length===1&&identicalCodes.filter(x=>x==="DUPLICATE").length===1&&!identicalCodes.includes("SERVER_ERROR")&&identicalCounts.parent===1&&identicalCounts.form===1,"deterministic identical UUID race");result.deterministicSameUuidIdentical={codes:identicalCodes,counts:identicalCounts};
  const changedCase=await createCase("dry"),changedUuid=randomUUID(),changedLeft=payload(changedCase,"dry",undefined,changedUuid),changedRight=structuredClone(changedLeft);changedRight.operationId=randomUUID();changedRight.payload.responses.comments="changed canonical payload";const changedOutcomes=await deterministicRace("beforeParentInsert",changedLeft,changedRight),changedCodes=outcomeCodes(changedOutcomes),changedCounts=await parentAndFormCounts(changedCase.jobId),storedChanged=(await pool.query<any>("SELECT response_payload FROM master_system_form_instances WHERE client_uuid=$1",[changedUuid])).rows[0];assert(changedCodes.filter(x=>x==="ACCEPTED").length===1&&changedCodes.filter(x=>x==="IDEMPOTENCY_CONFLICT").length===1&&!changedCodes.includes("SERVER_ERROR")&&changedCounts.parent===1&&changedCounts.form===1&&["validation","changed canonical payload"].includes(storedChanged.response_payload.comments),"deterministic changed UUID race");result.deterministicSameUuidChanged={codes:changedCodes,counts:changedCounts,storedComments:storedChanged.response_payload.comments};
  const clientLeftCase=await createCase("dry"),clientRightCase=await createCase("dry"),clientUuid=randomUUID(),clientLeft=payload(clientLeftCase,"dry",undefined,clientUuid),clientRight=payload(clientRightCase,"dry",undefined,clientUuid),clientOutcomes=await deterministicRace("beforeFormInsert",clientLeft,clientRight),clientCodes=outcomeCodes(clientOutcomes),clientForms=(await pool.query<any>("SELECT count(*)::int count FROM master_system_form_instances WHERE client_uuid=$1",[clientUuid])).rows[0].count;assert(clientCodes.filter(x=>x==="ACCEPTED").length===1&&clientCodes.filter(x=>x==="IDEMPOTENCY_CONFLICT").length===1&&!clientCodes.includes("SERVER_ERROR")&&clientForms===1,"deterministic client UUID constraint race");result.deterministicClientUuidConstraint={codes:clientCodes,forms:clientForms};
  const fixture=await pool.connect();try{await fixture.query("BEGIN");await fixture.query("UPDATE customer_enabled_systems SET system_configuration='{}'::jsonb WHERE id='00000000-0000-4000-8000-000000000812'");let failed=false;try{await assertDryWetRiserFixture(fixture,structuredClone((await fixture.query<any>("SELECT configuration_snapshot FROM inspection_jobs WHERE id='00000000-0000-4000-8000-000000000819'")).rows[0].configuration_snapshot));}catch{failed=true;}assert(failed,"fixture conflict was silently accepted");result.fixtureConflictFailsClosed=true;}finally{await fixture.query("ROLLBACK");fixture.release();}
  await v2TemplateConflict("code",client=>client.query("UPDATE master_service_report_templates SET code='MFE-FSSR-INCORRECT' WHERE id=$1",[masterServiceReportV2.id]));
  await v2TemplateConflict("name",client=>client.query("UPDATE master_service_report_templates SET name='Incorrect V2 Name' WHERE id=$1",[masterServiceReportV2.id]));
  await v2TemplateConflict("version",client=>client.query("UPDATE master_service_report_templates SET version=4 WHERE id=$1",[masterServiceReportV2.id]));
  await v2TemplateConflict("selection policy",async client=>{const constraint=(await client.query("SELECT conname FROM pg_constraint WHERE conrelid='master_service_report_templates'::regclass AND contype='c' AND pg_get_constraintdef(oid) LIKE '%selection_policy%'")).rows[0]?.conname;assert(constraint,"selection policy constraint is unavailable");await client.query(`ALTER TABLE master_service_report_templates DROP CONSTRAINT "${constraint}"`);await client.query("UPDATE master_service_report_templates SET selection_policy='incorrect' WHERE id=$1",[masterServiceReportV2.id]);});
  await v2TemplateConflict("header metadata",client=>client.query("UPDATE master_service_report_templates SET header_definition='{\"fields\":[]}'::jsonb WHERE id=$1",[masterServiceReportV2.id]));
  await v2TemplateConflict("boilerplate",client=>client.query("UPDATE master_service_report_templates SET report_boilerplate='{\"conditions\":[\"incorrect\"]}'::jsonb WHERE id=$1",[masterServiceReportV2.id]));
  await v2TemplateConflict("publication status",client=>client.query("UPDATE master_service_report_templates SET publication_status='retired' WHERE id=$1",[masterServiceReportV2.id]));
  await v2TemplateConflict("system membership",client=>client.query("INSERT INTO master_service_report_systems(template_version_id,system_key,display_name,sort_order,definition_status,definition) VALUES($1,'unexpected_v2_system','Unexpected',99,'confirmed','{}'::jsonb)",[masterServiceReportV2.id]));
  await seedMasterServiceReport(pool);await seedMasterServiceReport(pool);const repeatedStartupClient=await pool.connect();try{await assertPublishedMasterServiceReportTemplate(repeatedStartupClient,"Published Master V2",masterServiceReportV2);}finally{repeatedStartupClient.release();}result.v2TemplateRepeatedStartup=true;
  result.v1Compatible=(await pool.query("SELECT 1 FROM customer_enabled_systems WHERE system_key='hose_reel' AND system_configuration='{}'::jsonb LIMIT 1")).rowCount===1;assert(result.v1Compatible,"V1 unrelated configuration");console.log(JSON.stringify({status:"PASS",...result}));
}finally{if(validationSessionToken)await pool.query('DELETE FROM user_sessions WHERE token_hash=$1',[hashSessionToken(validationSessionToken)]);await cleanupValidationData();await pool.end();}}
main().catch(error=>{console.error(error);process.exitCode=1;});
