import { randomUUID } from "node:crypto";
import { pool } from "../db/pool.js";
import { assertDryWetRiserFixture } from "../db/seedMasterServiceReport.js";
import { syncDryWetRiserInspections } from "../sync/dryWetRiserInspectionSync.js";
import { createSession, hashSessionToken } from "../auth/sessionTokens.js";

type Mode = "dry" | "wet";
type Case = { customerId:string; revisionId:string; enabledId:string; jobId:string; templateId:string; snapshot:Record<string, any> };
const fixedWater=["saj_main_water_supply","water_level","automatic_refilling_facilities","drain_and_stop_valve_positions"];
const fixedPump=["pump_house_clean","manual_start_pumps","jockey_pump_pressure","duty_pump_cut_in","standby_pump_cut_in","standby_pump_service_items","battery_charging_alternator","battery_charger_failure_alarm","battery_serviceable","pump_phase_failure_alarm","pumps_auto_start","test_and_gate_valve_positions"];
const created:Case[]=[];
const result:Record<string, unknown>={};
let actorUserId: number | undefined;
let validationSessionToken: string | undefined;
const assert=(ok:unknown,message:string)=>{if(!ok)throw new Error(message);};
const failureCode=(r:any)=>r.failed?.[0]?.code;

async function createCase(mode:Mode, dbConfig:unknown={riserMode:mode}, frozenConfig:unknown={riserMode:mode}) {
  const base=(await pool.query<any>("SELECT master_template_version_id AS \"templateId\",configuration_snapshot AS snapshot FROM inspection_jobs WHERE id='00000000-0000-4000-8000-000000000819'")).rows[0];
  if(!base)throw new Error("Dry/Wet source fixture is unavailable");
  const c:Case={customerId:randomUUID(),revisionId:randomUUID(),enabledId:randomUUID(),jobId:randomUUID(),templateId:base.templateId,snapshot:structuredClone(base.snapshot)};
  c.snapshot.customer={id:c.customerId,code:`VALIDATION-RISER-${c.jobId}`,displayName:"Disposable Riser Validation"};
  c.snapshot.configuration={revisionId:c.revisionId,revisionNumber:1};
  const system=c.snapshot.enabledSystems.find((x:any)=>x.systemKey==="dry_wet_riser");
  system.enabledSystemId=c.enabledId; system.systemConfiguration=frozenConfig;
  const client=await pool.connect();try{await client.query("BEGIN");await client.query("INSERT INTO customers(id,customer_code,display_name,is_demo) VALUES($1,$2,'Disposable Riser Validation',true)",[c.customerId,`VALIDATION-RISER-${c.jobId}`]);await client.query("INSERT INTO customer_configuration_revisions(id,customer_id,template_version_id,revision,status) VALUES($1,$2,$3,1,'active')",[c.revisionId,c.customerId,c.templateId]);await client.query("INSERT INTO customer_enabled_systems(id,configuration_revision_id,template_version_id,system_key,sort_order,system_configuration) VALUES($1,$2,$3,'dry_wet_riser',1,$4)",[c.enabledId,c.revisionId,c.templateId,dbConfig]);await client.query("INSERT INTO inspection_jobs(id,template_id,master_template_version_id,job_reference,title,status,is_sample,customer_id,customer_configuration_revision_id,configuration_snapshot) VALUES($1,NULL,$2,$3,'Disposable Riser Validation','open',true,$4,$5,$6)",[c.jobId,c.templateId,`VALIDATION-RISER-${c.jobId}`,c.customerId,c.revisionId,c.snapshot]);await client.query("COMMIT");created.push(c);return c;}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
function payload(c:Case, mode:unknown, submittedConfig:unknown={riserMode:mode}, id=randomUUID()) { const system=c.snapshot.enabledSystems.find((x:any)=>x.systemKey==="dry_wet_riser"); const rows=(keys:string[])=>Object.fromEntries(keys.map(k=>[k,{result:"good",remarks:""}])); const outlets=system.locations.flatMap((l:any)=>Array.from({length:l.presetRowCount},(_:unknown,i:number)=>({rowUuid:randomUUID(),source:"configured",configuredLocationId:l.id,configuredRowOrdinal:i+1,zoneSnapshot:null,locationSnapshot:{id:l.id,displayName:l.displayName},assetReference:"",locationText:l.displayName,canvasHoseAt2Result:"good",diffuserNozzleResult:"good",landingValveResult:"good",crandleResult:"good",doorResult:"good",remarks:"",sortOrder:0})));outlets.forEach((row:any,index:number)=>row.sortOrder=index+1); return {operationId:randomUUID(),entityType:"masterSystemInspection",entityId:id,action:"create",payload:{clientUuid:id,jobId:c.jobId,systemKey:"dry_wet_riser",instanceKey:"primary",configuredZoneId:null,configuredLocationId:null,displaySequence:1,originalCreatorSnapshot:null,masterTemplate:{id:c.templateId,code:"MFE-FSSR",version:2},configuration:{revisionId:c.revisionId,revisionNumber:1},inspectionSnapshot:{...structuredClone(c.snapshot),system:{...system,systemConfiguration:submittedConfig}},responses:{schemaVersion:1,mode,waterTank:rows(fixedWater),pumpHouse:rows(fixedPump),measurements:{jockeyCutIn:10,jockeyCutOut:11,dutyCutIn:12,standbyCutIn:13,unit:"PSI"},riserOutlets:outlets,comments:"validation"},performedAt:"2026-07-29T00:00:00.000Z"}}; }
async function submit(item:any){return syncDryWetRiserInspections([item],actorUserId);}
async function cleanupValidationData(){await pool.query("DELETE FROM master_system_form_instances WHERE inspection_group_id IN (SELECT inspection.id FROM master_system_inspections inspection INNER JOIN inspection_jobs job ON job.id=inspection.job_id INNER JOIN customers customer ON customer.id=job.customer_id WHERE customer.customer_code LIKE 'VALIDATION-RISER-%')");await pool.query("DELETE FROM master_system_inspections WHERE job_id IN (SELECT job.id FROM inspection_jobs job INNER JOIN customers customer ON customer.id=job.customer_id WHERE customer.customer_code LIKE 'VALIDATION-RISER-%')");await pool.query("DELETE FROM inspection_jobs WHERE customer_id IN (SELECT id FROM customers WHERE customer_code LIKE 'VALIDATION-RISER-%')");await pool.query("DELETE FROM customer_enabled_systems WHERE configuration_revision_id IN (SELECT id FROM customer_configuration_revisions WHERE customer_id IN (SELECT id FROM customers WHERE customer_code LIKE 'VALIDATION-RISER-%'))");await pool.query("DELETE FROM customer_configuration_revisions WHERE customer_id IN (SELECT id FROM customers WHERE customer_code LIKE 'VALIDATION-RISER-%')");await pool.query("DELETE FROM customers WHERE customer_code LIKE 'VALIDATION-RISER-%'");}
async function accepted(mode:Mode){const c=await createCase(mode);const item=payload(c,mode);const r=await submit(item);assert(r.acceptedIds[0]===item.entityId,`${mode} was not accepted: ${JSON.stringify(r)}`);const stored=(await pool.query<any>("SELECT response_payload,inspection_snapshot FROM master_system_form_instances WHERE client_uuid=$1",[item.entityId])).rows[0];assert(stored.response_payload.mode===mode&&stored.inspection_snapshot.system.systemConfiguration.riserMode===mode,`${mode} was not canonical`);return {c,item};}
async function endpoint(path:string, authenticated=true){return fetch(`http://localhost:3000${path}`,authenticated?{headers:{Cookie:`inspection_session=${validationSessionToken}`}}:undefined);}
async function validateServerDetail(acceptedCase:{c:Case;item:any}){const id=acceptedCase.item.entityId;const response=await endpoint(`/dry-wet-riser-inspections/${id}`);assert(response.status===200,`accepted detail status ${response.status}`);const body=await response.json() as any;const detail=body.inspection;assert(detail.clientUuid===id&&detail.jobId===acceptedCase.c.jobId&&detail.jobReference===`VALIDATION-RISER-${acceptedCase.c.jobId}`&&detail.jobTitle==='Disposable Riser Validation'&&detail.customerId===acceptedCase.c.customerId&&detail.customerName==='Disposable Riser Validation'&&detail.systemKey==='dry_wet_riser'&&detail.systemLabel==='Dry / Wet Riser System'&&detail.template.code==='MFE-FSSR'&&detail.template.version===2&&detail.configuration.revisionId===acceptedCase.c.revisionId&&detail.systemConfiguration.riserMode==='dry'&&detail.responses.waterTank&&fixedWater.every((key)=>key in detail.responses.waterTank)&&detail.responses.pumpHouse&&fixedPump.every((key)=>key in detail.responses.pumpHouse)&&detail.responses.measurements.unit==='PSI'&&[detail.responses.measurements.jockeyCutIn,detail.responses.measurements.jockeyCutOut,detail.responses.measurements.dutyCutIn,detail.responses.measurements.standbyCutIn].every(Number.isFinite)&&Array.isArray(detail.responses.riserOutlets)&&detail.responses.riserOutlets.every((row:any,index:number)=>row.sortOrder===index+1)&&detail.responses.comments==='validation'&&typeof detail.syncedByUsername==='string','accepted detail was not canonical');assert((await endpoint(`/dry-wet-riser-inspections/${randomUUID()}`)).status===404,'unknown detail did not return 404');assert((await endpoint(`/dry-wet-riser-inspections/${id}`,false)).status===401,'unauthenticated detail did not return 401');const nonDry=(await pool.query<{clientUuid:string}>(`SELECT instance.client_uuid AS "clientUuid" FROM master_system_form_instances instance INNER JOIN master_system_inspections inspection ON inspection.id=instance.inspection_group_id WHERE inspection.system_key <> 'dry_wet_riser' AND instance.status='submitted' LIMIT 1`)).rows[0]?.clientUuid;if(nonDry)assert((await endpoint(`/dry-wet-riser-inspections/${nonDry}`)).status===404,'non-Dry/Wet detail did not return 404');const original=(await pool.query<{responsePayload:unknown}>('SELECT response_payload AS "responsePayload" FROM master_system_form_instances WHERE client_uuid=$1',[id])).rows[0]?.responsePayload;assert(original,'accepted detail payload is missing');try{await pool.query(`UPDATE master_system_form_instances SET response_payload='{}'::jsonb WHERE client_uuid=$1`,[id]);assert((await endpoint(`/dry-wet-riser-inspections/${id}`)).status===404,'malformed detail did not fail closed');}finally{await pool.query('UPDATE master_system_form_instances SET response_payload=$1 WHERE client_uuid=$2',[original,id]);}result.serverDetail={accepted:true,unknown404:true,unauthenticated401:true,nonDry404:!!nonDry,malformedFailsClosed:true};}
async function main(){try{await cleanupValidationData();actorUserId=(await pool.query<{id:number}>("SELECT id FROM users WHERE is_active=true ORDER BY id LIMIT 1")).rows[0]?.id;assert(actorUserId,"validation actor is unavailable");
  validationSessionToken=(await createSession(actorUserId)).token;const dry=await accepted("dry"),wet=await accepted("wet");result.dryAccepted=true;result.wetAccepted=true;await validateServerDetail(dry);
  const altered=await createCase("dry");assert(failureCode(await submit(payload(altered,"wet",{riserMode:"dry"})))==="VALIDATION_ERROR","altered response mode");
  const alteredSnapshot=await createCase("dry");assert(failureCode(await submit(payload(alteredSnapshot,"dry",{riserMode:"wet"})))==="VALIDATION_ERROR","altered snapshot mode");
  const missingDb=await createCase("dry",{});assert(failureCode(await submit(payload(missingDb,"dry")))==="CONFIGURATION_ERROR","missing db mode");
  const missingFrozen=await createCase("dry",{riserMode:"dry"},{});assert(failureCode(await submit(payload(missingFrozen,"dry")))==="CONFIGURATION_ERROR","missing frozen mode");
  const invalid=await createCase("dry");assert(failureCode(await submit(payload(invalid,"other",{riserMode:"other"})))==="CONFIGURATION_ERROR","invalid mode");
  const extra=await createCase("dry");assert(failureCode(await submit(payload(extra,"dry",{riserMode:"dry",extra:true})))==="CONFIGURATION_ERROR","extra configuration key");result.modeRejections=true;
  const replay=await accepted("dry");const duplicate=await submit(replay.item);assert(duplicate.duplicateIds[0]===replay.item.entityId,"duplicate replay");const changed=structuredClone(replay.item);changed.payload.responses.comments="changed";assert(failureCode(await submit(changed))==="IDEMPOTENCY_CONFLICT","changed replay");const changedMode=structuredClone(replay.item);changedMode.payload.responses.mode="wet";assert(failureCode(await submit(changedMode))==="VALIDATION_ERROR","changed mode replay");const count=(await pool.query<any>("SELECT count(*)::int AS count FROM master_system_inspections WHERE job_id=$1",[replay.c.jobId])).rows[0].count;assert(count===1,"duplicate added parent");result.idempotency=true;
  const competing=await accepted("wet");assert(failureCode(await submit(payload(competing.c,"wet")))==="ACTIVE_INSPECTION_EXISTS","competing UUID");result.competingUuid=true;
  const concurrent=await createCase("dry");const both=await Promise.all([submit(payload(concurrent,"dry")),submit(payload(concurrent,"dry"))]);const codes=both.map(x=>x.acceptedIds.length?"ACCEPTED":failureCode(x));assert(codes.filter(x=>x==="ACCEPTED").length===1&&codes.filter(x=>x==="ACTIVE_INSPECTION_EXISTS").length===1,`concurrent outcomes ${codes}`);result.concurrent=codes;
  const fixture=await pool.connect();try{await fixture.query("BEGIN");await fixture.query("UPDATE customer_enabled_systems SET system_configuration='{}'::jsonb WHERE id='00000000-0000-4000-8000-000000000812'");let failed=false;try{await assertDryWetRiserFixture(fixture,structuredClone((await fixture.query<any>("SELECT configuration_snapshot FROM inspection_jobs WHERE id='00000000-0000-4000-8000-000000000819'")).rows[0].configuration_snapshot));}catch{failed=true;}assert(failed,"fixture conflict was silently accepted");result.fixtureConflictFailsClosed=true;}finally{await fixture.query("ROLLBACK");fixture.release();}
  result.v1Compatible=(await pool.query("SELECT 1 FROM customer_enabled_systems WHERE system_key='hose_reel' AND system_configuration='{}'::jsonb LIMIT 1")).rowCount===1;assert(result.v1Compatible,"V1 unrelated configuration");console.log(JSON.stringify({status:"PASS",...result}));
}finally{if(validationSessionToken)await pool.query('DELETE FROM user_sessions WHERE token_hash=$1',[hashSessionToken(validationSessionToken)]);await cleanupValidationData();await pool.end();}}
main().catch(error=>{console.error(error);process.exitCode=1;});
