import assert from "node:assert/strict";
import test from "node:test";
import { masterServiceReportV1 } from "../../api/src/inspections/templates/masterServiceReportV1";
import { masterServiceReportV7 } from "../../api/src/inspections/templates/masterServiceReportV7";
import { resolveV7EvidenceContract, v7EvidenceContractSha256 } from "../../api/src/inspections/evidence/v7EvidenceContracts";
import { resolvePublishedAutomaticSprinklerControls } from "../src/automaticSprinkler/automaticSprinklerDefinition";
import { getAutomaticSprinklerSubmitIssues } from "../src/automaticSprinkler/automaticSprinklerRepository";
import type { AutomaticSprinklerInspectionRecord, AutomaticSprinklerInspectionSnapshot, AutomaticSprinklerResponses, AutomaticSprinklerV7ChecklistKey } from "../src/automaticSprinkler/automaticSprinklerTypes";
import { v7AutomaticSprinklerSubmissionIssues, v7RequiredAutomaticSprinklerFieldPaths } from "../src/automaticSprinkler/automaticSprinklerV7Evidence";

const uuid = "00000000-0000-4000-8000-000000000099";
const hash = (value: string) => value.repeat(64);
const v7Definition = masterServiceReportV7.systems.find((system) => system.key === "automatic_sprinkler")!;
const historicalDefinition = masterServiceReportV1.systems.find((system) => system.key === "automatic_sprinkler")!;
function snapshot(definition: unknown, version: number): AutomaticSprinklerInspectionSnapshot { const controls = resolvePublishedAutomaticSprinklerControls(definition, "MFE-FSSR", version); return { template: { code: "MFE-FSSR", version }, system: { definition, resolvedControls: controls } } as AutomaticSprinklerInspectionSnapshot; }
function record(version = 7): AutomaticSprinklerInspectionRecord { return { clientUuid: uuid, masterTemplate: { id: `00000000-0000-4000-8000-00000000080${version}`, code: "MFE-FSSR", version }, inspectionSnapshot: snapshot(version === 7 ? v7Definition : historicalDefinition, version) } as AutomaticSprinklerInspectionRecord; }
function completeResponses(version = 7): AutomaticSprinklerResponses {
  const controls = resolvePublishedAutomaticSprinklerControls(version === 7 ? v7Definition : historicalDefinition, "MFE-FSSR", version);
  const measurements = { jockey_pump_pressure: { values: { cut_in: 1, cut_out: 2 }, unit: "PSI", result: "good" as const, remarks: "" }, duty_pump_cut_in: { values: { value: 1 }, unit: "PSI", result: "good" as const, remarks: "" }, standby_pump_cut_in: { values: { value: 1 }, unit: "PSI", result: "good" as const, remarks: "" }, water_supply_gauge: { values: { value: 1 }, unit: "PSI", result: "good" as const, remarks: "" }, installation_gauge: { values: { value: 1 }, unit: "PSI", result: "good" as const, remarks: "" } };
  if (version === 7) return { schemaVersion: 2, checklist: Object.fromEntries([...controls.checklist.waterTank, ...controls.checklist.pumpHouse, ...controls.checklist.mainAlarmValve, ...controls.checklist.testRunFirePump].map((item) => [item.key, { result: "good", remarks: "" }])) as Record<AutomaticSprinklerV7ChecklistKey, { result: "good"; remarks: string }>, measurements, comments: "" };
  return { schemaVersion: 1, waterTank: Object.fromEntries(controls.checklist.waterTank.map((item) => [item.key, { result: "good", remarks: "" }])), pumpHouse: Object.fromEntries(controls.checklist.pumpHouse.map((item) => [item.key, { result: "good", remarks: "" }])), mainAlarmValve: Object.fromEntries(controls.checklist.mainAlarmValve.map((item) => [item.key, { result: "good", remarks: "" }])), measurements, comments: "" } as AutomaticSprinklerResponses;
}
function attachment(fieldPath: string, sha256: string) { return { photoUuid: crypto.randomUUID(), inspectionClientUuid: uuid, systemKey: "automatic_sprinkler", fieldPath, sha256, protocolVersion: 7 } as Parameters<typeof v7AutomaticSprinklerSubmissionIssues>[2][number]; }

test("a clean Automatic Sprinkler V7 draft passes the submit gate", () => assert.deepEqual([...getAutomaticSprinklerSubmitIssues(completeResponses(), record().inspectionSnapshot), ...v7AutomaticSprinklerSubmissionIssues(record(), completeResponses(), [])], []));
test("V7 renders all four results and the three paper-order Test Run rows", () => { const controls = resolvePublishedAutomaticSprinklerControls(v7Definition, "MFE-FSSR", 7); assert.deepEqual(controls.checklist.testRunFirePump.map((item) => item.key), ["trfp_jockey_pump", "trfp_duty_pump", "trfp_standby_pump"]); assert.deepEqual(controls.measurements[0]!.result.options.map((item) => item.value), ["good", "not_good", "complete_repair", "na"]); });
test("checklist, measurement, and Test Run findings each require their own remark and photo", () => { const draft = completeResponses() as Extract<AutomaticSprinklerResponses, { schemaVersion: 2 }>; draft.checklist.saj_main_water_supply = { result: "not_good", remarks: "" }; draft.measurements.jockey_pump_pressure.result = "complete_repair"; draft.checklist.trfp_jockey_pump = { result: "not_good", remarks: "" }; const issues = v7AutomaticSprinklerSubmissionIssues(record(), draft, []); for (const path of ["automatic_sprinkler_checks.saj_main_water_supply", "automatic_sprinkler_measurements.jockey_pump_pressure", "automatic_sprinkler_checks.trfp_jockey_pump"]) assert.ok(issues.some((issue) => issue.includes(path) && issue.includes("Photo"))); assert.ok(issues.filter((issue) => issue.includes("Remark")).length >= 3); });
test("one photo cannot satisfy two current findings", () => { const draft = completeResponses() as Extract<AutomaticSprinklerResponses, { schemaVersion: 2 }>; draft.checklist.saj_main_water_supply = { result: "not_good", remarks: "supply" }; draft.measurements.jockey_pump_pressure.result = "complete_repair"; draft.measurements.jockey_pump_pressure.remarks = "pump"; const issues = v7AutomaticSprinklerSubmissionIssues(record(), draft, [attachment("automatic_sprinkler_checks.saj_main_water_supply", hash("a")), attachment("automatic_sprinkler_measurements.jockey_pump_pressure", hash("a"))]); assert.ok(issues.some((issue) => issue.includes("same photo"))); });
test("stale evidence is excluded after the finding is corrected", () => { const draft = completeResponses(); assert.deepEqual(v7AutomaticSprinklerSubmissionIssues(record(), draft, [attachment("automatic_sprinkler_checks.saj_main_water_supply", hash("a"))]), []); assert.deepEqual(v7RequiredAutomaticSprinklerFieldPaths(draft), []); });
test("web V7 paths equal the server adapter canonical paths", () => { const adapter = resolveV7EvidenceContract({ systemKey: "automatic_sprinkler", templateId: masterServiceReportV7.id, templateVersion: 7, definition: v7Definition, contractSha256: v7EvidenceContractSha256(v7Definition) }); assert.ok(adapter); const draft = completeResponses() as Extract<AutomaticSprinklerResponses, { schemaVersion: 2 }>; draft.checklist.saj_main_water_supply = { result: "not_good", remarks: "supply" }; draft.measurements.jockey_pump_pressure.result = "complete_repair"; draft.measurements.jockey_pump_pressure.remarks = "pump"; draft.checklist.trfp_jockey_pump = { result: "not_good", remarks: "run" }; const paths = v7RequiredAutomaticSprinklerFieldPaths(draft); assert.deepEqual(paths, ["automatic_sprinkler_checks.saj_main_water_supply", "automatic_sprinkler_checks.trfp_jockey_pump", "automatic_sprinkler_measurements.jockey_pump_pressure"]); for (const path of paths) assert.ok(adapter.isCanonicalFieldPath(path)); });
test("V1-V6 Automatic Sprinkler records retain Good/Poor and legacy PSI photos are unaffected", () => { for (const version of [1, 2, 3, 4, 5, 6]) { const controls = resolvePublishedAutomaticSprinklerControls(historicalDefinition, "MFE-FSSR", version); assert.deepEqual(controls.checklist.waterTank[0]!.result.options.map((item) => item.value), ["good", "poor"]); assert.deepEqual(getAutomaticSprinklerSubmitIssues(completeResponses(version), record(version).inspectionSnapshot), []); assert.deepEqual(v7AutomaticSprinklerSubmissionIssues(record(version), completeResponses(version), [attachment("measurements.jockey_pump_pressure.cut_in", hash("legacy"))]), []); } });
