import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";

type Fixture = { clientUuid: string; jobReference: string; username: string; password: string; foreignUsername: string; foreignPassword: string; photoA: string; photoB: string };
const baseUrl = process.env.CO2_V7_LIVE_BROWSER_BASE_URL ?? "http://127.0.0.1:4176";
const fixturePath = process.env.CO2_V7_LIVE_BROWSER_FIXTURE_PATH;
async function fixture() { if (!fixturePath) throw new Error("CO2_V7_LIVE_BROWSER_FIXTURE_PATH is required"); return JSON.parse(await readFile(fixturePath, "utf8")) as Fixture; }
async function signIn(page: import("@playwright/test").Page, username: string, password: string) { await page.goto(`${baseUrl}/`); await page.getByRole("button", { name: "Technician" }).click(); await page.getByLabel("Username").fill(username); await page.getByLabel("Password").fill(password); await page.getByRole("button", { name: "Sign in" }).click(); await expect(page.getByRole("heading", { name: "My Service Jobs" })).toBeVisible(); }
async function openAcceptedDetail(page: import("@playwright/test").Page, live: Fixture) { await page.goto(`${baseUrl}/#/co2-form/${live.clientUuid}`); await expect(page.getByRole("heading", { name: "CO2 Fire Extinguisher System" })).toBeVisible(); }
async function openPhoto(page: import("@playwright/test").Page, photoUuid: string) { const link = page.locator(`a[href="/api/v7-evidence/accepted/${photoUuid}/content"]`); await expect(link).toBeVisible(); const responsePromise = page.context().waitForEvent("response", (response) => response.url().endsWith(`/api/v7-evidence/accepted/${photoUuid}/content`)); const popupPromise = page.context().waitForEvent("page"); await link.click(); const [response, popup] = await Promise.all([responsePromise, popupPromise]); await popup.waitForLoadState("domcontentloaded"); return { response, popup, bytes: await response.body() }; }

test("CO2 V7 accepted detail renders from the real accepted authority and opens actor-scoped photos", async ({ page, browser }) => {
  const live = await fixture(); await signIn(page, live.username, live.password); await openAcceptedDetail(page, live);
  await expect(page.getByText("Runtime CO2 Browser Poor A")).toBeVisible(); await expect(page.getByText("Runtime CO2 Browser Poor B")).toBeVisible(); await expect(page.locator("p").filter({ hasText: "Main Supply:" })).toContainText("Poor"); await expect(page.locator("p").filter({ hasText: "CO2 Cylinder:" })).toContainText("Poor"); await expect(page.locator("p").filter({ hasText: "Battery:" })).toContainText("Good"); await expect(page.locator("p").filter({ hasText: "Charger:" })).toContainText("Not Relevant"); await expect(page.locator("article p").filter({ hasText: "Heat Detector:" }).first()).toContainText("Normal"); await expect(page.locator("article p").filter({ hasText: "Smoke Detector:" }).first()).toContainText("Test"); await expect(page.locator("article p").filter({ hasText: "Heat Detector:" }).nth(1)).toContainText("Isolation");
  const photoA = await openPhoto(page, live.photoA); expect(photoA.response.status()).toBe(200); expect(photoA.response.headers()["content-type"]).toContain("image/jpeg"); expect(photoA.popup.url()).toContain(`/api/v7-evidence/accepted/${live.photoA}/content`);
  const photoB = await openPhoto(page, live.photoB); expect(photoB.response.status()).toBe(200); expect(photoB.response.headers()["content-type"]).toContain("image/jpeg"); expect(photoB.popup.url()).toContain(`/api/v7-evidence/accepted/${live.photoB}/content`); expect(Buffer.compare(photoA.bytes, photoB.bytes)).not.toBe(0);
  await page.reload(); await page.getByRole("button", { name: "Technician" }).click(); await expect(page.getByText("Runtime CO2 Browser Poor A")).toBeVisible(); await expect(page.getByText("Runtime CO2 Browser Poor B")).toBeVisible(); expect((await openPhoto(page, live.photoA)).response.status()).toBe(200); expect((await openPhoto(page, live.photoB)).response.status()).toBe(200);
  const unauthenticated = await browser.newContext(); const unauthenticatedPage = await unauthenticated.newPage(); expect((await unauthenticatedPage.goto(`${baseUrl}/api/v7-evidence/accepted/${live.photoA}/content`))?.status()).toBe(401); await unauthenticated.close();
  const foreign = await browser.newContext(); const foreignPage = await foreign.newPage(); await signIn(foreignPage, live.foreignUsername, live.foreignPassword); expect((await foreignPage.goto(`${baseUrl}/api/v7-evidence/accepted/${live.photoA}/content`))?.status()).toBe(404); await foreign.close();
});
