import { expect, test } from "@playwright/test";

test("PFE login, Save Draft, Submit, Edit Failed and sync use the authenticated workspace", async ({ page }) => {
  await page.goto("/tests/portable-user-workspace.html");
  await page.getByRole("button", { name: /Technician/ }).click();
  await page.getByLabel("Username", { exact: true }).fill("pfe-tech");
  await page.getByLabel("Password", { exact: true }).fill("test-only");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await page.locator(".job-card").click();
  await page.getByRole("button", { name: /Portable Fire Extinguisher/ }).click();
  const state = () => page.evaluate(() => (window as any).inspectWorkspace());
  await page.getByLabel("Total Fire Extinguisher", { exact: true }).fill("3");
  await page.getByRole("button", { name: "Save Draft", exact: true }).click();
  await expect.poll(async () => (await state()).records[0]?.responses.total).toBe(3);
  const saved = await state();
  expect(saved.name).toBe("inspection-pwa:user:903");
  expect(saved.records[0].syncStatus).toBe("Draft");
  expect(saved.outbox).toHaveLength(0);
  await page.getByRole("button", { name: "Submit Inspection", exact: true }).click();
  await expect.poll(async () => (await state()).records[0]?.syncStatus).toBe("Pending");
  expect((await state()).outbox).toHaveLength(1);
  await page.getByRole("button", { name: "Back to Systems", exact: true }).click();
  await page.getByRole("button", { name: "Back to My Jobs", exact: true }).click();
  await page.getByRole("button", { name: "Sync Now", exact: true }).click();
  await expect.poll(async () => (await state()).records[0]?.syncStatus).toBe("Failed");
  await page.locator(".job-card").click();
  await page.getByRole("button", { name: /Portable Fire Extinguisher/ }).click();
  await page.getByRole("button", { name: "Edit Failed Inspection", exact: true }).click();
  await expect.poll(async () => (await state()).records[0]?.syncStatus).toBe("Draft");
  await page.getByLabel("Total Fire Extinguisher", { exact: true }).fill("4");
  await page.getByRole("button", { name: "Submit Inspection", exact: true }).click();
  await expect.poll(async () => (await state()).records[0]?.syncStatus).toBe("Pending");
  await page.getByRole("button", { name: "Back to Systems", exact: true }).click();
  await page.getByRole("button", { name: "Back to My Jobs", exact: true }).click();
  await page.getByRole("button", { name: "Sync Now", exact: true }).click();
  await expect.poll(async () => (await state()).records[0]?.syncStatus).toBe("Synced");
  const synced = await state();
  expect(synced.records[0].clientUuid).toBe(saved.records[0].clientUuid);
  expect(synced.records[0].responses.total).toBe(4);
  expect(synced.outbox.every((item: any) => item.status === "Completed")).toBe(true);
  expect(synced.syncCount).toBe(2);
  expect(synced.legacyRecords).toBe(0);
  expect(synced.legacyOutbox).toBe(0);
});
