import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";

type Fixture = { clientUuid: string; jobReference: string; username: string; password: string; foreignUsername: string; foreignPassword: string; photoA: string; photoB: string };
const baseUrl = process.env.WET_CHEMICAL_V7_LIVE_BROWSER_BASE_URL ?? "http://127.0.0.1:4176";
const fixturePath = process.env.WET_CHEMICAL_V7_LIVE_BROWSER_FIXTURE_PATH;
async function fixture() { if (!fixturePath) throw new Error("WET_CHEMICAL_V7_LIVE_BROWSER_FIXTURE_PATH is required"); return JSON.parse(await readFile(fixturePath, "utf8")) as Fixture; }
async function signIn(page: import("@playwright/test").Page, username: string, password: string) { await page.goto(`${baseUrl}/`); await page.getByRole("button", { name: "Technician" }).click(); await page.getByLabel("Username").fill(username); await page.getByLabel("Password").fill(password); await page.getByRole("button", { name: "Sign in" }).click(); await expect(page.getByRole("heading", { name: "My Service Jobs" })).toBeVisible(); await page.waitForTimeout(1_000); }
async function openAcceptedDetail(page: import("@playwright/test").Page, live: Fixture) { await page.goto(`${baseUrl}/#/wet-chemical-form/${live.clientUuid}`); await expect(page.getByRole("heading", { name: "Wet Chemical System" })).toBeVisible(); }
async function openPhoto(page: import("@playwright/test").Page, photoUuid: string) { const href = `/api/v7-evidence/accepted/${photoUuid}/content`; await expect(page.locator(`a[href="${href}"]`)).toBeVisible(); const photoPage = await page.context().newPage(); const response = await photoPage.goto(`${baseUrl}${href}`); if (!response) throw new Error("Accepted photo did not respond"); return { response, photoPage, bytes: await response.body() }; }

test("Wet Chemical V7 accepted detail renders from the real accepted authority and opens actor-scoped photos", async ({ page, browser }) => {
  const live = await fixture(); await signIn(page, live.username, live.password); await openAcceptedDetail(page, live);
  await expect(page.getByText("Runtime Wet Chemical Poor A")).toBeVisible(); await expect(page.getByText("Runtime Wet Chemical Poor B")).toBeVisible(); await expect(page.locator("p").filter({ hasText: "Main Supply:" })).toHaveText("Main Supply: Not Good — Runtime Wet Chemical Poor A"); await expect(page.locator("p").filter({ hasText: "Wet Chemical Cylinder:" })).toHaveText("Wet Chemical Cylinder: Not Good — Runtime Wet Chemical Poor B"); await expect(page.locator("p").filter({ hasText: "Battery:" })).toHaveText("Battery: Good"); await expect(page.locator("p").filter({ hasText: "Charger:" })).toHaveText("Charger: No Need Checking / N.A.");
  // Row-scoped and ^-anchored: a bare hasText "Heat Detector:" also matches "Second Heat Detector:".
  const detectorRow = (sequence: number) => page.locator("article.hose-row-card").filter({ has: page.getByText(`Row ${sequence}`, { exact: true }) }); await expect(page.locator("article.hose-row-card")).toHaveCount(2); await expect(detectorRow(1).locator("p").filter({ hasText: /^Heat Detector:/ })).toHaveText("Heat Detector: Normal, Test"); await expect(detectorRow(1).locator("p").filter({ hasText: /^Second Heat Detector:/ })).toHaveText("Second Heat Detector: Test"); await expect(detectorRow(2).locator("p").filter({ hasText: /^Heat Detector:/ })).toHaveText("Heat Detector: Isolation"); await expect(detectorRow(2).locator("p").filter({ hasText: /^Second Heat Detector:/ })).toHaveText("Second Heat Detector: Normal");
  const acceptedEvidence = await page.evaluate(async (clientUuid) => (await fetch(`/api/v7-evidence/accepted?inspectionClientUuid=${encodeURIComponent(clientUuid)}`)).json(), live.clientUuid); expect(acceptedEvidence).toMatchObject({ evidence: [{ photoUuid: live.photoA }, { photoUuid: live.photoB }] }); const photoA = await openPhoto(page, live.photoA); expect(photoA.response.status()).toBe(200); expect(photoA.response.headers()["content-type"]).toContain("image/jpeg"); expect(photoA.photoPage.url()).toContain(`/api/v7-evidence/accepted/${live.photoA}/content`);
  const photoB = await openPhoto(page, live.photoB); expect(photoB.response.status()).toBe(200); expect(photoB.response.headers()["content-type"]).toContain("image/jpeg"); expect(photoB.photoPage.url()).toContain(`/api/v7-evidence/accepted/${live.photoB}/content`); expect(Buffer.compare(photoA.bytes, photoB.bytes)).not.toBe(0); await photoA.photoPage.close(); await photoB.photoPage.close();
  await page.reload(); await page.getByRole("button", { name: "Technician" }).click(); await expect(page.getByText("Runtime Wet Chemical Poor A")).toBeVisible(); await expect(page.getByText("Runtime Wet Chemical Poor B")).toBeVisible(); expect((await openPhoto(page, live.photoA)).response.status()).toBe(200); expect((await openPhoto(page, live.photoB)).response.status()).toBe(200);
  const unauthenticated = await browser.newContext(); const unauthenticatedPage = await unauthenticated.newPage(); expect((await unauthenticatedPage.goto(`${baseUrl}/api/v7-evidence/accepted/${live.photoA}/content`))?.status()).toBe(401); await unauthenticated.close();
  const foreign = await browser.newContext(); const foreignPage = await foreign.newPage(); await signIn(foreignPage, live.foreignUsername, live.foreignPassword); expect((await foreignPage.goto(`${baseUrl}/api/v7-evidence/accepted/${live.photoA}/content`))?.status()).toBe(404); await foreign.close();
});
