import type { Co2Responses } from "../co2/co2Types";

type R = Record<string, unknown>;
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
// The shared suppression (CO2 / Wet Chemical) accepted-detail shape built by the API acceptedDetailResponse; identical for V4 and V7.
const detailKeys = ["clientUuid","serverFormInstanceId","jobId","jobReference","jobTitle","customerName","systemKey","systemLabel","instanceKey","zoneId","locationId","displaySequence","status","performedAt","receivedAt","template","configuration","responses","displayControls","deviceReportedCreatorUsername","verifiedOriginalCreatorUsername","syncedByUsername"];
const responseKeys = ["controlPanelLocation","detectorRows","chargerAndBatteries","physicalOutlook","mainFunctionKeys","comments"];
const rowKeys = ["rowUuid","displaySequence","alarmZone","location","heatDetectorStatus","smokeDetectorStatus","remarks"];
const rec=(v:unknown):v is R=>typeof v==="object"&&v!==null&&!Array.isArray(v);
const exact=(v:R,k:readonly string[])=>Object.keys(v).length===k.length&&k.every(x=>Object.hasOwn(v,x));
const text=(v:unknown,max:number,required=true):v is string=>typeof v==="string"&&v.length<=max&&(!required||v.trim().length>0);
function canonicalTimestamp(v:unknown):v is string { if(typeof v!=="string"||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{6}Z$/.test(v))return false;const [year,month,day,hour,minute,second]=v.slice(0,19).split(/[-T:]/).map(Number);const d=new Date(0);d.setUTCFullYear(year,month-1,day);d.setUTCHours(hour,minute,second,0);return d.getUTCFullYear()===year&&d.getUTCMonth()===month-1&&d.getUTCDate()===day&&d.getUTCHours()===hour&&d.getUTCMinutes()===minute&&d.getUTCSeconds()===second; }
// Wet Chemical starts at V4; V5/V6 carry the V4 definition, so the server freezes source.templateVersion 4 for any non-V7 template.
// V4 is good/poor; V7 uses the four-state model (migration 020), matching the server displayControls.
const v7Results=["good","not_good","complete_repair","na"] as const;
function result(v:unknown,v7=false){return v7?(v7Results as readonly unknown[]).includes(v):v==="good"||v==="poor";}
function resultControl(value:unknown, values:readonly string[], required:boolean, type:"single_select"|"multi_select"="single_select") { return rec(value)&&exact(value,["type","required","options"])&&value.type===type&&value.required===required&&Array.isArray(value.options)&&value.options.length===values.length&&value.options.every((option,index)=>rec(option)&&exact(option,["value","label"])&&option.value===values[index]&&typeof option.label==="string"&&option.label.trim().length>0&&option.label.length<=100); }
function remarksDefinition(value:unknown,maxLength:number) { return rec(value)&&exact(value,["policy","maxLength"])&&value.policy==="optional"&&value.maxLength===maxLength; }
function checklistControls(value:unknown, expectedKeys:readonly string[], v7=false) { const values=v7?v7Results:["good","poor"]; return Array.isArray(value)&&value.length===expectedKeys.length&&value.every((item,index)=>rec(item)&&exact(item,["key","label","sortOrder","result","remarks"])&&item.key===expectedKeys[index]&&text(item.label,300)&&item.sortOrder===index+1&&resultControl(item.result,values,true)&&remarksDefinition(item.remarks,2000)); }
function detectorControl(value:unknown,key:string,order:number,multi=false) { return rec(value)&&exact(value,["key","label","sortOrder","result"])&&value.key===key&&text(value.label,300)&&value.sortOrder===order&&resultControl(value.result,["normal","test","isolation"],false,multi?"multi_select":"single_select"); }
function displayControls(value:unknown) { return rec(value)&&exact(value,["schemaVersion","source","repetitionMode","controlPanelLocation","detectorRows","chargerAndBatteries","physicalOutlook","mainFunctionKeys","comments"])
  &&value.schemaVersion===1&&rec(value.source)&&exact(value.source,["templateCode","templateVersion","systemKey"])&&value.source.templateCode==="MFE-FSSR"&&(value.source.templateVersion===4||value.source.templateVersion===7)&&value.source.systemKey==="wet_chemical"&&value.repetitionMode==="per_location"
  &&rec(value.controlPanelLocation)&&exact(value.controlPanelLocation,["key","label","required","maxLength"])&&value.controlPanelLocation.key==="control_panel_location"&&text(value.controlPanelLocation.label,300)&&value.controlPanelLocation.required===true&&value.controlPanelLocation.maxLength===300
  &&rec(value.detectorRows)&&exact(value.detectorRows,["minimum","maximum","alarmZone","location","heatDetector","smokeDetector","remarks"])&&value.detectorRows.minimum===1&&value.detectorRows.maximum===250
  &&rec(value.detectorRows.alarmZone)&&exact(value.detectorRows.alarmZone,["key","label","required","maxLength"])&&value.detectorRows.alarmZone.key==="alarm_zone"&&text(value.detectorRows.alarmZone.label,300)&&value.detectorRows.alarmZone.required===true&&value.detectorRows.alarmZone.maxLength===200
  &&rec(value.detectorRows.location)&&exact(value.detectorRows.location,["key","label","required","maxLength"])&&value.detectorRows.location.key==="location"&&text(value.detectorRows.location.label,300)&&value.detectorRows.location.required===true&&value.detectorRows.location.maxLength===300
  &&detectorControl(value.detectorRows.heatDetector,"heat_detector",3,value.source.templateVersion===7)&&detectorControl(value.detectorRows.smokeDetector,"unconfirmed_second_heat_detector",4,value.source.templateVersion===7)&&remarksDefinition(value.detectorRows.remarks,2000)
  &&checklistControls(value.chargerAndBatteries,["main_supply","battery","charger"],value.source.templateVersion===7)
  &&checklistControls(value.physicalOutlook,["wet_chemical_cylinder","electric_actuator","manual_release_key","alarm_bell","twin_flashing_light","manual_pull_station","high_pressure_hose","discharge_nozzle"],value.source.templateVersion===7)
  &&checklistControls(value.mainFunctionKeys,["main_alarm_reset","lamp_test","evacuate","ac_supply","dc_supply","signal_alarm_to_mfap"],value.source.templateVersion===7)
  &&remarksDefinition(value.comments,4000); }
function checklist(value:unknown, keys:string[], v7=false) { if(!rec(value)||!exact(value,keys))return; const out:R={}; for(const key of keys){const item=value[key];if(!rec(item)||!exact(item,["result","remarks"])||!result(item.result,v7)||!text(item.remarks,2000,false))return;out[key]={result:item.result,remarks:item.remarks};} return out; }
function canonicalDetectorStates(value:unknown) { return Array.isArray(value)&&value.length>0&&value.length<=3&&value.every((item,index)=>typeof item==="string"&&["normal","test","isolation"].includes(item)&&(index===0||["normal","test","isolation"].indexOf(value[index-1] as string)<["normal","test","isolation"].indexOf(item))); }
function responses(value:unknown, v7=false):Co2Responses|undefined {
  if(!rec(value)||!exact(value,responseKeys)||!text(value.controlPanelLocation,300)||!Array.isArray(value.detectorRows)||value.detectorRows.length<1||value.detectorRows.length>250||!text(value.comments,4000,false))return;
  const seen=new Set<string>(); const rows=[] as Co2Responses["detectorRows"];
  for(let i=0;i<value.detectorRows.length;i++){const row=value.detectorRows[i];const detector=v7?canonicalDetectorStates:((item:unknown)=>item===null||["normal","test","isolation"].includes(String(item)));if(!rec(row)||!exact(row,rowKeys)||typeof row.rowUuid!=="string"||!uuid.test(row.rowUuid)||seen.has(row.rowUuid)||row.displaySequence!==i+1||!text(row.alarmZone,200,true)||!text(row.location,300,true)||!text(row.remarks,2000,false)||!detector(row.heatDetectorStatus)||!detector(row.smokeDetectorStatus)|| (!v7&&row.heatDetectorStatus===null&&row.smokeDetectorStatus===null))return;seen.add(row.rowUuid);rows.push(row as Co2Responses["detectorRows"][number]);}
  const charger=checklist(value.chargerAndBatteries,["main_supply","battery","charger"],v7);
  const physical=checklist(value.physicalOutlook,["wet_chemical_cylinder","electric_actuator","manual_release_key","alarm_bell","twin_flashing_light","manual_pull_station","high_pressure_hose","discharge_nozzle"],v7);
  const functions=checklist(value.mainFunctionKeys,["main_alarm_reset","lamp_test","evacuate","ac_supply","dc_supply","signal_alarm_to_mfap"],v7);
  if(!charger||!physical||!functions)return;
  return {controlPanelLocation:value.controlPanelLocation,detectorRows:rows,chargerAndBatteries:charger as Co2Responses["chargerAndBatteries"],physicalOutlook:physical as Co2Responses["physicalOutlook"],mainFunctionKeys:functions as Co2Responses["mainFunctionKeys"],comments:value.comments};
}
export type ServerWetChemicalDetail={clientUuid:string;serverFormInstanceId:string;jobId:string;jobReference:string;jobTitle:string;customerName:string;systemKey:"wet_chemical";systemLabel:"Wet Chemical System";instanceKey:string;status:"submitted";performedAt:string;receivedAt:string;responses:Co2Responses;deviceReportedCreatorUsername:string|null;verifiedOriginalCreatorUsername:string|null;syncedByUsername:string};
export function parseServerWetChemicalDetail(value:unknown,requestedClientUuid:string,expectedJobId?:string):ServerWetChemicalDetail|undefined {
 if(!rec(value)||!exact(value,detailKeys)||value.clientUuid!==requestedClientUuid||typeof value.clientUuid!=="string"||!uuid.test(value.clientUuid)||typeof value.serverFormInstanceId!=="string"||!uuid.test(value.serverFormInstanceId)||typeof value.jobId!=="string"||!uuid.test(value.jobId)||(expectedJobId!==undefined&&value.jobId!==expectedJobId)||!text(value.jobReference,250)||!text(value.jobTitle,300)||!text(value.customerName,250)||value.systemKey!=="wet_chemical"||value.systemLabel!=="Wet Chemical System"||typeof value.locationId!=="string"||!uuid.test(value.locationId)||value.instanceKey!==`location:${value.locationId}`||!(value.zoneId===null||typeof value.zoneId==="string"&&uuid.test(value.zoneId))||!Number.isSafeInteger(value.displaySequence)||Number(value.displaySequence)<1||value.status!=="submitted"||!canonicalTimestamp(value.performedAt)||!canonicalTimestamp(value.receivedAt)||!rec(value.template)||!exact(value.template,["id","code","version"])||typeof value.template.id!=="string"||!uuid.test(value.template.id)||value.template.code!=="MFE-FSSR"||!Number.isSafeInteger(value.template.version)||Number(value.template.version)<1||!rec(value.configuration)||!exact(value.configuration,["revisionId","revisionNumber"])||typeof value.configuration.revisionId!=="string"||!uuid.test(value.configuration.revisionId)||!Number.isSafeInteger(value.configuration.revisionNumber)||Number(value.configuration.revisionNumber)<1||!displayControls(value.displayControls)||Number(value.template.version)<4||((value.displayControls as R).source as R).templateVersion!==(value.template.version===7?7:4)||!(value.deviceReportedCreatorUsername===null||text(value.deviceReportedCreatorUsername,160))||!(value.verifiedOriginalCreatorUsername===null||text(value.verifiedOriginalCreatorUsername,160))||!text(value.syncedByUsername,160))return;
 const parsed=responses(value.responses,rec(value.displayControls)&&rec(value.displayControls.source)&&value.displayControls.source.templateVersion===7);if(!parsed)return;return {clientUuid:value.clientUuid,serverFormInstanceId:value.serverFormInstanceId,jobId:value.jobId,jobReference:value.jobReference,jobTitle:value.jobTitle,customerName:value.customerName,systemKey:"wet_chemical",systemLabel:"Wet Chemical System",instanceKey:value.instanceKey,status:"submitted",performedAt:value.performedAt,receivedAt:value.receivedAt,responses:parsed,deviceReportedCreatorUsername:value.deviceReportedCreatorUsername as string|null,verifiedOriginalCreatorUsername:value.verifiedOriginalCreatorUsername as string|null,syncedByUsername:value.syncedByUsername};
}
export async function loadServerWetChemicalDetail(clientUuid:string,expectedJobId?:string){if(!uuid.test(clientUuid))throw new Error("Wet Chemical inspection identifier is invalid");const r=await fetch(`/api/wet-chemical-inspections/${encodeURIComponent(clientUuid)}`,{credentials:"same-origin",cache:"no-store"});if(!r.ok)throw new Error(r.status===404?"Accepted Wet Chemical inspection was not found":"Server Wet Chemical detail is unavailable");const body:unknown=await r.json();if(!rec(body)||!exact(body,["inspection"]))throw new Error("Server returned invalid Wet Chemical accepted detail");const detail=parseServerWetChemicalDetail(body.inspection,clientUuid,expectedJobId);if(!detail)throw new Error("Server returned invalid Wet Chemical accepted detail");return detail;}
