import { localDatabase, type SyncOutboxItem } from "../db/localDatabase";
import type { InspectionCatalog } from "../referenceData/referenceDataTypes";
import { compatibleCatalogSystem } from "../referenceData/systemContractCompatibility";
import type { InspectionJob, JobSystemSnapshot } from "../jobs/jobTypes";
import type { DeviceReportedCreator } from "../hoseReel/hoseReelTypes";
import type { InspectionAttachmentRecord } from "../attachments/attachmentTypes";
import { resolvePublishedDryWetRiserControls } from "./dryWetRiserDefinition";
import { listDryWetRiserV7Photos, v7DryWetRiserEvidenceOutbox, v7DryWetRiserManifest, v7DryWetRiserSubmissionIssues, isDryWetRiserV7EvidenceFinding } from "./dryWetRiserV7Evidence";
import type { DryWetRiserInspectionRecord, DryWetRiserResponses, DryWetRiserV7MeasurementKey, RiserOutlet, RiserOutletResultColumn, V7DryWetRiserResponses } from "./dryWetRiserTypes";
import { parseDryWetRiserSystemConfiguration } from "./dryWetRiserConfiguration";
const key="dry_wet_riser" as const; const now=()=>new Date().toISOString(); const fixedWater=["saj_main_water_supply","water_level","automatic_refilling_facilities","drain_and_stop_valve_positions"]; const fixedPump=["pump_house_clean","manual_start_pumps","jockey_pump_pressure","duty_pump_cut_in","standby_pump_cut_in","standby_pump_service_items","battery_charging_alternator","battery_charger_failure_alarm","battery_serviceable","pump_phase_failure_alarm","pumps_auto_start","test_and_gate_valve_positions"];
const rows=(keys:string[])=>Object.fromEntries(keys.map((k)=>[k,{result:null,remarks:""}]));
function definition(catalog:InspectionCatalog, job:InspectionJob){ const compatible=compatibleCatalogSystem(catalog,job.configurationSnapshot.template,key); if(!compatible)throw new Error("Compatible Dry/Wet Riser reference data is not cached for this job. Refresh online first."); return compatible; }
function configured(system:JobSystemSnapshot,isV7:boolean):RiserOutlet[]{ let n=0; return system.locations.flatMap((location)=>Array.from({length:location.presetRowCount},(_,index)=>({rowUuid:crypto.randomUUID(),source:"configured" as const,configuredLocationId:location.id,configuredRowOrdinal:index+1,zoneSnapshot:system.zones.find((zone)=>zone.id===location.zoneId)?{id:location.zoneId!,displayName:system.zones.find((zone)=>zone.id===location.zoneId)!.displayName}:null,locationSnapshot:{id:location.id,displayName:location.displayName},assetReference:typeof location.rowPreset==="object"&&location.rowPreset&&"assetReference" in location.rowPreset&&typeof location.rowPreset.assetReference==="string"?location.rowPreset.assetReference:"",locationText:location.displayName,canvasHoseAt2Result:null,diffuserNozzleResult:null,landingValveResult:null,crandleResult:null,doorResult:null,remarks:"",sortOrder:++n,...(isV7?{fieldRemarks:{}}:{})}))); }
function frozenMode(system:JobSystemSnapshot):"dry"|"wet" { const config=parseDryWetRiserSystemConfiguration(system.systemConfiguration);if(!config)throw new Error("Dry/Wet Riser configuration must provide exactly one frozen mode");return config.riserMode; }
function emptyV7Responses(system:JobSystemSnapshot,mode:"dry"|"wet",definitionValue:unknown,templateCode:string,templateVersion:number):V7DryWetRiserResponses{
  const controls=resolvePublishedDryWetRiserControls(definitionValue,templateCode,templateVersion);
  return {
    schemaVersion:2, mode,
    checklist: Object.fromEntries([...controls.checklist.waterTank,...controls.checklist.pumpHouse].map((item)=>[item.key,{result:null,remarks:""}])) as V7DryWetRiserResponses["checklist"],
    measurements: {
      jockey_psi: { values: { cut_in: null, cut_out: null }, unit: "PSI", result: null, remarks: "" },
      duty_psi: { values: { cut_in: null }, unit: "PSI", result: null, remarks: "" },
      standby_psi: { values: { cut_in: null }, unit: "PSI", result: null, remarks: "" }
    },
    riserOutlets: configured(system,true),
    comments: ""
  };
}
export async function getOrCreateDryWetRiserInspection(job:InspectionJob,system:JobSystemSnapshot,catalog:InspectionCatalog,creator:{id:number;username:string;role:"admin"|"inspector"}|undefined){ const jobSystemKey=`${job.id}:${key}`; const existing=await localDatabase.masterSystemInspections.where("jobSystemKey").equals(jobSystemKey).first(); if(existing){if(existing.systemKey!==key)throw new Error("Stored inspection identity is invalid");return existing as DryWetRiserInspectionRecord;} if(system.systemKey!==key)throw new Error("Invalid Dry/Wet Riser system"); const mode=frozenMode(system); const d=definition(catalog,job); const t=now(); const isV7=job.configurationSnapshot.template.version===7; const responses:DryWetRiserResponses=isV7?emptyV7Responses(system,mode,d.system.definition,job.configurationSnapshot.template.code,job.configurationSnapshot.template.version):{schemaVersion:1,mode,waterTank:rows(fixedWater),pumpHouse:rows(fixedPump),measurements:{jockeyCutIn:null,jockeyCutOut:null,dutyCutIn:null,standbyCutIn:null,unit:"PSI"},riserOutlets:configured(system,false),comments:""}; const record:DryWetRiserInspectionRecord={schemaVersion:1,clientUuid:crypto.randomUUID(),jobSystemKey,jobId:job.id,systemKey:key,instanceKey:"primary",configuredZoneId:null,configuredLocationId:null,displaySequence:1,originalCreatorSnapshot:creator?{source:"device_reported",userId:creator.id,username:creator.username,role:creator.role,capturedAt:t} as DeviceReportedCreator:null,masterTemplate:{id:job.configurationSnapshot.template.id,code:"MFE-FSSR",version:job.configurationSnapshot.template.version},configuration:job.configurationSnapshot.configuration,inspectionSnapshot:{schemaVersion:1,capturedAt:t,job:{id:job.id,reference:job.reference,title:job.title},customer:job.configurationSnapshot.customer,configuration:job.configurationSnapshot.configuration,template:job.configurationSnapshot.template,system:{...system,definition:d.system.definition,repetitionMode:"single_with_repeatable_rows"}},responses,performedAt:t,localCreatedAt:t,localUpdatedAt:t,syncStatus:"Draft"}; try{await localDatabase.masterSystemInspections.add(record);return record;}catch(error){const winner=await localDatabase.masterSystemInspections.where("jobSystemKey").equals(jobSystemKey).first();if(winner?.systemKey===key)return winner as DryWetRiserInspectionRecord;throw error;} }
function v7SubmitIssues(record:DryWetRiserInspectionRecord,r:V7DryWetRiserResponses,attachments:InspectionAttachmentRecord[]):string[]{
  const issues:string[]=[]; let mode:"dry"|"wet"|undefined;
  try{mode=frozenMode(record.inspectionSnapshot.system);}catch{issues.push("Frozen Riser Mode is invalid");}
  if(r.mode!==mode)issues.push("Frozen Riser Mode cannot be changed");
  const controls=resolvePublishedDryWetRiserControls(record.inspectionSnapshot.system.definition,record.masterTemplate.code,record.masterTemplate.version);
  for(const [section,definitions] of [["Water Tank",controls.checklist.waterTank],["Pump House",controls.checklist.pumpHouse]] as const){
    for(const item of definitions){
      const value=r.checklist[item.key as keyof V7DryWetRiserResponses["checklist"]];
      if(!value||!item.result.options.some((option)=>option.value===value.result))issues.push(`${section}: ${item.label} result required`);
      if((value?.remarks.length??0)>item.remarks.maxLength)issues.push(`${section}: ${item.label} remarks too long`);
    }
  }
  for(const definition of controls.measurements){
    const measurementKey=definition.key as DryWetRiserV7MeasurementKey; const item=r.measurements[measurementKey];
    for(const valueDefinition of definition.values){ const value=item.values[valueDefinition.key as keyof typeof item.values]; if(!Number.isFinite(value))issues.push(`Pump House: ${definition.label} ${valueDefinition.label} required`); }
    if(item.unit!=="PSI")issues.push(`Pump House: ${definition.label} unit is required`);
    if(!definition.result.options.some((option)=>option.value===item.result))issues.push(`Pump House: ${definition.label} result required`);
    if(item.remarks.length>definition.remarks.maxLength)issues.push(`Pump House: ${definition.label} remarks too long`);
  }
  if(r.riserOutlets.length===0)issues.push("At least one Riser Outlet is required");
  const configuredRows=record.inspectionSnapshot.system.locations.flatMap((location)=>Array.from({length:location.presetRowCount},(_,i)=>`${location.id}:${i+1}`));
  const actual=new Set<string>();const retainedConfiguredRows=new Set<string>();
  for(const row of r.riserOutlets){
    if(!row.rowUuid||actual.has(row.rowUuid))issues.push("Riser Outlet UUIDs must be unique");
    actual.add(row.rowUuid);
    if(row.sortOrder<1||row.sortOrder!==r.riserOutlets.indexOf(row)+1)issues.push("Riser Outlet ordering is invalid");
    if(!row.locationText||row.locationText.length>250)issues.push("Every Riser Outlet needs a Location");
    for(const column of controls.repeatableRows.resultColumns){
      const field=column.key as RiserOutletResultColumn; const value=row[field];
      if(!column.result.options.some((option)=>option.value===value))issues.push(`Every Riser Outlet needs ${column.label} result`);
      if(isDryWetRiserV7EvidenceFinding(value)&&!row.fieldRemarks?.[field]?.trim())issues.push(`${column.label} requires its own Remark`);
    }
    if(row.source==="configured"){
      const configuredKey=`${row.configuredLocationId}:${row.configuredRowOrdinal}`;
      if(!row.configuredLocationId||!row.configuredRowOrdinal||!configuredRows.includes(configuredKey)||retainedConfiguredRows.has(configuredKey))issues.push("Configured Riser Outlet provenance is invalid");
      else retainedConfiguredRows.add(configuredKey);
    }
    if(row.source==="technician"&&(row.configuredLocationId!==null||row.configuredRowOrdinal!==null))issues.push("Technician Riser Outlet provenance is invalid");
  }
  if(retainedConfiguredRows.size!==configuredRows.length)issues.push("Configured Riser Outlets must be retained");
  if(r.comments.length>4000)issues.push("Comments too long");
  issues.push(...v7DryWetRiserSubmissionIssues(record,r,attachments));
  return issues;
}
export function submitIssues(record:DryWetRiserInspectionRecord,r:DryWetRiserResponses,attachments:InspectionAttachmentRecord[]=[]):string[]{
  if(r.schemaVersion===2)return v7SubmitIssues(record,r,attachments);
  const issues:string[]=[]; let mode:"dry"|"wet"|undefined;try{mode=frozenMode(record.inspectionSnapshot.system);}catch{issues.push("Frozen Riser Mode is invalid");} if(r.mode!==mode)issues.push("Frozen Riser Mode cannot be changed"); for(const [section,values] of [["Water Tank",r.waterTank],["Pump House",r.pumpHouse]] as const)for(const [k,v] of Object.entries(values)){if(!v||!(v.result==="good"||v.result==="poor"))issues.push(`${section}: ${k} result required`);if(v?.remarks.length>2000)issues.push(`${section}: remarks too long`);} for(const value of [r.measurements.jockeyCutIn,r.measurements.jockeyCutOut,r.measurements.dutyCutIn,r.measurements.standbyCutIn])if(!Number.isFinite(value))issues.push("All four PSI values are required");if(r.measurements.unit!=="PSI")issues.push("PSI unit is required");if(r.riserOutlets.length===0)issues.push("At least one Riser Outlet is required"); const configuredRows=record.inspectionSnapshot.system.locations.flatMap((location)=>Array.from({length:location.presetRowCount},(_,i)=>`${location.id}:${i+1}`));const actual=new Set<string>();const retainedConfiguredRows=new Set<string>();for(const row of r.riserOutlets){if(!row.rowUuid||actual.has(row.rowUuid))issues.push("Riser Outlet UUIDs must be unique");actual.add(row.rowUuid);if(row.sortOrder<1||row.sortOrder!==r.riserOutlets.indexOf(row)+1)issues.push("Riser Outlet ordering is invalid");if(!row.locationText||row.locationText.length>250||![row.canvasHoseAt2Result,row.diffuserNozzleResult,row.landingValveResult,row.crandleResult,row.doorResult].every((value)=>value==="good"||value==="poor"))issues.push("Every Riser Outlet needs Location and all results");if(row.source==="configured"){const configuredKey=`${row.configuredLocationId}:${row.configuredRowOrdinal}`;if(!row.configuredLocationId||!row.configuredRowOrdinal||!configuredRows.includes(configuredKey)||retainedConfiguredRows.has(configuredKey))issues.push("Configured Riser Outlet provenance is invalid");else retainedConfiguredRows.add(configuredKey);}if(row.source==="technician"&&(row.configuredLocationId!==null||row.configuredRowOrdinal!==null))issues.push("Technician Riser Outlet provenance is invalid");}if(retainedConfiguredRows.size!==configuredRows.length)issues.push("Configured Riser Outlets must be retained");if(r.comments.length>4000)issues.push("Comments too long");return issues;
}
function payload(record:DryWetRiserInspectionRecord,evidenceManifest?:ReturnType<typeof v7DryWetRiserManifest>){const {clientUuid,jobId,systemKey,instanceKey,configuredZoneId,configuredLocationId,displaySequence,originalCreatorSnapshot,masterTemplate,configuration,inspectionSnapshot,responses,performedAt}=record;return{clientUuid,jobId,systemKey,instanceKey,configuredZoneId,configuredLocationId,displaySequence,originalCreatorSnapshot,masterTemplate,configuration,inspectionSnapshot,responses,performedAt,...(evidenceManifest?{evidenceManifest}:{})};}
export async function saveDryWetRiserDraft(record:DryWetRiserInspectionRecord,responses:DryWetRiserResponses){let next:DryWetRiserInspectionRecord|undefined;await localDatabase.transaction("rw",localDatabase.masterSystemInspections,async()=>{const live=await localDatabase.masterSystemInspections.get(record.clientUuid);if(!live||live.systemKey!==key||live.localUpdatedAt!==record.localUpdatedAt||live.syncStatus!=="Draft")throw new Error("This Dry/Wet Riser record changed elsewhere. Reload before saving.");const current=live as DryWetRiserInspectionRecord;next={...current,responses:{...responses,mode:frozenMode(current.inspectionSnapshot.system)},localUpdatedAt:now(),lastSyncError:undefined};await localDatabase.masterSystemInspections.put(next);});return next!;}
export async function submitLocalDryWetRiser(record:DryWetRiserInspectionRecord,responses:DryWetRiserResponses){let next:DryWetRiserInspectionRecord|undefined;const activeKey=`masterSystemInspection:create:${record.clientUuid}`;await localDatabase.transaction("rw",localDatabase.masterSystemInspections,localDatabase.inspectionAttachments,localDatabase.syncOutbox,async()=>{const live=await localDatabase.masterSystemInspections.get(record.clientUuid);if(!live||live.systemKey!==key||live.localUpdatedAt!==record.localUpdatedAt||live.syncStatus!=="Draft")throw new Error("This Dry/Wet Riser record changed elsewhere. Reload before submitting.");const current=live as DryWetRiserInspectionRecord;const frozenResponses={...responses,mode:frozenMode(current.inspectionSnapshot.system)} as DryWetRiserResponses;const isV7=current.masterTemplate.version===7;const photos=isV7?await listDryWetRiserV7Photos(current.clientUuid):[];if(submitIssues(current,frozenResponses,photos).length)throw new Error("Complete required Dry/Wet Riser fields");next={...current,responses:frozenResponses,syncStatus:"Pending",performedAt:now(),localUpdatedAt:now(),lastSyncError:undefined};const manifest=isV7&&frozenResponses.schemaVersion===2?v7DryWetRiserManifest(photos,frozenResponses):undefined;const existing=await localDatabase.syncOutbox.where("activeKey").equals(activeKey).first();const item:SyncOutboxItem={operationId:existing?.operationId??crypto.randomUUID(),entityType:"masterSystemInspection",entityId:record.clientUuid,action:"create",payload:payload(next,manifest),createdAt:next.localCreatedAt,attempts:existing?.attempts??0,status:"Pending",activeKey};await localDatabase.masterSystemInspections.put(next);if(existing)await localDatabase.syncOutbox.put(item);else await localDatabase.syncOutbox.add(item);if(manifest){for(const photo of photos.filter((candidate)=>manifest.some((entry)=>entry.photoUuid===candidate.photoUuid))){await localDatabase.inspectionAttachments.update(photo.photoUuid,{syncStatus:"Pending",localUpdatedAt:next.localUpdatedAt});const evidenceKey=`v7StagedEvidence:create:${photo.photoUuid}`;if(!await localDatabase.syncOutbox.where("activeKey").equals(evidenceKey).first())await localDatabase.syncOutbox.add(v7DryWetRiserEvidenceOutbox(photo));}}});return next!;}
export function addRiserOutlet(responses:DryWetRiserResponses):DryWetRiserResponses{ return { ...responses, riserOutlets: [...responses.riserOutlets, { rowUuid: crypto.randomUUID(), source: "technician", configuredLocationId: null, configuredRowOrdinal: null, zoneSnapshot: null, locationSnapshot: null, assetReference: "", locationText: "", canvasHoseAt2Result: null, diffuserNozzleResult: null, landingValveResult: null, crandleResult: null, doorResult: null, remarks: "", sortOrder: responses.riserOutlets.length + 1, ...(responses.schemaVersion === 2 ? { fieldRemarks: {} } : {}) }] }; }
export async function returnFailedDryWetRiserToDraft(record:DryWetRiserInspectionRecord){let next:DryWetRiserInspectionRecord|undefined;const activeKey=`masterSystemInspection:create:${record.clientUuid}`;await localDatabase.transaction("rw",localDatabase.masterSystemInspections,localDatabase.syncOutbox,async()=>{const live=await localDatabase.masterSystemInspections.get(record.clientUuid);if(!live||live.systemKey!==key||live.localUpdatedAt!==record.localUpdatedAt||!["Failed","Conflict"].includes(live.syncStatus))throw new Error("This Dry/Wet Riser record changed elsewhere. Reload before correcting it.");next={...(live as DryWetRiserInspectionRecord),syncStatus:"Draft",localUpdatedAt:now(),lastSyncError:undefined};const item=await localDatabase.syncOutbox.where("activeKey").equals(activeKey).first();if(item)await localDatabase.syncOutbox.update(item.operationId,{status:"Completed",activeKey:undefined,completedAt:now(),lastError:"Superseded by technician correction"});await localDatabase.masterSystemInspections.put(next);});return next!;}
