import { useEffect, useMemo, useState } from "react";
import { ResultSelector } from "../inspectionControls/ResultSelector";
import { RemarksField } from "../inspectionControls/RemarksField";
import { inspectionSyncMessage } from "../uiPresentation";
import { parseDryWetRiserSystemConfiguration } from "./dryWetRiserConfiguration";
import type { DryWetRiserInspectionRecord, DryWetRiserResponses, RiserResult } from "./dryWetRiserTypes";
import { submitIssues } from "./dryWetRiserRepository";

const resultDefinition = { type: "single_select" as const, required: true, options: [{ value: "good" as const, label: "Good" }, { value: "poor" as const, label: "Poor" }] };
const remarks = { policy: "optional" as const, maxLength: 2000 };
const checklistLabels: Record<string, string> = {
  saj_main_water_supply: "SAJ Main Water Supply", water_level: "Water Level", automatic_refilling_facilities: "Automatic Refilling Facilities", drain_and_stop_valve_positions: "Drain and Stop Valve Positions",
  pump_house_clean: "Pump House Cleanliness", manual_start_pumps: "Manual Start Pumps", jockey_pump_pressure: "Jockey Pump Pressure", duty_pump_cut_in: "Duty Pump Cut-In", standby_pump_cut_in: "Standby Pump Cut-In", standby_pump_service_items: "Standby Pump Service Items", battery_charging_alternator: "Battery Charging Alternator", battery_charger_failure_alarm: "Battery Charger Failure Alarm", battery_serviceable: "Battery Serviceable", pump_phase_failure_alarm: "Pump Phase Failure Alarm", pumps_auto_start: "Pumps Auto Start", test_and_gate_valve_positions: "Test and Gate Valve Positions"
};
const measurementLabels = { jockeyCutIn: "Jockey Pump Cut-In", jockeyCutOut: "Jockey Pump Cut-Out", dutyCutIn: "Duty Pump Cut-In", standbyCutIn: "Standby Pump Cut-In" } as const;
const outletLabels = { canvasHoseAt2Result: "Canvas Hose ×2", diffuserNozzleResult: "Diffuser Nozzle", landingValveResult: "Landing Valve", crandleResult: "Crandle", doorResult: "Door" } as const;

type Props = { record: DryWetRiserInspectionRecord; onBack: () => void; onSaveDraft: (responses: DryWetRiserResponses) => Promise<void>; onSubmitLocal: (responses: DryWetRiserResponses) => Promise<void>; onEditFailed: () => Promise<void> };

export function DryWetRiserInspectionForm({ record, onBack, onSaveDraft, onSubmitLocal, onEditFailed }: Props) {
  const [responses, setResponses] = useState(record.responses);
  const [message, setMessage] = useState("");
  const [show, setShow] = useState(false);
  useEffect(() => setResponses(record.responses), [record]);
  const readOnly = record.syncStatus !== "Draft";
  const frozenRiserMode = parseDryWetRiserSystemConfiguration(record.inspectionSnapshot.system.systemConfiguration)?.riserMode;
  const riserSystemTitle = frozenRiserMode === "dry" ? "Dry Riser System" : frozenRiserMode === "wet" ? "Wet Riser System" : "Riser Type Unavailable";
  const issues = useMemo(() => show ? submitIssues(record, responses) : [], [record, responses, show]);
  const update = (section: "waterTank" | "pumpHouse", key: string, change: object) => setResponses((current) => ({ ...current, [section]: { ...current[section], [key]: { ...current[section][key], ...change } } }));
  const updateOutlet = (rowUuid: string, change: Partial<DryWetRiserResponses["riserOutlets"][number]>) => setResponses((current) => ({ ...current, riserOutlets: current.riserOutlets.map((candidate) => candidate.rowUuid === rowUuid ? { ...candidate, ...change } : candidate) }));
  const add = () => setResponses((current) => ({ ...current, riserOutlets: [...current.riserOutlets, { rowUuid: crypto.randomUUID(), source: "technician", configuredLocationId: null, configuredRowOrdinal: null, zoneSnapshot: null, locationSnapshot: null, assetReference: "", locationText: "", canvasHoseAt2Result: null, diffuserNozzleResult: null, landingValveResult: null, crandleResult: null, doorResult: null, remarks: "", sortOrder: current.riserOutlets.length + 1 }] }));
  const checklist = (section: "waterTank" | "pumpHouse", key: string) => <section className="hose-check-row" key={key}><strong>{checklistLabels[key] ?? key}</strong><ResultSelector definition={resultDefinition} label={`${checklistLabels[key] ?? key} condition`} value={responses[section][key]?.result ?? null} readOnly={readOnly} onChange={(result) => update(section, key, { result })} /><RemarksField label="Remarks" definition={remarks} value={responses[section][key]?.remarks ?? ""} readOnly={readOnly} onChange={(value) => update(section, key, { remarks: value })} /></section>;

  return <section className="hose-reel-form" aria-labelledby="dry-wet-riser-title">
    <button type="button" className="secondary-command" onClick={onBack}>Back to Systems</button>
    <header className="inspection-context"><div><p className="eyebrow">{record.inspectionSnapshot.job.reference}</p><h2 id="dry-wet-riser-title">{riserSystemTitle}</h2><p><strong>{record.inspectionSnapshot.customer.displayName}</strong></p><p>{record.inspectionSnapshot.job.title}</p></div><strong role="status">{inspectionSyncMessage(record.syncStatus)}</strong></header>
    {record.lastSyncError ? <p className="error-text">{record.lastSyncError}</p> : null}{message ? <p className="form-message" role="status">{message}</p> : null}
    {show && issues.length ? <section className="validation-summary" role="alert"><h3>Cannot submit yet</h3><ul>{issues.map((issue, index) => <li key={index}>{issue}</li>)}</ul></section> : null}
    {["Failed", "Conflict"].includes(record.syncStatus) ? <button type="button" onClick={() => void onEditFailed()}>Edit Failed Inspection</button> : null}
    <fieldset disabled><legend>Riser Type</legend><p className="field-help">The selected type is configured and frozen with this service visit.</p><div className="riser-mode-options" role="radiogroup" aria-label="Configured riser type"><label className={frozenRiserMode === "dry" ? "riser-mode-option riser-mode-option--selected" : "riser-mode-option"}><input type="radio" name="riser-mode" checked={frozenRiserMode === "dry"} readOnly />Dry Riser System</label><label className={frozenRiserMode === "wet" ? "riser-mode-option riser-mode-option--selected" : "riser-mode-option"}><input type="radio" name="riser-mode" checked={frozenRiserMode === "wet"} readOnly />Wet Riser System</label></div></fieldset>
    <fieldset disabled={readOnly}><legend>Water Tank</legend>{Object.keys(responses.waterTank).map((key) => checklist("waterTank", key))}</fieldset>
    <fieldset disabled={readOnly}><legend>Pump House</legend>{Object.keys(responses.pumpHouse).map((key) => checklist("pumpHouse", key))}<section className="measurement-card"><strong>PSI Measurements</strong>{(Object.keys(measurementLabels) as Array<keyof typeof measurementLabels>).map((key) => <label key={key}>{measurementLabels[key]} (PSI)<input type="number" value={responses.measurements[key] ?? ""} onChange={(event) => setResponses((current) => ({ ...current, measurements: { ...current.measurements, [key]: event.target.value === "" ? null : Number(event.target.value) } }))} /></label>)}</section></fieldset>
    <fieldset disabled={readOnly}><legend>Riser Outlet</legend><div className="riser-outlet-table" role="table" aria-label="Riser outlet inspection rows"><div className="riser-outlet-table__header" role="row"><span role="columnheader">Outlet</span><span role="columnheader">Reference &amp; location</span><span role="columnheader">Inspection results</span><span role="columnheader">Remarks</span></div>{responses.riserOutlets.map((row, index) => <section className="riser-outlet-table__row" role="row" key={row.rowUuid}><div className="riser-outlet-table__identity" role="cell"><strong>Outlet {index + 1}</strong>{row.source === "configured" ? <small>Configured</small> : <small>Added by technician</small>}</div><div className="riser-outlet-table__location" role="cell"><label>Reference Number<input value={row.assetReference} onChange={(event) => updateOutlet(row.rowUuid, { assetReference: event.target.value })} /></label><label>Location<input value={row.locationText} onChange={(event) => updateOutlet(row.rowUuid, { locationText: event.target.value })} /></label></div><div className="riser-outlet-table__results" role="cell">{(Object.keys(outletLabels) as Array<keyof typeof outletLabels>).map((field) => <ResultSelector<RiserResult> key={field} definition={resultDefinition} label={`${outletLabels[field]} condition`} value={row[field]} readOnly={readOnly} onChange={(value) => updateOutlet(row.rowUuid, { [field]: value })} />)}</div><div className="riser-outlet-table__remarks" role="cell"><RemarksField label="Remarks" definition={remarks} value={row.remarks} readOnly={readOnly} onChange={(value) => updateOutlet(row.rowUuid, { remarks: value })} />{row.source === "technician" ? <button type="button" className="secondary-command" onClick={() => setResponses((current) => ({ ...current, riserOutlets: current.riserOutlets.filter((candidate) => candidate.rowUuid !== row.rowUuid).map((candidate, position) => ({ ...candidate, sortOrder: position + 1 })) }))}>Remove outlet</button> : null}</div></section>)}</div>{!readOnly ? <button type="button" className="secondary-command" onClick={add}>Add Riser Outlet</button> : null}</fieldset>
    <fieldset disabled={readOnly}><legend>Comments</legend><textarea value={responses.comments} onChange={(event) => setResponses((current) => ({ ...current, comments: event.target.value }))} /></fieldset>
    {!readOnly ? <div className="form-actions sticky-form-actions"><button type="button" onClick={() => void onSaveDraft(responses).then(() => setMessage("Saved on this device.")).catch((error) => setMessage(error.message))}>Save Draft</button><button type="button" onClick={() => { setShow(true); if (!submitIssues(record, responses).length) void onSubmitLocal(responses).catch((error) => setMessage(error.message)); }}>Submit Inspection</button></div> : null}
  </section>;
}
