import { useEffect, useMemo, useState } from "react";
import { ResultSelector } from "../inspectionControls/ResultSelector";
import { RemarksField } from "../inspectionControls/RemarksField";
import { MeasurementValueInput } from "../inspectionControls/MeasurementValueInput";
import { inspectionSyncMessage } from "../uiPresentation";
import { parseDryWetRiserSystemConfiguration } from "./dryWetRiserConfiguration";
import { resolvePublishedDryWetRiserControls } from "./dryWetRiserDefinition";
import { DryWetRiserV7EvidenceField } from "./DryWetRiserV7EvidenceField";
import { isDryWetRiserV7EvidenceFinding, listDryWetRiserV7Photos, type DryWetRiserV7FieldPath } from "./dryWetRiserV7Evidence";
import type { DryWetRiserInspectionRecord, DryWetRiserResponses, DryWetRiserV7ChecklistKey, DryWetRiserV7MeasurementKey, RiserOutletResultColumn, RiserResult, V7DryWetRiserResponses } from "./dryWetRiserTypes";
import { addRiserOutlet, submitIssues } from "./dryWetRiserRepository";
import type { InspectionAttachmentRecord } from "../attachments/attachmentTypes";

const resultDefinition = { type: "single_select" as const, required: true, options: [{ value: "good" as const, label: "Good" }, { value: "poor" as const, label: "Poor" }] };
const remarks = { policy: "optional" as const, maxLength: 2000 };
const checklistLabels: Record<string, string> = {
  saj_main_water_supply: "SAJ Main Water Supply", water_level: "Water Level", automatic_refilling_facilities: "Automatic Refilling Facilities", drain_and_stop_valve_positions: "Drain and Stop Valve Positions",
  pump_house_clean: "Pump House Cleanliness", manual_start_pumps: "Manual Start Pumps", jockey_pump_pressure: "Jockey Pump Pressure", duty_pump_cut_in: "Duty Pump Cut-In", standby_pump_cut_in: "Standby Pump Cut-In", standby_pump_service_items: "Standby Pump Service Items", battery_charging_alternator: "Battery Charging Alternator", battery_charger_failure_alarm: "Battery Charger Failure Alarm", battery_serviceable: "Battery Serviceable", pump_phase_failure_alarm: "Pump Phase Failure Alarm", pumps_auto_start: "Pumps Auto Start", test_and_gate_valve_positions: "Test and Gate Valve Positions"
};
const measurementLabels = { jockeyCutIn: "Jockey Pump Cut-In", jockeyCutOut: "Jockey Pump Cut-Out", dutyCutIn: "Duty Pump Cut-In", standbyCutIn: "Standby Pump Cut-In" } as const;
const outletLabels = { canvasHoseAt2Result: "Canvas Hose ×2", diffuserNozzleResult: "Diffuser Nozzle", landingValveResult: "Landing Valve", crandleResult: "Crandle", doorResult: "Door" } as const;

type Props = { record: DryWetRiserInspectionRecord; onBack: () => void; onSaveDraft: (responses: DryWetRiserResponses) => Promise<void>; onSubmitLocal: (responses: DryWetRiserResponses) => Promise<void>; onEditFailed: () => Promise<void> };

export function DryWetRiserInspectionForm({ record, onBack, onSaveDraft, onSubmitLocal, onEditFailed }: Props) {
  const [responses, setResponses] = useState(record.responses);
  const [message, setMessage] = useState("");
  const [show, setShow] = useState(false);
  const [photos, setPhotos] = useState<InspectionAttachmentRecord[]>([]);
  const isV7 = record.masterTemplate.version === 7;
  useEffect(() => setResponses(record.responses), [record]);
  useEffect(() => { setMessage(""); setShow(false); }, [record.clientUuid]);
  useEffect(() => { if (isV7) void listDryWetRiserV7Photos(record.clientUuid).then(setPhotos); else setPhotos([]); }, [isV7, record.clientUuid, record.localUpdatedAt]);
  const readOnly = record.syncStatus !== "Draft";
  const refreshPhotos = async () => setPhotos(await listDryWetRiserV7Photos(record.clientUuid));
  const evidenceFor = (fieldPath: DryWetRiserV7FieldPath) => photos.find((photo) => photo.fieldPath === fieldPath);
  const frozenRiserMode = parseDryWetRiserSystemConfiguration(record.inspectionSnapshot.system.systemConfiguration)?.riserMode;
  const riserSystemTitle = frozenRiserMode === "dry" ? "Dry Riser System" : frozenRiserMode === "wet" ? "Wet Riser System" : "Riser Type Unavailable";
  const issues = useMemo(() => show ? submitIssues(record, responses, photos) : [], [record, responses, show, photos]);
  const controlResolution = useMemo(() => {
    if (!isV7) return { controls: undefined };
    try { return { controls: resolvePublishedDryWetRiserControls(record.inspectionSnapshot.system.definition, record.masterTemplate.code, record.masterTemplate.version) }; }
    catch (error) { return { controls: undefined, error: error instanceof Error ? error.message : "Inspection controls are unavailable" }; }
  }, [isV7, record.inspectionSnapshot.system.definition, record.masterTemplate.code, record.masterTemplate.version]);
  const controls = controlResolution.controls;
  const update = (section: "waterTank" | "pumpHouse", key: string, change: object) => setResponses((current) => current.schemaVersion === 2 ? current : ({ ...current, [section]: { ...current[section], [key]: { ...current[section][key], ...change } } }));
  const updateV7Checklist = (key: DryWetRiserV7ChecklistKey, change: Partial<{ result: V7DryWetRiserResponses["checklist"][DryWetRiserV7ChecklistKey]["result"]; remarks: string }>) => setResponses((current) => current.schemaVersion !== 2 ? current : ({ ...current, checklist: { ...current.checklist, [key]: { ...current.checklist[key], ...change } } }));
  const updateV7Measurement = (measurementKey: DryWetRiserV7MeasurementKey, change: object) => setResponses((current) => current.schemaVersion !== 2 ? current : ({ ...current, measurements: { ...current.measurements, [measurementKey]: { ...current.measurements[measurementKey], ...change } } }));
  const updateOutlet = (rowUuid: string, change: Partial<DryWetRiserResponses["riserOutlets"][number]>) => setResponses((current) => ({ ...current, riserOutlets: current.riserOutlets.map((candidate) => candidate.rowUuid === rowUuid ? { ...candidate, ...change } : candidate) }));
  const add = () => setResponses(addRiserOutlet);
  const checklist = (section: "waterTank" | "pumpHouse", key: string) => <section className="hose-check-row" key={key}><strong>{checklistLabels[key] ?? key}</strong><ResultSelector definition={resultDefinition} label={`${checklistLabels[key] ?? key} condition`} value={responses.schemaVersion === 2 ? null : responses[section][key]?.result ?? null} readOnly={readOnly} onChange={(result) => update(section, key, { result })} /><RemarksField label="Remarks" definition={remarks} value={responses.schemaVersion === 2 ? "" : responses[section][key]?.remarks ?? ""} readOnly={readOnly} onChange={(value) => update(section, key, { remarks: value })} /></section>;

  if (isV7 && responses.schemaVersion === 2) {
    if (!controls) return <section className="hose-reel-form" aria-labelledby="dry-wet-riser-title">
      <button type="button" className="secondary-command" onClick={onBack}>Back to Systems</button>
      <h2 id="dry-wet-riser-title">Dry/Wet Riser inspection unavailable</h2>
      <p className="error-text" role="alert">{controlResolution.error ?? "The frozen inspection definition is invalid."}</p>
    </section>;
    const v7 = responses;
    return <section className="hose-reel-form" aria-labelledby="dry-wet-riser-title">
      <button type="button" className="secondary-command" onClick={onBack}>Back to Systems</button>
      <header className="inspection-context"><div><p className="eyebrow">{record.inspectionSnapshot.job.reference}</p><h2 id="dry-wet-riser-title">{riserSystemTitle}</h2><p><strong>{record.inspectionSnapshot.customer.displayName}</strong></p><p>{record.inspectionSnapshot.job.title}</p></div><strong role="status">{inspectionSyncMessage(record.syncStatus)}</strong></header>
      {record.lastSyncError ? <p className="error-text">{record.lastSyncError}</p> : null}{message ? <p className="form-message" role="status">{message}</p> : null}
      {show && issues.length ? <section className="validation-summary" role="alert"><h3>Cannot submit yet</h3><ul>{issues.map((issue, index) => <li key={index}>{issue}</li>)}</ul></section> : null}
      {["Failed", "Conflict"].includes(record.syncStatus) ? <button type="button" onClick={() => void onEditFailed()}>Edit Failed Inspection</button> : null}
      <fieldset disabled><legend>Riser Type</legend><p className="field-help">The selected type is configured and frozen with this service visit.</p><div className="riser-mode-options" role="radiogroup" aria-label="Configured riser type"><label className={frozenRiserMode === "dry" ? "riser-mode-option riser-mode-option--selected" : "riser-mode-option"}><input type="radio" name="riser-mode" checked={frozenRiserMode === "dry"} readOnly />Dry Riser System</label><label className={frozenRiserMode === "wet" ? "riser-mode-option riser-mode-option--selected" : "riser-mode-option"}><input type="radio" name="riser-mode" checked={frozenRiserMode === "wet"} readOnly />Wet Riser System</label></div></fieldset>
      <fieldset disabled={readOnly}><legend>Water Tank</legend>{controls.checklist.waterTank.map((definition) => { const key = definition.key as DryWetRiserV7ChecklistKey; const item = v7.checklist[key]; const fieldPath = `dry_wet_riser_checks.${key}` as DryWetRiserV7FieldPath; return <section className="hose-check-row" key={key}><strong>{definition.label}</strong><ResultSelector definition={definition.result} label={`${definition.label} result`} value={item?.result ?? null} readOnly={readOnly} onChange={(result) => updateV7Checklist(key, { result })} /><RemarksField label="Remarks" definition={definition.remarks} value={item?.remarks ?? ""} readOnly={readOnly} onChange={(remarksValue) => updateV7Checklist(key, { remarks: remarksValue })} />{isDryWetRiserV7EvidenceFinding(item?.result) ? <DryWetRiserV7EvidenceField record={record} fieldPath={fieldPath} attachment={evidenceFor(fieldPath)} onChanged={refreshPhotos} /> : null}</section>; })}</fieldset>
      <fieldset disabled={readOnly}><legend>Pump House</legend>{controls.checklist.pumpHouse.map((definition) => { const key = definition.key as DryWetRiserV7ChecklistKey; const item = v7.checklist[key]; const fieldPath = `dry_wet_riser_checks.${key}` as DryWetRiserV7FieldPath; return <section className="hose-check-row" key={key}><strong>{definition.label}</strong><ResultSelector definition={definition.result} label={`${definition.label} result`} value={item?.result ?? null} readOnly={readOnly} onChange={(result) => updateV7Checklist(key, { result })} /><RemarksField label="Remarks" definition={definition.remarks} value={item?.remarks ?? ""} readOnly={readOnly} onChange={(remarksValue) => updateV7Checklist(key, { remarks: remarksValue })} />{isDryWetRiserV7EvidenceFinding(item?.result) ? <DryWetRiserV7EvidenceField record={record} fieldPath={fieldPath} attachment={evidenceFor(fieldPath)} onChanged={refreshPhotos} /> : null}</section>; })}
        {controls.measurements.map((definition) => { const measurementKey = definition.key as DryWetRiserV7MeasurementKey; const item = v7.measurements[measurementKey]; const fieldPath = `dry_wet_riser_measurements.${measurementKey}` as DryWetRiserV7FieldPath; return <section className="measurement-card" key={measurementKey}><strong>{definition.label}</strong>{definition.values.map((valueDefinition) => <MeasurementValueInput key={valueDefinition.key} definition={valueDefinition} value={item.values[valueDefinition.key as keyof typeof item.values]} readOnly={readOnly} onChange={(value) => updateV7Measurement(measurementKey, { values: { ...item.values, [valueDefinition.key]: value } })} />)}<ResultSelector definition={definition.result} label={`${definition.label} result`} value={item.result} readOnly={readOnly} onChange={(result) => updateV7Measurement(measurementKey, { result })} /><RemarksField label="Remarks" definition={definition.remarks} value={item.remarks} readOnly={readOnly} onChange={(remarksValue) => updateV7Measurement(measurementKey, { remarks: remarksValue })} />{isDryWetRiserV7EvidenceFinding(item.result) ? <DryWetRiserV7EvidenceField record={record} fieldPath={fieldPath} attachment={evidenceFor(fieldPath)} onChanged={refreshPhotos} /> : null}</section>; })}
      </fieldset>
      <fieldset disabled={readOnly}><legend>Riser Outlet</legend><div className="riser-outlet-table" role="table" aria-label="Riser outlet inspection rows"><div className="riser-outlet-table__header" role="row"><span role="columnheader">Outlet</span><span role="columnheader">Reference &amp; location</span><span role="columnheader">Inspection results</span><span role="columnheader">Remarks</span></div>{v7.riserOutlets.map((row, index) => <section className="riser-outlet-table__row" role="row" key={row.rowUuid}><div className="riser-outlet-table__identity" role="cell"><strong>Outlet {index + 1}</strong>{row.source === "configured" ? <small>Configured</small> : <small>Added by technician</small>}</div><div className="riser-outlet-table__location" role="cell"><label>Reference Number<input value={row.assetReference} onChange={(event) => updateOutlet(row.rowUuid, { assetReference: event.target.value })} /></label><label>Location<input value={row.locationText} onChange={(event) => updateOutlet(row.rowUuid, { locationText: event.target.value })} /></label></div><div className="riser-outlet-table__results" role="cell">{controls.repeatableRows.resultColumns.map((column) => { const field = column.key as RiserOutletResultColumn; const value = row[field]; const fieldPath = `riser_outlet.riser_outlet_rows.rows.${row.rowUuid}.${field}` as DryWetRiserV7FieldPath; return <div className="hose-component" key={field}><strong>{column.label}</strong><ResultSelector definition={column.result} label={`${column.label} condition`} value={value} readOnly={readOnly} onChange={(nextValue) => updateOutlet(row.rowUuid, { [field]: nextValue })} />{isDryWetRiserV7EvidenceFinding(value) ? <section><RemarksField label={`${column.label} Remark *`} definition={controls.repeatableRows.remarks} value={row.fieldRemarks?.[field] ?? ""} readOnly={readOnly} onChange={(remark) => updateOutlet(row.rowUuid, { fieldRemarks: { ...row.fieldRemarks, [field]: remark } })} /><DryWetRiserV7EvidenceField record={record} fieldPath={fieldPath} attachment={evidenceFor(fieldPath)} onChanged={refreshPhotos} /></section> : null}</div>; })}</div><div className="riser-outlet-table__remarks" role="cell"><RemarksField label="Remarks" definition={controls.repeatableRows.remarks} value={row.remarks} readOnly={readOnly} onChange={(value) => updateOutlet(row.rowUuid, { remarks: value })} />{row.source === "technician" ? <button type="button" className="secondary-command" onClick={() => setResponses((current) => ({ ...current, riserOutlets: current.riserOutlets.filter((candidate) => candidate.rowUuid !== row.rowUuid).map((candidate, position) => ({ ...candidate, sortOrder: position + 1 })) }))}>Remove outlet</button> : null}</div></section>)}</div>{!readOnly ? <button type="button" className="secondary-command" onClick={add}>Add Riser Outlet</button> : null}</fieldset>
      <fieldset disabled={readOnly}><legend>Comments</legend><textarea value={v7.comments} onChange={(event) => setResponses((current) => ({ ...current, comments: event.target.value }))} /></fieldset>
      {!readOnly ? <div className="form-actions sticky-form-actions"><button type="button" onClick={() => void onSaveDraft(responses).then(() => setMessage("Saved on this device.")).catch((error) => setMessage(error.message))}>Save Draft</button><button type="button" onClick={() => { setShow(true); if (!submitIssues(record, responses, photos).length) void onSubmitLocal(responses).catch((error) => setMessage(error.message)); }}>Submit Inspection</button></div> : null}
    </section>;
  }

  return <section className="hose-reel-form" aria-labelledby="dry-wet-riser-title">
    <button type="button" className="secondary-command" onClick={onBack}>Back to Systems</button>
    <header className="inspection-context"><div><p className="eyebrow">{record.inspectionSnapshot.job.reference}</p><h2 id="dry-wet-riser-title">{riserSystemTitle}</h2><p><strong>{record.inspectionSnapshot.customer.displayName}</strong></p><p>{record.inspectionSnapshot.job.title}</p></div><strong role="status">{inspectionSyncMessage(record.syncStatus)}</strong></header>
    {record.lastSyncError ? <p className="error-text">{record.lastSyncError}</p> : null}{message ? <p className="form-message" role="status">{message}</p> : null}
    {show && issues.length ? <section className="validation-summary" role="alert"><h3>Cannot submit yet</h3><ul>{issues.map((issue, index) => <li key={index}>{issue}</li>)}</ul></section> : null}
    {["Failed", "Conflict"].includes(record.syncStatus) ? <button type="button" onClick={() => void onEditFailed()}>Edit Failed Inspection</button> : null}
    <fieldset disabled><legend>Riser Type</legend><p className="field-help">The selected type is configured and frozen with this service visit.</p><div className="riser-mode-options" role="radiogroup" aria-label="Configured riser type"><label className={frozenRiserMode === "dry" ? "riser-mode-option riser-mode-option--selected" : "riser-mode-option"}><input type="radio" name="riser-mode" checked={frozenRiserMode === "dry"} readOnly />Dry Riser System</label><label className={frozenRiserMode === "wet" ? "riser-mode-option riser-mode-option--selected" : "riser-mode-option"}><input type="radio" name="riser-mode" checked={frozenRiserMode === "wet"} readOnly />Wet Riser System</label></div></fieldset>
    <fieldset disabled={readOnly}><legend>Water Tank</legend>{responses.schemaVersion === 2 ? null : Object.keys(responses.waterTank).map((key) => checklist("waterTank", key))}</fieldset>
    <fieldset disabled={readOnly}><legend>Pump House</legend>{responses.schemaVersion === 2 ? null : Object.keys(responses.pumpHouse).map((key) => checklist("pumpHouse", key))}<section className="measurement-card"><strong>PSI Measurements</strong>{(Object.keys(measurementLabels) as Array<keyof typeof measurementLabels>).map((key) => <label key={key}>{measurementLabels[key]} (PSI)<input type="number" value={responses.schemaVersion === 2 ? "" : responses.measurements[key] ?? ""} onChange={(event) => setResponses((current) => current.schemaVersion === 2 ? current : ({ ...current, measurements: { ...current.measurements, [key]: event.target.value === "" ? null : Number(event.target.value) } }))} /></label>)}</section></fieldset>
    <fieldset disabled={readOnly}><legend>Riser Outlet</legend><div className="riser-outlet-table" role="table" aria-label="Riser outlet inspection rows"><div className="riser-outlet-table__header" role="row"><span role="columnheader">Outlet</span><span role="columnheader">Reference &amp; location</span><span role="columnheader">Inspection results</span><span role="columnheader">Remarks</span></div>{responses.riserOutlets.map((row, index) => <section className="riser-outlet-table__row" role="row" key={row.rowUuid}><div className="riser-outlet-table__identity" role="cell"><strong>Outlet {index + 1}</strong>{row.source === "configured" ? <small>Configured</small> : <small>Added by technician</small>}</div><div className="riser-outlet-table__location" role="cell"><label>Reference Number<input value={row.assetReference} onChange={(event) => updateOutlet(row.rowUuid, { assetReference: event.target.value })} /></label><label>Location<input value={row.locationText} onChange={(event) => updateOutlet(row.rowUuid, { locationText: event.target.value })} /></label></div><div className="riser-outlet-table__results" role="cell">{(Object.keys(outletLabels) as Array<keyof typeof outletLabels>).map((field) => <ResultSelector<RiserResult> key={field} definition={resultDefinition} label={`${outletLabels[field]} condition`} value={row[field]} readOnly={readOnly} onChange={(value) => updateOutlet(row.rowUuid, { [field]: value })} />)}</div><div className="riser-outlet-table__remarks" role="cell"><RemarksField label="Remarks" definition={remarks} value={row.remarks} readOnly={readOnly} onChange={(value) => updateOutlet(row.rowUuid, { remarks: value })} />{row.source === "technician" ? <button type="button" className="secondary-command" onClick={() => setResponses((current) => ({ ...current, riserOutlets: current.riserOutlets.filter((candidate) => candidate.rowUuid !== row.rowUuid).map((candidate, position) => ({ ...candidate, sortOrder: position + 1 })) }))}>Remove outlet</button> : null}</div></section>)}</div>{!readOnly ? <button type="button" className="secondary-command" onClick={add}>Add Riser Outlet</button> : null}</fieldset>
    <fieldset disabled={readOnly}><legend>Comments</legend><textarea value={responses.comments} onChange={(event) => setResponses((current) => ({ ...current, comments: event.target.value }))} /></fieldset>
    {!readOnly ? <div className="form-actions sticky-form-actions"><button type="button" onClick={() => void onSaveDraft(responses).then(() => setMessage("Saved on this device.")).catch((error) => setMessage(error.message))}>Save Draft</button><button type="button" onClick={() => { setShow(true); if (!submitIssues(record, responses, photos).length) void onSubmitLocal(responses).catch((error) => setMessage(error.message)); }}>Submit Inspection</button></div> : null}
  </section>;
}
