import type { RiserResult, RiserRow } from "./dryWetRiserTypes";
import type { ServerDryWetRiserDetail } from "./serverDryWetRiserApi";
import { formatClientDateTime } from "../uiPresentation";

type Props = { inspection: ServerDryWetRiserDetail; onBack: () => void };
const waterTank = ["saj_main_water_supply", "water_level", "automatic_refilling_facilities", "drain_and_stop_valve_positions"];
const pumpHouse = ["pump_house_clean", "manual_start_pumps", "jockey_pump_pressure", "duty_pump_cut_in", "standby_pump_cut_in", "standby_pump_service_items", "battery_charging_alternator", "battery_charger_failure_alarm", "battery_serviceable", "pump_phase_failure_alarm", "pumps_auto_start", "test_and_gate_valve_positions"];
const label = (value: RiserResult | null) => value === "good" ? "Good" : value === "poor" ? "Poor" : "Not recorded";
const names: Record<string, string> = { saj_main_water_supply: "SAJ Main Water Supply", water_level: "Water Level", automatic_refilling_facilities: "Automatic Refilling Facilities", drain_and_stop_valve_positions: "Drain and Stop Valve Positions", pump_house_clean: "Pump House Cleanliness", manual_start_pumps: "Manual Start Pumps", jockey_pump_pressure: "Jockey Pump Pressure", duty_pump_cut_in: "Duty Pump Cut-In", standby_pump_cut_in: "Standby Pump Cut-In", standby_pump_service_items: "Standby Pump Service Items", battery_charging_alternator: "Battery Charging Alternator", battery_charger_failure_alarm: "Battery Charger Failure Alarm", battery_serviceable: "Battery Serviceable", pump_phase_failure_alarm: "Pump Phase Failure Alarm", pumps_auto_start: "Pumps Auto Start", test_and_gate_valve_positions: "Test and Gate Valve Positions" };
const name = (value: string) => names[value] ?? value;

export function ServerDryWetRiserView({ inspection, onBack }: Props) {
  const checklist = (keys: string[], source: Record<string, RiserRow>) => keys.map((key) => <section className="hose-check-row" key={key}><strong>{name(key)}</strong><span>{label(source[key].result)}</span><p>{source[key].remarks || "No remarks"}</p></section>);
  return <section className="hose-reel-form server-inspection-detail" aria-labelledby="server-riser-title">
    <button type="button" className="secondary-command" onClick={onBack}>Back to Systems</button>
    <header className="inspection-context"><div><p className="eyebrow">{inspection.jobReference}</p><h2 id="server-riser-title">{inspection.systemLabel}</h2><p><strong>{inspection.customer.displayName}</strong></p><p>{inspection.jobTitle}</p></div><strong className="inspection-status status-synced">Inspection Complete</strong></header>
    <p className="success-message">Submitted {formatClientDateTime(inspection.performedAt)} · Synced by {inspection.syncedByUsername}</p>
    <section><h3>Riser Type</h3><p><strong>{inspection.systemConfiguration.riserMode === "dry" ? "Dry Riser System" : "Wet Riser System"}</strong></p><p className="field-help">Frozen with this historical service visit.</p></section>
    <section><h3>Water Tank</h3>{checklist(waterTank, inspection.responses.waterTank)}</section>
    <section><h3>Pump House</h3>{checklist(pumpHouse, inspection.responses.pumpHouse)}</section>
    <section><h3>PSI Measurements</h3>{[["Jockey Cut In", inspection.responses.measurements.jockeyCutIn], ["Jockey Cut Out", inspection.responses.measurements.jockeyCutOut], ["Duty Pump Cut In", inspection.responses.measurements.dutyCutIn], ["Stand-by Pump Cut In", inspection.responses.measurements.standbyCutIn]].map(([title, value]) => <section className="measurement-card" key={title as string}><strong>{title}</strong><p>{value} PSI</p></section>)}</section>
    <section><h3>Riser Outlet</h3><div className="riser-outlet-table riser-outlet-table--readonly" role="table" aria-label="Accepted riser outlet inspection rows"><div className="riser-outlet-table__header" role="row"><span role="columnheader">Outlet</span><span role="columnheader">Reference &amp; location</span><span role="columnheader">Inspection results</span><span role="columnheader">Remarks</span></div>{[...inspection.responses.riserOutlets].sort((left, right) => left.sortOrder - right.sortOrder).map((row, index) => <section className="riser-outlet-table__row" role="row" key={row.rowUuid}><div className="riser-outlet-table__identity" role="cell"><strong>Outlet {index + 1}</strong><small>{row.source === "configured" ? "Configured" : "Added by technician"}</small></div><div className="riser-outlet-table__location" role="cell"><p><span>Reference</span>{row.assetReference || "Not recorded"}</p><p><span>Location</span>{row.locationText}</p></div><div className="riser-outlet-table__results" role="cell"><p><span>Canvas Hose ×2</span>{label(row.canvasHoseAt2Result)}</p><p><span>Diffuser Nozzle</span>{label(row.diffuserNozzleResult)}</p><p><span>Landing Valve</span>{label(row.landingValveResult)}</p><p><span>Crandle</span>{label(row.crandleResult)}</p><p><span>Door</span>{label(row.doorResult)}</p></div><div className="riser-outlet-table__remarks" role="cell"><p>{row.remarks || "No remarks"}</p></div></section>)}</div></section>
    <section><h3>Comments</h3><p>{inspection.responses.comments || "No comments"}</p></section>
  </section>;
}
