import { useEffect, useState } from "react";
import { ResultSelector } from "../inspectionControls/ResultSelector";
import { RemarksField } from "../inspectionControls/RemarksField";
import { SmokeVentilationV7EvidenceField } from "./SmokeVentilationV7EvidenceField";
import { submitIssues } from "./smokeVentilationRepository";
import { smokeVentilationChecklistFields, smokeVentilationRowColumns, type SmokeVentilationInspectionRecord, type SmokeVentilationResponses, type SmokeVentilationResult } from "./smokeVentilationTypes";
import { isSmokeVentilationV7EvidenceFinding, listSmokeVentilationV7Photos, resolveSmokeVentilationChecklistDefinitions, resolveSmokeVentilationRowResultDefinitions, type SmokeVentilationV7FieldPath } from "./smokeVentilationV7Evidence";

const remarks = { policy: "optional" as const, maxLength: 2000 };

export function SmokeVentilationInspectionForm({ record, onBack, onSaveDraft, onSubmitLocal, onEditFailed }: { record: SmokeVentilationInspectionRecord; onBack: () => void; onSaveDraft: (responses: SmokeVentilationResponses) => Promise<void>; onSubmitLocal: (responses: SmokeVentilationResponses) => Promise<void>; onEditFailed: () => Promise<void> }) {
  const [responses, setResponses] = useState(record.responses); const [message, setMessage] = useState(""); const [show, setShow] = useState(false); const [photos, setPhotos] = useState<Awaited<ReturnType<typeof listSmokeVentilationV7Photos>>>([]);
  const checklistDefinitions = resolveSmokeVentilationChecklistDefinitions(record.inspectionSnapshot.system.definition);
  const rowDefinitions = resolveSmokeVentilationRowResultDefinitions(record.inspectionSnapshot.system.definition);
  useEffect(() => setResponses(record.responses), [record]);
  useEffect(() => { void listSmokeVentilationV7Photos(record.clientUuid).then(setPhotos); }, [record.clientUuid, record.localUpdatedAt]);
  const readOnly = record.syncStatus !== "Draft";
  const issues = show ? submitIssues(record, responses, photos) : [];
  const updateChecklist = (key: keyof SmokeVentilationResponses["checklist"], change: Partial<SmokeVentilationResponses["checklist"][typeof key]>) => setResponses((current) => ({ ...current, checklist: { ...current.checklist, [key]: { ...current.checklist[key], ...change } } }));
  const updateRow = (id: string, change: Partial<SmokeVentilationResponses["rows"][number]>) => setResponses((current) => ({ ...current, rows: current.rows.map((row) => row.rowUuid === id ? { ...row, ...change } : row) }));
  const addRow = () => setResponses((current) => ({ ...current, rows: [...current.rows, { rowUuid: crypto.randomUUID(), source: "technician", configuredLocationId: null, configuredRowOrdinal: null, zoneSnapshot: null, locationSnapshot: null, assetReference: "", autoResult: null, manualResult: null, remarks: "", fieldRemarks: {}, sortOrder: current.rows.length + 1 }] }));
  const evidenceFor = (fieldPath: string) => photos.find((photo) => photo.fieldPath === fieldPath);
  const refreshPhotos = async () => setPhotos(await listSmokeVentilationV7Photos(record.clientUuid));
  return <section className="hose-reel-form" aria-labelledby="smoke-ventilation-title"><button type="button" className="secondary-command" onClick={onBack}>Back to Systems</button><header className="inspection-context"><div><p className="eyebrow">{record.inspectionSnapshot.job.reference}</p><h2 id="smoke-ventilation-title">Smoke Ventilation System</h2><p><strong>{record.inspectionSnapshot.customer.displayName}</strong></p><p>{record.inspectionSnapshot.job.title}</p></div><strong>{record.syncStatus === "Synced" ? "Inspection Complete" : record.syncStatus === "Pending" ? "Waiting to Sync" : record.syncStatus === "Failed" || record.syncStatus === "Conflict" ? "Needs Attention" : record.syncStatus === "Syncing" ? "Syncing…" : record.syncStatus}</strong></header>{record.lastSyncError ? <p className="error-text">{record.lastSyncError}</p> : null}{message ? <p className="form-message">{message}</p> : null}{show && issues.length ? <section className="validation-summary" role="alert"><h3>Cannot submit yet</h3><ul>{issues.map((issue, index) => <li key={index}>{issue}</li>)}</ul></section> : null}{["Failed", "Conflict"].includes(record.syncStatus) ? <button type="button" onClick={() => void onEditFailed()}>Edit Failed Inspection</button> : null}
    <fieldset disabled={readOnly}><legend>Control Panel</legend>
      <label>Smoke Ventilation Control Panel No.<input maxLength={200} value={responses.controlPanelNo} onChange={(event) => setResponses((current) => ({ ...current, controlPanelNo: event.target.value }))} /></label>
      <label>Location<input maxLength={300} value={responses.location} onChange={(event) => setResponses((current) => ({ ...current, location: event.target.value }))} /></label>
      <label>Date Tested<input maxLength={200} value={responses.dateTested} onChange={(event) => setResponses((current) => ({ ...current, dateTested: event.target.value }))} /></label>
    </fieldset>
    <fieldset disabled={readOnly}><legend>Fan Schedule</legend>{responses.rows.map((row, index) => { const configured = row.source === "configured"; return <section className="hose-row-card" key={row.rowUuid}><h4>Fan {index + 1}</h4><label>No.<input value={row.assetReference} disabled={readOnly || configured} onChange={(event) => updateRow(row.rowUuid, { assetReference: event.target.value })} /></label>{smokeVentilationRowColumns.map(([field, wireKey, label]) => { const definition = rowDefinitions?.[field]; const result = row[field] as SmokeVentilationResult | null; const finding = isSmokeVentilationV7EvidenceFinding(result); const fieldPath = `fan_schedule.fan_schedule_rows.rows.${row.rowUuid}.${wireKey}` as SmokeVentilationV7FieldPath; return <div className="hose-component" key={field}><strong>{label}</strong>{definition ? <ResultSelector<SmokeVentilationResult> definition={definition} label={`${label} result`} value={result} readOnly={readOnly} onChange={(value) => updateRow(row.rowUuid, { [field]: value })} /> : <p className="error-text">Smoke Ventilation V7 definition is unavailable.</p>}{finding ? <section><RemarksField label={`${label} Remark *`} definition={remarks} value={row.fieldRemarks?.[field] ?? ""} readOnly={readOnly} onChange={(value) => updateRow(row.rowUuid, { fieldRemarks: { ...row.fieldRemarks, [field]: value } })} /><SmokeVentilationV7EvidenceField record={record} fieldPath={fieldPath} attachment={evidenceFor(fieldPath)} onChanged={refreshPhotos} /></section> : null}</div>; })}<RemarksField label="Remarks" definition={remarks} value={row.remarks} readOnly={readOnly} onChange={(value) => updateRow(row.rowUuid, { remarks: value })} />{!readOnly && row.source === "technician" ? <button type="button" className="secondary-command" onClick={() => setResponses((current) => ({ ...current, rows: current.rows.filter((candidate) => candidate.rowUuid !== row.rowUuid).map((candidate, rowIndex) => ({ ...candidate, sortOrder: rowIndex + 1 })) }))}>Remove Row</button> : null}</section>; })}{!readOnly ? <button type="button" className="secondary-command" onClick={addRow}>Add Row</button> : null}</fieldset>
    {(["Power Supply", "Charger & Batteries", "Main Function Key"] as const).map((title) => <fieldset disabled={readOnly} key={title}><legend>{title}</legend>{smokeVentilationChecklistFields.filter(([key]) => title === "Power Supply" ? key.startsWith("main_power") || key.startsWith("secondary_essential") : title === "Charger & Batteries" ? key.startsWith("cb_") : key.startsWith("mfk_")).map(([key, label]) => { const definition = checklistDefinitions?.[key]; const entry = responses.checklist[key]; const finding = isSmokeVentilationV7EvidenceFinding(entry?.result); const fieldPath = `smoke_ventilation_checks.${key}` as SmokeVentilationV7FieldPath; return <section className="hose-check-row" key={key}><strong>{label}</strong>{definition ? <ResultSelector<SmokeVentilationResult> definition={definition} label={`${label} result`} value={entry?.result ?? null} readOnly={readOnly} onChange={(result) => updateChecklist(key, { result })} /> : <p className="error-text">Smoke Ventilation V7 definition is unavailable.</p>}<RemarksField label="Remarks" definition={remarks} value={entry?.remarks ?? ""} readOnly={readOnly} onChange={(remarks) => updateChecklist(key, { remarks })} />{finding ? <SmokeVentilationV7EvidenceField record={record} fieldPath={fieldPath} attachment={evidenceFor(fieldPath)} onChanged={refreshPhotos} /> : null}</section>; })}</fieldset>)}
    <fieldset disabled={readOnly}><legend>Comments</legend><RemarksField label="Comments" definition={{ policy: "optional", maxLength: 4000 }} value={responses.comments} readOnly={readOnly} onChange={(comments) => setResponses((current) => ({ ...current, comments }))} /></fieldset>
    {!readOnly ? <div className="form-actions sticky-form-actions"><button type="button" className="secondary-command" onClick={() => void onSaveDraft(responses).then(() => setMessage("Draft saved on this device.")).catch((error) => setMessage(error.message))}>Save Draft</button><button type="button" onClick={() => { setShow(true); if (!submitIssues(record, responses, photos).length) void onSubmitLocal(responses).catch((error) => setMessage(error.message)); }}>Submit Inspection</button></div> : null}
  </section>;
}
