import { localDatabase, type SyncOutboxItem } from "../db/localDatabase";
import type { InspectionCatalog } from "../referenceData/referenceDataTypes";
import { compatibleCatalogSystem } from "../referenceData/systemContractCompatibility";
import type { InspectionJob, JobSystemSnapshot } from "../jobs/jobTypes";
import type { DeviceReportedCreator } from "../hoseReel/hoseReelTypes";
import type { HydrantInspectionRecord, HydrantResponses, HydrantRow } from "./hydrantTypes";
const key="hydrant" as const; const now=()=>new Date().toISOString();
const fields=["canvasHose1Result","canvasHose2Result","diffuserNozzleResult","landingValveResult","landingValveHandleResult","hoseCabinetResult","keyLockResult"] as const;
function configured(system:JobSystemSnapshot):HydrantRow[]{let n=0;return system.locations.flatMap(l=>Array.from({length:l.presetRowCount},(_,i)=>({rowUuid:crypto.randomUUID(),source:"configured" as const,configuredLocationId:l.id,configuredRowOrdinal:i+1,zoneSnapshot:system.zones.find(z=>z.id===l.zoneId)?{id:l.zoneId!,displayName:system.zones.find(z=>z.id===l.zoneId)!.displayName}:null,locationSnapshot:{id:l.id,displayName:l.displayName},assetReference:typeof l.rowPreset==="object"&&l.rowPreset&&"assetReference" in l.rowPreset&&typeof l.rowPreset.assetReference==="string"?l.rowPreset.assetReference:"",locationText:l.displayName,canvasHose1Result:null,canvasHose2Result:null,diffuserNozzleResult:null,landingValveResult:null,landingValveHandleResult:null,hoseCabinetResult:null,keyLockResult:null,remarks:"",sortOrder:++n})));}
export async function getOrCreateHydrantInspection(job:InspectionJob,system:JobSystemSnapshot,catalog:InspectionCatalog,creator:{id:number;username:string;role:"admin"|"inspector"}|undefined){const jobSystemKey=`${job.id}:${key}`,existing=await localDatabase.masterSystemInspections.where("jobSystemKey").equals(jobSystemKey).first();if(existing){if(existing.systemKey!==key)throw new Error("Stored inspection identity is invalid");return existing as HydrantInspectionRecord;}const compatible=compatibleCatalogSystem(catalog,job.configurationSnapshot.template,key),definition=compatible?.system.definition;if(!definition||system.systemKey!==key)throw new Error("Cached compatible Hydrant definition is unavailable. Refresh jobs online first.");const t=now(),record:HydrantInspectionRecord={schemaVersion:1,clientUuid:crypto.randomUUID(),jobSystemKey,jobId:job.id,systemKey:key,instanceKey:"primary",configuredZoneId:null,configuredLocationId:null,displaySequence:1,originalCreatorSnapshot:creator?{source:"device_reported",userId:creator.id,username:creator.username,role:creator.role,capturedAt:t} as DeviceReportedCreator:null,masterTemplate:{id:job.configurationSnapshot.template.id,code:"MFE-FSSR",version:job.configurationSnapshot.template.version},configuration:job.configurationSnapshot.configuration,inspectionSnapshot:{schemaVersion:1,capturedAt:t,job:{id:job.id,reference:job.reference,title:job.title},customer:job.configurationSnapshot.customer,configuration:job.configurationSnapshot.configuration,template:job.configurationSnapshot.template,system:{...system,definition,repetitionMode:"single_with_repeatable_rows"}},responses:{schemaVersion:1,hydrantType:null,rows:configured(system),comments:""},performedAt:t,localCreatedAt:t,localUpdatedAt:t,syncStatus:"Draft"};await localDatabase.masterSystemInspections.add(record);return record;}
export function submitIssues(record:HydrantInspectionRecord,r:HydrantResponses){const issues:string[]=[];if(!["pressurize","meter","public"].includes(r.hydrantType??""))issues.push("Hydrant Type is required");const expected=record.inspectionSnapshot.system.locations.flatMap(l=>Array.from({length:l.presetRowCount},(_,i)=>`${l.id}:${i+1}`));const seen=new Set<string>();if(!r.rows.length)issues.push("At least one Hydrant Location is required");r.rows.forEach((x,i)=>{if(!x.rowUuid||x.sortOrder!==i+1||!x.locationText||x.locationText.length>300||x.assetReference.length>200||x.remarks.length>2000)issues.push("Hydrant Location row is invalid");if(!fields.every(f=>x[f]==="good"||x[f]==="poor"))issues.push("Every Hydrant Location result is required");if(x.source==="configured"){const id=`${x.configuredLocationId}:${x.configuredRowOrdinal}`;if(!expected.includes(id)||seen.has(id))issues.push("Configured Hydrant row identity is invalid");seen.add(id);}else if(x.configuredLocationId!==null||x.configuredRowOrdinal!==null)issues.push("Technician Hydrant row provenance is invalid");});if(seen.size!==expected.length)issues.push("Configured Hydrant rows must be retained");if(r.comments.length>4000)issues.push("Comments exceed 4000 characters");return issues;}
const payload=(r:HydrantInspectionRecord)=>({clientUuid:r.clientUuid,jobId:r.jobId,systemKey:r.systemKey,instanceKey:r.instanceKey,configuredZoneId:null,configuredLocationId:null,displaySequence:1,originalCreatorSnapshot:r.originalCreatorSnapshot,masterTemplate:r.masterTemplate,configuration:r.configuration,inspectionSnapshot:r.inspectionSnapshot,responses:r.responses,performedAt:r.performedAt});
async function write(record:HydrantInspectionRecord,responses:HydrantResponses,submit:boolean){let out:HydrantInspectionRecord|undefined;await localDatabase.transaction("rw",localDatabase.masterSystemInspections,localDatabase.syncOutbox,async()=>{const live=await localDatabase.masterSystemInspections.get(record.clientUuid) as HydrantInspectionRecord|undefined;if(!live||live.systemKey!==key||live.syncStatus!=="Draft"||live.localUpdatedAt!==record.localUpdatedAt)throw new Error("This Hydrant record changed elsewhere. Reload before continuing.");if(submit&&submitIssues(live,responses).length)throw new Error("Complete required Hydrant fields");out={...live,responses,syncStatus:submit?"Pending":"Draft",performedAt:submit?now():live.performedAt,localUpdatedAt:now(),lastSyncError:undefined};await localDatabase.masterSystemInspections.put(out);if(submit){const activeKey=`masterSystemInspection:create:${live.clientUuid}`,old=await localDatabase.syncOutbox.where("activeKey").equals(activeKey).first(),item:SyncOutboxItem={operationId:old?.operationId??crypto.randomUUID(),entityType:"masterSystemInspection",entityId:live.clientUuid,action:"create",payload:payload(out),createdAt:out.localCreatedAt,attempts:old?.attempts??0,status:"Pending",activeKey};if(old)await localDatabase.syncOutbox.put(item);else await localDatabase.syncOutbox.add(item);}});return out!;}
export const saveHydrantDraft=(r:HydrantInspectionRecord,x:HydrantResponses)=>write(r,x,false);export const submitLocalHydrant=(r:HydrantInspectionRecord,x:HydrantResponses)=>write(r,x,true);
export async function returnFailedHydrantToDraft(r:HydrantInspectionRecord){const live=await localDatabase.masterSystemInspections.get(r.clientUuid) as HydrantInspectionRecord|undefined;if(!live||!["Failed","Conflict"].includes(live.syncStatus))throw new Error("This Hydrant record changed elsewhere.");const out={...live,syncStatus:"Draft" as const,localUpdatedAt:now(),lastSyncError:undefined};await localDatabase.masterSystemInspections.put(out);return out;}
