import { useEffect, useState } from "react";
import { inspectionSyncMessage } from "../uiPresentation";
import {
  addFireAlarmPrimaryTechnicianRow,
  addFireAlarmSecondaryTechnicianRow,
  removeFireAlarmPrimaryTechnicianRow,
  removeFireAlarmSecondaryTechnicianRow
} from "./fireAlarmRepository";
import { resolveFireAlarmVisibleLabels } from "./fireAlarmDefinition";
import type { DeviceState, FireAlarmInspectionRecord, FireAlarmResponses, GoodPoor } from "./fireAlarmTypes";
import { canonicalizeFireAlarmResponses, fireAlarmChargerKeys, fireAlarmFunctionKeys, getFireAlarmSubmissionIssues } from "./fireAlarmValidation";
import { FireAlarmV6EvidenceField } from "./FireAlarmV6EvidenceField";
import { listFireAlarmV6Photos, type FireAlarmV6FieldPath, v6SubmissionIssues } from "./fireAlarmV6Evidence";
import { FireAlarmV7EvidenceField } from "./FireAlarmV7EvidenceField";
import { listFireAlarmV7Photos, type FireAlarmV7FieldPath, v7FireAlarmSubmissionIssues } from "./fireAlarmV7Evidence";
import { fireAlarmClientDispatch } from "../referenceData/systemContractCompatibility";
import { MultiResultSelector } from "../inspectionControls/MultiResultSelector";
import { RemarksField } from "../inspectionControls/RemarksField";

type Props = { record: FireAlarmInspectionRecord; onBack: () => void; onSaveDraft: (responses: FireAlarmResponses) => Promise<void>; onSubmitLocal: (responses: FireAlarmResponses) => Promise<void>; onEditFailed: () => Promise<void>; onRecordChange?: (record: FireAlarmInspectionRecord) => void };
const labels: Record<string, string> = { main_supply: "Main Supply", battery: "Battery", charger: "Charger", main_alarm_reset: "Main Alarm Reset", lamp_test: "Lamp Test", evacuate: "Evacuate", ac_supply: "A/C Supply", dc_supply: "D/C Supply", spka_system: "SPKA System", alarm_lift_trip: "Alarm Lift Trip", signal_gas_discharge: "Signal Gas Discharge" };
const deviceOptions: Array<[DeviceState, string]> = [["normal", "Normal"], ["test", "Test"], ["isolation", "Isolation"]];
const goodPoorOptions: Array<[GoodPoor, string]> = [["good", "Good"], ["poor", "Poor"]];
const goodPoorV6Options: Array<[GoodPoor, string]> = [["good", "Good"], ["poor", "Poor"], ["not_relevant", "Not Relevant"]];
const isV7EvidenceFinding = (value: unknown) => value === "not_good" || value === "complete_repair";

function Select<T extends string>({ label, value, options, onChange, disabled = false }: { label: string; value: T | null; options: Array<[T, string]>; onChange: (value: T | null) => void; disabled?: boolean }) {
  return <label>{label}<select aria-label={label} value={value ?? ""} disabled={disabled} onChange={(event) => onChange(event.target.value === "" ? null : event.target.value as T)}><option value="">Select</option>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>;
}

export function FireAlarmInspectionForm({ record, onBack, onSaveDraft, onSubmitLocal, onEditFailed, onRecordChange }: Props) {
  const [responses, setResponses] = useState(record.responses); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [issues, setIssues] = useState<ReturnType<typeof getFireAlarmSubmissionIssues>>([]); const [photos, setPhotos] = useState<Awaited<ReturnType<typeof listFireAlarmV6Photos>>>([]);
  const isV6 = fireAlarmClientDispatch(record.masterTemplate) === "v6";
  const isV7 = fireAlarmClientDispatch(record.masterTemplate) === "v7";
  const usesV7Evidence = isV7;
  const usesEvidence = isV6 || isV7;
  const v7Options = (options: Array<{ value: GoodPoor; label: string }>): Array<[GoodPoor, string]> => options.map((option) => [option.value, option.label]);
  const chargerOptions = (key: string) => isV7
    ? v7Options(record.inspectionSnapshot.system.resolvedControls.chargerAndBatteries.find((item) => item.key === key)!.result.options)
    : usesEvidence ? goodPoorV6Options : goodPoorOptions;
  const functionOptions = (key: string) => isV7
    ? v7Options(record.inspectionSnapshot.system.resolvedControls.mainFunctionKeys.find((item) => item.key === key)!.result.options)
    : usesEvidence ? goodPoorV6Options : goodPoorOptions;
  const secondaryOptions = (key: "alarmBell" | "manualCallPoint") => isV7
    ? v7Options(record.inspectionSnapshot.system.resolvedControls.secondaryAlarmDeviceRows[key].options)
    : usesEvidence ? goodPoorV6Options : goodPoorOptions;
  const visibleLabels = resolveFireAlarmVisibleLabels(record.inspectionSnapshot.system.definition, isV7 ? 7 : isV6 ? 6 : 3);
  useEffect(() => { setResponses(record.responses); setError(""); if (isV6) void listFireAlarmV6Photos(record.clientUuid).then(setPhotos); else if (isV7) void listFireAlarmV7Photos(record.clientUuid).then(setPhotos); else setPhotos([]); }, [record, isV6, isV7]);
  const editable = record.syncStatus === "Draft";
  const primary = (rowUuid: string, change: object) => setResponses((current) => ({ ...current, primaryDeviceRows: current.primaryDeviceRows.map((row) => row.rowUuid === rowUuid ? { ...row, ...change } : row) }));
  const secondary = (rowUuid: string, change: object) => setResponses((current) => ({ ...current, secondaryAlarmDeviceRows: current.secondaryAlarmDeviceRows.map((row) => row.rowUuid === rowUuid ? { ...row, ...change } : row) }));
  async function save() { setMessage(""); setError(""); try { const canonical = usesEvidence ? structuredClone(responses) : canonicalizeFireAlarmResponses(responses, record.inspectionSnapshot); await onSaveDraft(canonical); setMessage(inspectionSyncMessage("Draft")); } catch (reason) { setError(reason instanceof Error ? reason.message : "Fire Alarm Draft could not be saved"); } }
  const evidenceFor = (fieldPath: string) => photos.find((photo) => photo.fieldPath === fieldPath);
  const refreshPhotos = async () => setPhotos(isV7 ? await listFireAlarmV7Photos(record.clientUuid) : await listFireAlarmV6Photos(record.clientUuid));
  async function submit() { setMessage(""); setError(""); const currentIssues = isV6 ? v6SubmissionIssues(responses, photos).map((message) => ({ section: "Evidence", message })) : isV7 ? v7FireAlarmSubmissionIssues(responses, photos, record.inspectionSnapshot.system.resolvedControls).map((message) => ({ section: "Evidence", message })) : getFireAlarmSubmissionIssues(responses, record.inspectionSnapshot); setIssues(currentIssues); if (currentIssues.length) return; try { await onSubmitLocal(responses); setMessage(inspectionSyncMessage("Pending")); } catch (reason) { setError(reason instanceof Error ? reason.message : "Fire Alarm inspection could not be submitted locally"); } }
  return <section className="fire-alarm-form hose-reel-form" aria-labelledby="fire-alarm-title">
    <button type="button" className="secondary-command" onClick={onBack}>Back to Systems</button>
    <header className="inspection-context"><div><p className="eyebrow">{record.inspectionSnapshot.job.reference}</p><h2 id="fire-alarm-title">Fire Alarm / Detector System</h2><p><strong>{record.inspectionSnapshot.customer.displayName}</strong></p><p>{record.inspectionSnapshot.job.title}</p></div><strong role="status">{inspectionSyncMessage(record.syncStatus)}</strong></header>
    {message ? <p className="success-message" role="status">{message}</p> : null}{record.lastSyncError ? <p className="error-text">{record.lastSyncError}</p> : null}{error ? <section className="validation-summary" role="alert"><h3>Fire Alarm action failed</h3><p>{error}</p></section> : null}
    {issues.length ? <section className="validation-summary" role="alert"><h3>Cannot submit yet</h3><ul>{issues.map((issue, index) => <li key={`${issue.section}-${index}`}>{issue.message}</li>)}</ul></section> : null}
    {record.syncStatus === "Failed" || record.syncStatus === "Conflict" ? <button type="button" onClick={() => void onEditFailed().catch((reason) => setError(reason instanceof Error ? reason.message : "Fire Alarm inspection could not be corrected"))}>Edit Failed Inspection</button> : null}
    <fieldset disabled={!editable}><legend>Control Panel Location</legend><label htmlFor="fire-alarm-control-panel">Control Panel Location<input id="fire-alarm-control-panel" maxLength={300} value={responses.controlPanelLocation} onChange={(event) => setResponses({ ...responses, controlPanelLocation: event.target.value })} /></label></fieldset>
    <fieldset disabled={!editable}><legend>{visibleLabels.primaryRows}</legend>
      {responses.primaryDeviceRows.map((row, index) => <section className="fire-alarm-row" id={`fire-alarm-primary-${row.rowUuid}`} key={row.rowUuid}><div className="fire-alarm-row-heading"><strong>Primary row {index + 1}</strong><span>{row.source === "configured" ? "Configured" : "Technician"}</span></div>
        <label>{visibleLabels.assetReference}<input maxLength={250} readOnly={row.source === "configured"} value={row.assetReference} onChange={(event) => primary(row.rowUuid, { assetReference: event.target.value })} /></label>
        <label>Alarm Zone<input maxLength={200} readOnly={row.source === "configured"} value={row.alarmZone} onChange={(event) => primary(row.rowUuid, { alarmZone: event.target.value })} /></label>
        <label>Location<input maxLength={300} readOnly={row.source === "configured"} value={row.location} onChange={(event) => primary(row.rowUuid, { location: event.target.value })} /></label>
        <div className="fire-alarm-results">{isV7 ? <><div><strong>Manual Call Point</strong><MultiResultSelector label="Manual Call Point" definition={record.inspectionSnapshot.system.resolvedControls.primaryDeviceRows.manualCallPoint} value={Array.isArray(row.manualCallPoint) ? row.manualCallPoint : null} readOnly={!editable} onChange={(value) => primary(row.rowUuid, { manualCallPoint: value })} /></div><div><strong>Flow Switch</strong><MultiResultSelector label="Flow Switch" definition={record.inspectionSnapshot.system.resolvedControls.primaryDeviceRows.flowSwitch} value={Array.isArray(row.flowSwitch) ? row.flowSwitch : null} readOnly={!editable} onChange={(value) => primary(row.rowUuid, { flowSwitch: value })} /></div><div><strong>Heat Detector</strong><MultiResultSelector label="Heat Detector" definition={record.inspectionSnapshot.system.resolvedControls.primaryDeviceRows.heatDetector} value={Array.isArray(row.heatDetector) ? row.heatDetector : null} readOnly={!editable} onChange={(value) => primary(row.rowUuid, { heatDetector: value })} /></div><div><strong>Smoke Detector</strong><MultiResultSelector label="Smoke Detector" definition={record.inspectionSnapshot.system.resolvedControls.primaryDeviceRows.smokeDetector} value={Array.isArray(row.smokeDetector) ? row.smokeDetector : null} readOnly={!editable} onChange={(value) => primary(row.rowUuid, { smokeDetector: value })} /></div></> : <><Select label="Manual Call Point" value={row.manualCallPoint as DeviceState | null} options={deviceOptions} onChange={(value) => primary(row.rowUuid, { manualCallPoint: value })} /><Select label="Flow Switch" value={row.flowSwitch as DeviceState | null} options={deviceOptions} onChange={(value) => primary(row.rowUuid, { flowSwitch: value })} /><Select label="Heat Detector" value={row.heatDetector as DeviceState | null} options={deviceOptions} onChange={(value) => primary(row.rowUuid, { heatDetector: value })} /><Select label="Smoke Detector" value={row.smokeDetector as DeviceState | null} options={deviceOptions} onChange={(value) => primary(row.rowUuid, { smokeDetector: value })} /></>}</div>
        <RemarksField systemKey="fire_alarm_detector" label="Remarks" definition={{ policy: "optional", maxLength: 2000 }} value={row.remarks} readOnly={!editable} onChange={(remarks) => primary(row.rowUuid, { remarks })} />
        {row.source === "technician" ? <button type="button" className="secondary-command" onClick={() => { void removeFireAlarmPrimaryTechnicianRow(record, responses, row.rowUuid).then((saved) => { setResponses(saved.responses); onRecordChange?.(saved); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Row could not be removed")); }}>Remove primary row</button> : null}
      </section>)}
      {editable ? <button type="button" className="secondary-command" onClick={() => { void addFireAlarmPrimaryTechnicianRow(record, responses).then((saved) => { setResponses(saved.responses); onRecordChange?.(saved); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Row could not be added")); }}>Add primary row</button> : null}
    </fieldset>
    <fieldset disabled={!editable}><legend>Charger &amp; Batteries</legend>{fireAlarmChargerKeys.map((key) => { const path = `charger_batteries.charger_battery_checks.${key}`; const field = responses.chargerAndBatteries[key]; return <section className="fire-alarm-check" id={`fire-alarm-charger-${key}`} key={key}><strong>{labels[key]}</strong><Select label={`${labels[key]} result`} value={field.result} options={chargerOptions(key)} onChange={(result) => setResponses({ ...responses, chargerAndBatteries: { ...responses.chargerAndBatteries, [key]: { ...field, result } } })} /><RemarksField systemKey="fire_alarm_detector" label={(isV6 && field.result === "poor") || (usesV7Evidence && isV7EvidenceFinding(field.result)) ? "Remark *" : "Remarks"} definition={{ policy: "optional", maxLength: 2000 }} value={field.remarks} readOnly={!editable} onChange={(remarks) => setResponses({ ...responses, chargerAndBatteries: { ...responses.chargerAndBatteries, [key]: { ...field, remarks } } })} />{field.result === "poor" && isV6 ? <FireAlarmV6EvidenceField record={record} fieldPath={path as FireAlarmV6FieldPath} attachment={evidenceFor(path as FireAlarmV6FieldPath)} onChanged={refreshPhotos} /> : usesV7Evidence && isV7EvidenceFinding(field.result) ? <FireAlarmV7EvidenceField record={record} fieldPath={path as FireAlarmV7FieldPath} attachment={evidenceFor(path as FireAlarmV6FieldPath)} onChanged={refreshPhotos} /> : null}</section>; })}</fieldset>
    <fieldset disabled={!editable}><legend>Main Function Key</legend>{fireAlarmFunctionKeys.map((key) => { const path = `main_function_key.function_checks.${key}`; const field = responses.mainFunctionKeys[key]; return <section className="fire-alarm-check" id={`fire-alarm-function-${key}`} key={key}><strong>{labels[key]}</strong><Select label={`${labels[key]} result`} value={field.result} options={functionOptions(key)} onChange={(result) => setResponses({ ...responses, mainFunctionKeys: { ...responses.mainFunctionKeys, [key]: { ...field, result } } })} /><RemarksField systemKey="fire_alarm_detector" label={(isV6 && field.result === "poor") || (usesV7Evidence && isV7EvidenceFinding(field.result)) ? "Remark *" : "Remarks"} definition={{ policy: "optional", maxLength: 2000 }} value={field.remarks} readOnly={!editable} onChange={(remarks) => setResponses({ ...responses, mainFunctionKeys: { ...responses.mainFunctionKeys, [key]: { ...field, remarks } } })} />{field.result === "poor" && isV6 ? <FireAlarmV6EvidenceField record={record} fieldPath={path as FireAlarmV6FieldPath} attachment={evidenceFor(path as FireAlarmV6FieldPath)} onChanged={refreshPhotos} /> : usesV7Evidence && isV7EvidenceFinding(field.result) ? <FireAlarmV7EvidenceField record={record} fieldPath={path as FireAlarmV7FieldPath} attachment={evidenceFor(path as FireAlarmV6FieldPath)} onChanged={refreshPhotos} /> : null}</section>; })}</fieldset>
    <fieldset disabled={!editable}><legend>{visibleLabels.secondaryRows}</legend>
      {responses.secondaryAlarmDeviceRows.map((row, index) => <section className="fire-alarm-row" id={`fire-alarm-secondary-${row.rowUuid}`} key={row.rowUuid}><div className="fire-alarm-row-heading"><strong>Secondary row {index + 1}</strong><span>{row.source === "configured" ? "Configured" : "Technician"}</span></div><label>{visibleLabels.assetReference}<input maxLength={250} readOnly={row.source === "configured"} value={row.assetReference} onChange={(event) => secondary(row.rowUuid, { assetReference: event.target.value })} /></label><label>Location<input maxLength={300} readOnly={row.source === "configured"} value={row.location} onChange={(event) => secondary(row.rowUuid, { location: event.target.value })} /></label><div className="fire-alarm-results"><Select label="Alarm Bell" value={row.alarmBell} options={secondaryOptions("alarmBell")} onChange={(value) => secondary(row.rowUuid, { alarmBell: value })} /><Select label="Manual Call Point" value={row.manualCallPoint} options={secondaryOptions("manualCallPoint")} onChange={(value) => secondary(row.rowUuid, { manualCallPoint: value })} /></div>{([ ["alarmBell", "alarm_bell", "Alarm Bell"], ["manualCallPoint", "manual_call_point", "Manual Call Point"] ] as const).map(([key, wire, label]) => { const path = `alarm_devices.alarm_device_rows.rows.${row.rowUuid}.${wire}`; return (isV6 && row[key] === "poor") || (usesV7Evidence && isV7EvidenceFinding(row[key])) ? <section key={key}><RemarksField systemKey="fire_alarm_detector" label={`${label} Remark *`} definition={{ policy: "optional", maxLength: 2000 }} value={row.fieldRemarks?.[key] ?? ""} readOnly={!editable} onChange={(remarks) => secondary(row.rowUuid, { fieldRemarks: { ...row.fieldRemarks, [key]: remarks } })} />{isV6 ? <FireAlarmV6EvidenceField record={record} fieldPath={path as FireAlarmV6FieldPath} attachment={evidenceFor(path as FireAlarmV6FieldPath)} onChanged={refreshPhotos} /> : <FireAlarmV7EvidenceField record={record} fieldPath={path as FireAlarmV7FieldPath} attachment={evidenceFor(path as FireAlarmV6FieldPath)} onChanged={refreshPhotos} />}</section> : null; })}<RemarksField systemKey="fire_alarm_detector" label="Remarks" definition={{ policy: "optional", maxLength: 2000 }} value={row.remarks} readOnly={!editable} onChange={(remarks) => secondary(row.rowUuid, { remarks })} />{row.source === "technician" ? <button type="button" className="secondary-command" onClick={() => { void removeFireAlarmSecondaryTechnicianRow(record, responses, row.rowUuid).then((saved) => { setResponses(saved.responses); onRecordChange?.(saved); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Row could not be removed")); }}>Remove secondary row</button> : null}</section>)}
      {editable ? <button type="button" className="secondary-command" onClick={() => { void addFireAlarmSecondaryTechnicianRow(record, responses).then((saved) => { setResponses(saved.responses); onRecordChange?.(saved); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Row could not be added")); }}>Add secondary row</button> : null}
    </fieldset>
    <fieldset disabled={!editable}><legend>{visibleLabels.comments}</legend><RemarksField systemKey="fire_alarm_detector" label={visibleLabels.comments} definition={{ policy: "optional", maxLength: 4000 }} value={responses.comments} readOnly={!editable} onChange={(comments) => setResponses({ ...responses, comments })} /></fieldset>
    {editable ? <div className="form-actions sticky-form-actions"><button type="button" className="secondary-command" onClick={() => void save()}>Save Draft</button><button type="button" onClick={() => void submit()}>Submit Inspection</button></div> : null}
  </section>;
}
