import type { ServerFireAlarmDetail } from "./fireAlarmTypes";
const labels:Record<string,string>={main_supply:"Main Supply",battery:"Battery",charger:"Charger",main_alarm_reset:"Main Alarm Reset",lamp_test:"Lamp Test",evacuate:"Evacuate",ac_supply:"A/C Supply",dc_supply:"D/C Supply",spka_system:"SPKA System",alarm_lift_trip:"Alarm Lift Trip",signal_gas_discharge:"Signal Gas Discharge"};
const result=(value:string)=>({normal:"Normal",test:"Test",isolation:"Isolation",good:"Good",poor:"Poor"}[value]??value);
const when=(value:string)=>new Date(value).toLocaleString();
export function FireAlarmAcceptedDetail({inspection,onBack}:{inspection:ServerFireAlarmDetail;onBack:()=>void}){const r=inspection.responses;return <section className="fire-alarm-form hose-reel-form server-inspection-detail" aria-labelledby="accepted-fire-alarm-title"><button type="button" className="secondary-command" onClick={onBack}>Back to Systems</button><header className="inspection-context"><div><p className="eyebrow">{inspection.jobReference}</p><h2 id="accepted-fire-alarm-title">{inspection.systemLabel}</h2><p>{inspection.jobTitle}</p><p>{inspection.customer.code} — {inspection.customer.displayName}</p></div><strong className="inspection-status status-synced">Inspection Complete</strong></header>
<dl className="server-detail-metadata"><div><dt>Performed</dt><dd>{when(inspection.performedAt)}</dd></div><div><dt>Received</dt><dd>{when(inspection.receivedAt)}</dd></div><div><dt>Device-reported creator</dt><dd>{inspection.deviceReportedCreatorUsername??"Not reported"}</dd></div><div><dt>Verified original creator</dt><dd>{inspection.verifiedOriginalCreatorUsername??"Not verified"}</dd></div><div><dt>Authenticated sync user</dt><dd>{inspection.syncedByUsername}</dd></div></dl>
<section><h3>Fire Alarm Control Panel Location</h3><p>{r.controlPanelLocation}</p></section><section><h3>Zone and Device Rows</h3><div className="server-detail-table-wrap"><table><thead><tr><th>No.</th><th>Alarm Zone</th><th>Location</th><th>Manual Call Point</th><th>Flow Switch</th><th>Heat Detector</th><th>Smoke Detector</th><th>Remarks</th></tr></thead><tbody>{r.primaryDeviceRows.map(x=><tr key={x.rowUuid}><td>{x.assetReference||x.displaySequence}</td><td>{x.alarmZone}</td><td>{x.location}</td><td>{result(x.manualCallPoint!)}</td><td>{result(x.flowSwitch!)}</td><td>{result(x.heatDetector!)}</td><td>{result(x.smokeDetector!)}</td><td>{x.remarks||"—"}</td></tr>)}</tbody></table></div></section>
<section><h3>Charger &amp; Batteries</h3>{Object.entries(r.chargerAndBatteries).map(([k,v])=><div className="accepted-check-row" key={k}><strong>{labels[k]}</strong><span>{result(v.result!)}</span><span>{v.remarks||"—"}</span></div>)}</section><section><h3>Main Function Key</h3>{Object.entries(r.mainFunctionKeys).map(([k,v])=><div className="accepted-check-row" key={k}><strong>{labels[k]}</strong><span>{result(v.result!)}</span><span>{v.remarks||"—"}</span></div>)}</section>
<section><h3>Alarm Bell and Manual Call Point Rows</h3><div className="server-detail-table-wrap"><table><thead><tr><th>No.</th><th>Location</th><th>Alarm Bell</th><th>Manual Call Point</th><th>Remarks</th></tr></thead><tbody>{r.secondaryAlarmDeviceRows.map(x=><tr key={x.rowUuid}><td>{x.assetReference||x.displaySequence}</td><td>{x.location}</td><td>{result(x.alarmBell!)}</td><td>{result(x.manualCallPoint!)}</td><td>{x.remarks||"—"}</td></tr>)}</tbody></table></div></section><section><h3>Comments</h3><p>{r.comments||"—"}</p></section></section>}
