import type { FireAlarmPrimaryDeviceRow, FireAlarmResponses, FireAlarmSecondaryAlarmDeviceRow, ServerFireAlarmDetail } from "./fireAlarmTypes";

type R=Record<string,unknown>;
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const detailKeys=["clientUuid","serverFormInstanceId","jobId","jobReference","jobTitle","customerId","customerCode","customerName","systemKey","systemLabel","instanceKey","zoneId","locationId","displaySequence","status","performedAt","receivedAt","template","configuration","responses","deviceReportedCreatorUsername","verifiedOriginalCreatorUsername","syncedByUsername"];
const responseKeys=["schemaVersion","controlPanelLocation","primaryDeviceRows","chargerAndBatteries","mainFunctionKeys","secondaryAlarmDeviceRows","comments"];
const primaryKeys=["rowUuid","source","configuredLocationId","configuredRowOrdinal","zoneSnapshot","locationSnapshot","displaySequence","assetReference","alarmZone","location","manualCallPoint","flowSwitch","heatDetector","smokeDetector","remarks"];
const secondaryKeys=["rowUuid","source","configuredLocationId","configuredRowOrdinal","zoneSnapshot","locationSnapshot","displaySequence","assetReference","location","alarmBell","manualCallPoint","remarks"];
const chargerKeys=["main_supply","battery","charger"],functionKeys=["main_alarm_reset","lamp_test","evacuate","ac_supply","dc_supply","spka_system","alarm_lift_trip","signal_gas_discharge"];
const rec=(v:unknown):v is R=>typeof v==="object"&&v!==null&&!Array.isArray(v);
const exact=(v:R,k:string[])=>Object.keys(v).length===k.length&&k.every(x=>x in v);
const text=(v:unknown,n=300,required=true):v is string=>typeof v==="string"&&v.length<=n&&(!required||v.trim().length>0);
const timestamp=(v:unknown):v is string=>{
  if(typeof v!=="string")return false;
  const match=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})\.(\d{6})Z$/.exec(v);
  if(!match)return false;
  const year=Number(match[1]),month=Number(match[2]),day=Number(match[3]);
  const hour=Number(match[4]),minute=Number(match[5]),second=Number(match[6]);
  const leap=year%4===0&&(year%100!==0||year%400===0);
  const days=[31,leap?29:28,31,30,31,30,31,31,30,31,30,31];
  return month>=1&&month<=12&&day>=1&&day<=days[month-1]
    &&hour<=23&&minute<=59&&second<=59;
};
const nullableText=(v:unknown)=>v===null||text(v,160);
function name(v:unknown,id:unknown,max:number){return rec(v)&&exact(v,["id","displayName"])&&v.id===id&&typeof v.id==="string"&&uuid.test(v.id)&&text(v.displayName,max);}
function checklist(v:unknown,keys:string[]){if(!rec(v)||!exact(v,keys))return;const out:R={};for(const key of keys){const item=v[key];if(!rec(item)||!exact(item,["result","remarks"])||(item.result!=="good"&&item.result!=="poor")||!text(item.remarks,2000,false))return;out[key]={result:item.result,remarks:item.remarks};}return out;}
function parseRows(items:unknown,table:"primary"|"secondary",seen:Set<string>){if(!Array.isArray(items)||(table==="primary"&&(items.length<1||items.length>250))||(table==="secondary"&&items.length>250))return;const out:R[]=[];let technician=false;for(let i=0;i<items.length;i++){const row=items[i];if(!rec(row)||!exact(row,table==="primary"?primaryKeys:secondaryKeys)||typeof row.rowUuid!=="string"||!uuid.test(row.rowUuid)||seen.has(row.rowUuid)||row.displaySequence!==i+1||!text(row.assetReference,250,false)||!text(row.location,300)||!text(row.remarks,2000,false))return;seen.add(row.rowUuid);if(row.source==="configured"){if(technician||typeof row.configuredLocationId!=="string"||!uuid.test(row.configuredLocationId)||!Number.isSafeInteger(row.configuredRowOrdinal)||Number(row.configuredRowOrdinal)<1||!name(row.locationSnapshot,row.configuredLocationId,300)||!(row.zoneSnapshot===null||rec(row.zoneSnapshot)&&typeof row.zoneSnapshot.id==="string"&&name(row.zoneSnapshot,row.zoneSnapshot.id,200)))return;}else{technician=true;if(row.source!=="technician"||row.configuredLocationId!==null||row.configuredRowOrdinal!==null||row.zoneSnapshot!==null||row.locationSnapshot!==null)return;}if(table==="primary"){if(!text(row.alarmZone,200)||![row.manualCallPoint,row.flowSwitch,row.heatDetector,row.smokeDetector].every(x=>x==="normal"||x==="test"||x==="isolation"))return;}else if(![row.alarmBell,row.manualCallPoint].every(x=>x==="good"||x==="poor"))return;out.push({...row});}return out;}
function parseResponses(v:unknown):FireAlarmResponses|undefined{if(!rec(v)||!exact(v,responseKeys)||v.schemaVersion!==1||!text(v.controlPanelLocation,300)||!text(v.comments,4000,false))return;const seen=new Set<string>(),primary=parseRows(v.primaryDeviceRows,"primary",seen),secondary=parseRows(v.secondaryAlarmDeviceRows,"secondary",seen),charger=checklist(v.chargerAndBatteries,chargerKeys),functions=checklist(v.mainFunctionKeys,functionKeys);if(!primary||!secondary||!charger||!functions)return;return{schemaVersion:1,controlPanelLocation:v.controlPanelLocation,primaryDeviceRows:primary as FireAlarmPrimaryDeviceRow[],chargerAndBatteries:charger as FireAlarmResponses["chargerAndBatteries"],mainFunctionKeys:functions as FireAlarmResponses["mainFunctionKeys"],secondaryAlarmDeviceRows:secondary as FireAlarmSecondaryAlarmDeviceRow[],comments:v.comments};}

export class FireAlarmDetailNotFoundError extends Error{}
export class InvalidFireAlarmDetailError extends Error{}
export class FireAlarmAuthenticationError extends Error{}
export function parseServerFireAlarmDetail(value:unknown,requestedClientUuid:string,expectedJobId:string):ServerFireAlarmDetail|undefined{
  if(!uuid.test(expectedJobId)||!rec(value)||!exact(value,detailKeys)||value.clientUuid!==requestedClientUuid||typeof value.clientUuid!=="string"||!uuid.test(value.clientUuid)||typeof value.serverFormInstanceId!=="string"||!uuid.test(value.serverFormInstanceId)||value.jobId!==expectedJobId||typeof value.jobId!=="string"||!uuid.test(value.jobId)||!text(value.jobReference,250)||!text(value.jobTitle,300)||typeof value.customerId!=="string"||!uuid.test(value.customerId)||!text(value.customerCode,128)||!text(value.customerName,250)||value.systemKey!=="fire_alarm_detector"||value.systemLabel!=="Fire Alarm / Detector System"||value.instanceKey!=="primary"||value.zoneId!==null||value.locationId!==null||value.displaySequence!==1||value.status!=="submitted"||!timestamp(value.performedAt)||!timestamp(value.receivedAt)||!rec(value.template)||!exact(value.template,["id","code","version"])||typeof value.template.id!=="string"||!uuid.test(value.template.id)||value.template.code!=="MFE-FSSR"||!Number.isSafeInteger(value.template.version)||Number(value.template.version)<1||!rec(value.configuration)||!exact(value.configuration,["revisionId","revisionNumber"])||typeof value.configuration.revisionId!=="string"||!uuid.test(value.configuration.revisionId)||!Number.isSafeInteger(value.configuration.revisionNumber)||Number(value.configuration.revisionNumber)<1||!nullableText(value.deviceReportedCreatorUsername)||!nullableText(value.verifiedOriginalCreatorUsername)||!text(value.syncedByUsername,160))return;
  const responses=parseResponses(value.responses);if(!responses)return;
  return{clientUuid:value.clientUuid,serverFormInstanceId:value.serverFormInstanceId,jobId:value.jobId,jobReference:value.jobReference,jobTitle:value.jobTitle,customer:{id:value.customerId,code:value.customerCode,displayName:value.customerName},systemKey:"fire_alarm_detector",systemLabel:"Fire Alarm / Detector System",instanceKey:"primary",status:"submitted",performedAt:value.performedAt,receivedAt:value.receivedAt,template:{id:value.template.id,code:"MFE-FSSR",version:value.template.version as number},configuration:{revisionId:value.configuration.revisionId,revisionNumber:value.configuration.revisionNumber as number},responses,deviceReportedCreatorUsername:value.deviceReportedCreatorUsername as string|null,verifiedOriginalCreatorUsername:value.verifiedOriginalCreatorUsername as string|null,syncedByUsername:value.syncedByUsername};
}
export async function loadServerFireAlarmDetail(clientUuid:string,expectedJobId:string):Promise<ServerFireAlarmDetail>{if(!uuid.test(clientUuid)||!uuid.test(expectedJobId))throw new InvalidFireAlarmDetailError("Inspection or job identifier is invalid");const response=await fetch(`/api/fire-alarm-inspections/${encodeURIComponent(clientUuid)}`,{credentials:"same-origin",cache:"no-store"});if(response.status===404)throw new FireAlarmDetailNotFoundError("Accepted Fire Alarm inspection was not found");if(response.status===401||response.status===403)throw new FireAlarmAuthenticationError("Sign in required to view this inspection");if(!response.ok)throw new Error(`Fire Alarm server detail failed: ${response.status}`);const envelope:unknown=await response.json();if(!rec(envelope)||!exact(envelope,["inspection"]))throw new InvalidFireAlarmDetailError("Server returned invalid accepted Fire Alarm detail");const detail=parseServerFireAlarmDetail(envelope.inspection,clientUuid,expectedJobId);if(!detail)throw new InvalidFireAlarmDetailError("Server returned invalid accepted Fire Alarm detail");return detail;}
