import { useEffect, useState } from "react";
import { ResultSelector } from "../inspectionControls/ResultSelector";
import { RemarksField } from "../inspectionControls/RemarksField";
import { FireIntercomV7EvidenceField } from "./FireIntercomV7EvidenceField";
import { submitIssues } from "./fireIntercomRepository";
import { fireIntercomRowColumns, type FireIntercomInspectionRecord, type FireIntercomResponses, type FireIntercomResult } from "./fireIntercomTypes";
import { isFireIntercomV7EvidenceFinding, listFireIntercomV7Photos, resolveFireIntercomRowResultDefinitions, type FireIntercomV7FieldPath } from "./fireIntercomV7Evidence";

const remarks = { policy: "optional" as const, maxLength: 2000 };

export function FireIntercomInspectionForm({ record, onBack, onSaveDraft, onSubmitLocal, onEditFailed }: { record: FireIntercomInspectionRecord; onBack: () => void; onSaveDraft: (responses: FireIntercomResponses) => Promise<void>; onSubmitLocal: (responses: FireIntercomResponses) => Promise<void>; onEditFailed: () => Promise<void> }) {
  const [responses, setResponses] = useState(record.responses); const [message, setMessage] = useState(""); const [show, setShow] = useState(false); const [photos, setPhotos] = useState<Awaited<ReturnType<typeof listFireIntercomV7Photos>>>([]);
  const rowDefinitions = resolveFireIntercomRowResultDefinitions(record.inspectionSnapshot.system.definition);
  useEffect(() => setResponses(record.responses), [record]);
  useEffect(() => { void listFireIntercomV7Photos(record.clientUuid).then(setPhotos); }, [record.clientUuid, record.localUpdatedAt]);
  const readOnly = record.syncStatus !== "Draft";
  const issues = show ? submitIssues(record, responses, photos) : [];
  const updateRow = (id: string, change: Partial<FireIntercomResponses["rows"][number]>) => setResponses((current) => ({ ...current, rows: current.rows.map((row) => row.rowUuid === id ? { ...row, ...change } : row) }));
  const addRow = () => setResponses((current) => ({ ...current, rows: [...current.rows, { rowUuid: crypto.randomUUID(), source: "technician", configuredLocationId: null, configuredRowOrdinal: null, zoneSnapshot: null, locationSnapshot: null, assetReference: "", conditionResult: null, remarks: "", fieldRemarks: {}, sortOrder: current.rows.length + 1 }] }));
  const evidenceFor = (fieldPath: string) => photos.find((photo) => photo.fieldPath === fieldPath);
  const refreshPhotos = async () => setPhotos(await listFireIntercomV7Photos(record.clientUuid));
  return <section className="hose-reel-form" aria-labelledby="fire-intercom-title"><button type="button" className="secondary-command" onClick={onBack}>Back to Systems</button><header className="inspection-context"><div><p className="eyebrow">{record.inspectionSnapshot.job.reference}</p><h2 id="fire-intercom-title">Fire Intercom System</h2><p><strong>{record.inspectionSnapshot.customer.displayName}</strong></p><p>{record.inspectionSnapshot.job.title}</p></div><strong>{record.syncStatus === "Synced" ? "Inspection Complete" : record.syncStatus === "Pending" ? "Waiting to Sync" : record.syncStatus === "Failed" || record.syncStatus === "Conflict" ? "Needs Attention" : record.syncStatus === "Syncing" ? "Syncing…" : record.syncStatus}</strong></header>{record.lastSyncError ? <p className="error-text">{record.lastSyncError}</p> : null}{message ? <p className="form-message">{message}</p> : null}{show && issues.length ? <section className="validation-summary" role="alert"><h3>Cannot submit yet</h3><ul>{issues.map((issue, index) => <li key={index}>{issue}</li>)}</ul></section> : null}{["Failed", "Conflict"].includes(record.syncStatus) ? <button type="button" onClick={() => void onEditFailed()}>Edit Failed Inspection</button> : null}
    <fieldset disabled={readOnly}><legend>Station Schedule</legend>{responses.rows.map((row, index) => { const configured = row.source === "configured"; return <section className="hose-row-card" key={row.rowUuid}><h4>Station {index + 1}</h4><label>Station<input value={row.assetReference} disabled={readOnly || configured} onChange={(event) => updateRow(row.rowUuid, { assetReference: event.target.value })} /></label>{fireIntercomRowColumns.map(([field, wireKey, label]) => { const definition = rowDefinitions?.[field]; const result = row[field] as FireIntercomResult | null; const finding = isFireIntercomV7EvidenceFinding(result); const fieldPath = `station_schedule.station_schedule_rows.rows.${row.rowUuid}.${wireKey}` as FireIntercomV7FieldPath; return <div className="hose-component" key={field}><strong>{label}</strong>{definition ? <ResultSelector<FireIntercomResult> definition={definition} label={`${label} result`} value={result} readOnly={readOnly} onChange={(value) => updateRow(row.rowUuid, { [field]: value })} /> : <p className="error-text">Fire Intercom V7 definition is unavailable.</p>}{finding ? <section><RemarksField label={`${label} Remark *`} definition={remarks} value={row.fieldRemarks?.[field] ?? ""} readOnly={readOnly} onChange={(value) => updateRow(row.rowUuid, { fieldRemarks: { ...row.fieldRemarks, [field]: value } })} /><FireIntercomV7EvidenceField record={record} fieldPath={fieldPath} attachment={evidenceFor(fieldPath)} onChanged={refreshPhotos} /></section> : null}</div>; })}<RemarksField label="Remarks" definition={remarks} value={row.remarks} readOnly={readOnly} onChange={(value) => updateRow(row.rowUuid, { remarks: value })} />{!readOnly && row.source === "technician" ? <button type="button" className="secondary-command" onClick={() => setResponses((current) => ({ ...current, rows: current.rows.filter((candidate) => candidate.rowUuid !== row.rowUuid).map((candidate, rowIndex) => ({ ...candidate, sortOrder: rowIndex + 1 })) }))}>Remove Row</button> : null}</section>; })}{!readOnly ? <button type="button" className="secondary-command" onClick={addRow}>Add Row</button> : null}</fieldset>
    <fieldset disabled={readOnly}><legend>Comments</legend><RemarksField label="Comments" definition={{ policy: "optional", maxLength: 4000 }} value={responses.comments} readOnly={readOnly} onChange={(comments) => setResponses((current) => ({ ...current, comments }))} /></fieldset>
    {!readOnly ? <div className="form-actions sticky-form-actions"><button type="button" className="secondary-command" onClick={() => void onSaveDraft(responses).then(() => setMessage("Draft saved on this device.")).catch((error) => setMessage(error.message))}>Save Draft</button><button type="button" onClick={() => { setShow(true); if (!submitIssues(record, responses, photos).length) void onSubmitLocal(responses).catch((error) => setMessage(error.message)); }}>Submit Inspection</button></div> : null}
  </section>;
}
