import assert from "node:assert/strict";
import test from "node:test";
import pg from "pg";
import { createHash, randomBytes, randomUUID } from "node:crypto";
import { once } from "node:events";
import { mkdir, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import express from "express";
import sharp from "sharp";
import { runMigrations } from "../db/migrations.js";
import { fireAlarmV6ContractSha256, reserveFireAlarmV6Session } from "../inspections/evidence/fireAlarmV6Evidence.js";
import { closeInspectionJob, setJobCompletionTestBarrier } from "../jobs/jobCompletion.js";
import { acceptFireAlarmV6Inspection, setFireAlarmV6AcceptanceTestBarrier } from "./fireAlarmV6Acceptance.js";
import { stagedEvidenceRouter } from "../routes/stagedEvidence.js";

const databaseUrl = process.env.SEED_INTEGRATION_DATABASE_URL;
const uuid = () => randomUUID();
const time = "2026-08-27T00:00:00.000Z";

test("V6 reservations and acceptance are isolated and atomic on PostgreSQL", { skip: !databaseUrl }, async () => {
  assert.equal(new URL(databaseUrl!).port, "55432", "test requires the dedicated isolated PostgreSQL port");
  const database = new pg.Pool({ connectionString: databaseUrl }); const uploadsPath = path.join(tmpdir(), `phase8f-v6-evidence-${uuid()}`); process.env.UPLOADS_PATH = uploadsPath;
  try {
    await database.query("DROP SCHEMA public CASCADE; CREATE SCHEMA public;");
    await runMigrations(database);
    assert.equal((await database.query("SELECT 1 FROM information_schema.tables WHERE table_name='staged_inspection_evidence'")).rowCount, 1, "migration 017 created staged authority");
    const schemaConstraints = await database.query<{ conname: string; definition: string }>(`SELECT conname, pg_get_constraintdef(oid) AS definition FROM pg_constraint WHERE conrelid='master_system_form_instances'::regclass AND conname IN ('master_system_form_instances_response_schema_version_check','master_system_form_instances_snapshot_schema_version_check')`);
    assert.equal(schemaConstraints.rows.length, 2, "migration 017 preserves both V6 schema constraints");
    assert.ok(schemaConstraints.rows.every((row) => row.definition.includes("1, 2")), "response and snapshot schema versions allow V1 and V6 only");
    const template = (await database.query<{ id: string; code: string; name: string; definition: unknown }>(`SELECT template.id, template.code, template.name, system.definition FROM master_service_report_templates template INNER JOIN master_service_report_systems system ON system.template_version_id=template.id WHERE template.version=6 AND system.system_key='fire_alarm_detector'`)).rows[0]!;
    const customerId = uuid(); const revisionId = uuid(); const enabledSystemId = uuid();
    await database.query(`INSERT INTO customers(id,customer_code,display_name,is_demo) VALUES($1,$2,'V6 integration customer',true)`, [customerId, `V6-${customerId}`]);
    await database.query(`INSERT INTO customer_configuration_revisions(id,customer_id,template_version_id,revision,status) VALUES($1,$2,$3,1,'active')`, [revisionId, customerId, template.id]);
    await database.query(`INSERT INTO customer_enabled_systems(id,configuration_revision_id,template_version_id,system_key,sort_order,system_configuration) VALUES($1,$2,$3,'fire_alarm_detector',1,'{}')`, [enabledSystemId, revisionId, template.id]);
    const system = { enabledSystemId, systemKey: "fire_alarm_detector", displayName: "Fire Alarm / Detector System", sortOrder: 1, definitionStatus: "confirmed", zones: [], locations: [] };
    const makeJob = async () => { const jobId = uuid(); const snapshot = { schemaVersion: 1, customer: { id: customerId, code: `V6-${customerId}`, displayName: "V6 integration customer" }, configuration: { revisionId, revisionNumber: 1 }, template: { id: template.id, code: template.code, name: template.name, version: 6 }, enabledSystems: [system] }; await database.query(`INSERT INTO inspection_jobs(id,master_template_version_id,job_reference,title,status,is_sample,technician_visible,customer_id,customer_configuration_revision_id,configuration_snapshot) VALUES($1,$2,$3,'V6 integration','open',true,true,$4,$5,$6)`, [jobId,template.id,`V6-${jobId}`,customerId,revisionId,snapshot]); return { jobId, snapshot }; };
    const { jobId, snapshot } = await makeJob();
    const actors = await Promise.all(["v6-tech-a", "v6-tech-b"].map(async (username) => (await database.query<{ id: number }>(`INSERT INTO users(username,password_hash,role) VALUES($1,'not-used','inspector') RETURNING id`, [`${username}-${uuid()}`])).rows[0]!.id));
    const contract = fireAlarmV6ContractSha256(template.definition); const inspectionX = uuid(); const client = await database.connect();
    try {
      await client.query("BEGIN"); await reserveFireAlarmV6Session(client, { inspectionClientUuid: inspectionX, jobId, systemKey: "fire_alarm_detector", masterTemplateId: template.id, contractSha256: contract, actorUserId: actors[0] }); await client.query("COMMIT");
      await client.query("BEGIN"); await reserveFireAlarmV6Session(client, { inspectionClientUuid: inspectionX, jobId, systemKey: "fire_alarm_detector", masterTemplateId: template.id, contractSha256: contract, actorUserId: actors[0] }); await client.query("COMMIT");
      await client.query("BEGIN"); await assert.rejects(() => reserveFireAlarmV6Session(client, { inspectionClientUuid: inspectionX, jobId, systemKey: "fire_alarm_detector", masterTemplateId: template.id, contractSha256: contract, actorUserId: actors[1] })); await client.query("ROLLBACK");
      await client.query("BEGIN"); await reserveFireAlarmV6Session(client, { inspectionClientUuid: uuid(), jobId, systemKey: "fire_alarm_detector", masterTemplateId: template.id, contractSha256: contract, actorUserId: actors[1] }); await client.query("COMMIT");
    } finally { client.release(); }
    const primaryUuid = uuid(); const photoUuid = uuid(); const fieldPath = "charger_batteries.charger_battery_checks.battery"; const sourceHash = "a".repeat(64);
    const mainPhotoUuid = uuid(); const mainFieldPath = "charger_batteries.charger_battery_checks.main_supply"; const mainSourceHash = "d".repeat(64);
    await database.query(`INSERT INTO staged_inspection_evidence(photo_uuid,inspection_client_uuid,job_id,system_key,field_path,master_template_version_id,master_template_version,system_contract_sha256,uploader_user_id,request_fingerprint,source_sha256,stored_sha256,mime_type,source_size_bytes,source_width,source_height,stored_size_bytes,width,height,storage_relative_path,status) VALUES($1,$2,$3,'fire_alarm_detector',$4,$5,6,$6,$7,$8,$9,$10,'image/jpeg',1,1,1,1,1,1,$11,'staged')`, [mainPhotoUuid,inspectionX,jobId,mainFieldPath,template.id,contract,actors[0],"e".repeat(64),mainSourceHash,"f".repeat(64),`inspections/${inspectionX}/${mainPhotoUuid}.jpg`]);
    await database.query(`INSERT INTO staged_inspection_evidence(photo_uuid,inspection_client_uuid,job_id,system_key,field_path,master_template_version_id,master_template_version,system_contract_sha256,uploader_user_id,request_fingerprint,source_sha256,stored_sha256,mime_type,source_size_bytes,source_width,source_height,stored_size_bytes,width,height,storage_relative_path,status) VALUES($1,$2,$3,'fire_alarm_detector',$4,$5,6,$6,$7,$8,$9,$10,'image/jpeg',1,1,1,1,1,1,$11,'staged')`, [photoUuid,inspectionX,jobId,fieldPath,template.id,contract,actors[0],"b".repeat(64),sourceHash,"c".repeat(64),`inspections/${inspectionX}/${photoUuid}.jpg`]);
    const result = (value: "good" | "poor" | "not_relevant", remarks = "") => ({ result: value, remarks });
    const responses = { schemaVersion: 2, controlPanelLocation: "Panel", primaryDeviceRows: [{ rowUuid: primaryUuid, source: "technician", configuredLocationId: null, configuredRowOrdinal: null, zoneSnapshot: null, locationSnapshot: null, displaySequence: 1, assetReference: "", alarmZone: "A", location: "B", manualCallPoint: "normal", flowSwitch: "normal", heatDetector: "normal", smokeDetector: "normal", remarks: "" }], chargerAndBatteries: { main_supply: result("poor", "Runtime Final Poor A"), battery: result("poor", "Runtime Final Poor B"), charger: result("not_relevant") }, mainFunctionKeys: { main_alarm_reset: result("good"), lamp_test: result("good"), evacuate: result("good"), ac_supply: result("good"), dc_supply: result("good"), spka_system: result("good"), alarm_lift_trip: result("good"), signal_gas_discharge: result("good") }, secondaryAlarmDeviceRows: [], comments: "" };
    const raceResponses = structuredClone(responses); raceResponses.chargerAndBatteries.main_supply = result("good"); raceResponses.chargerAndBatteries.battery = result("poor", "Battery failed");
    const item = { operationId: uuid(), entityType: "masterSystemInspection", entityId: inspectionX, action: "create", payload: { clientUuid: inspectionX, jobId, systemKey: "fire_alarm_detector", instanceKey: "primary", configuredZoneId: null, configuredLocationId: null, displaySequence: 1, originalCreatorSnapshot: null, masterTemplate: { id: template.id, code: template.code, version: 6 }, configuration: snapshot.configuration, inspectionSnapshot: snapshot, responses, evidenceManifest: [{ photoUuid: mainPhotoUuid, fieldPath: mainFieldPath, sourceSha256: mainSourceHash }, { photoUuid, fieldPath, sourceSha256: sourceHash }], performedAt: time } };
    const missingEvidence = await acceptFireAlarmV6Inspection({ ...item, operationId: uuid(), payload: { ...item.payload, evidenceManifest: [] } }, actors[0]);
    assert.equal(missingEvidence.acceptedIds.length, 0, "missing Poor evidence cannot create accepted authority");
    const missingMainRemark = structuredClone(responses); missingMainRemark.chargerAndBatteries.main_supply.remarks = "";
    assert.equal((await acceptFireAlarmV6Inspection({ ...item, operationId: uuid(), payload: { ...item.payload, responses: missingMainRemark } }, actors[0])).failed[0]?.message, "V6 Fire Alarm response is malformed or missing a Poor remark", "missing static Poor A own remark remains rejected");
    const missingBatteryRemark = structuredClone(responses); missingBatteryRemark.chargerAndBatteries.battery.remarks = "";
    assert.equal((await acceptFireAlarmV6Inspection({ ...item, operationId: uuid(), payload: { ...item.payload, responses: missingBatteryRemark } }, actors[0])).failed[0]?.message, "V6 Fire Alarm response is malformed or missing a Poor remark", "missing static Poor B own remark remains rejected");
    const malformedAssetReference = (assetReference: unknown) => { const value = structuredClone(responses) as Record<string, unknown>; (value.primaryDeviceRows as Array<Record<string, unknown>>)[0]!.assetReference = assetReference; return value; };
    assert.equal((await acceptFireAlarmV6Inspection({ ...item, operationId: uuid(), payload: { ...item.payload, responses: malformedAssetReference(undefined) } }, actors[0])).failed[0]?.code, "VALIDATION_ERROR", "undefined asset reference is rejected by the exact accepted V6 row contract");
    assert.equal((await acceptFireAlarmV6Inspection({ ...item, operationId: uuid(), payload: { ...item.payload, responses: malformedAssetReference(42) } }, actors[0])).failed[0]?.code, "VALIDATION_ERROR", "non-string asset reference is rejected by the accepted V6 row contract");
    const emptyRequiredLocation = structuredClone(responses) as Record<string, unknown>; (emptyRequiredLocation.primaryDeviceRows as Array<Record<string, unknown>>)[0]!.location = ""; assert.equal((await acceptFireAlarmV6Inspection({ ...item, operationId: uuid(), payload: { ...item.payload, responses: emptyRequiredLocation } }, actors[0])).failed[0]?.code, "VALIDATION_ERROR", "empty required Fire Alarm location remains rejected while asset reference is optional");
    assert.equal((await database.query(`SELECT count(*)::int AS count FROM master_system_form_instances WHERE client_uuid=$1`, [inspectionX])).rows[0]?.count, 0, "missing evidence leaves no form");
    assert.equal((await database.query<{ status: string }>(`SELECT status FROM staged_inspection_evidence WHERE photo_uuid=$1`, [photoUuid])).rows[0]?.status, "staged", "missing evidence leaves staged photo retryable");
    const unknownRowPhoto = uuid(); const unknownRow = uuid(); const unknownPath = `alarm_devices.alarm_device_rows.rows.${unknownRow}.alarm_bell`;
    await database.query(`INSERT INTO staged_inspection_evidence(photo_uuid,inspection_client_uuid,job_id,system_key,field_path,master_template_version_id,master_template_version,system_contract_sha256,uploader_user_id,request_fingerprint,source_sha256,stored_sha256,mime_type,source_size_bytes,source_width,source_height,stored_size_bytes,width,height,storage_relative_path,status) VALUES($1,$2,$3,'fire_alarm_detector',$4,$5,6,$6,$7,$8,$9,$10,'image/jpeg',1,1,1,1,1,1,$11,'staged')`, [unknownRowPhoto,inspectionX,jobId,unknownPath,template.id,contract,actors[0],"d".repeat(64),"e".repeat(64),"f".repeat(64),`inspections/${inspectionX}/${unknownRowPhoto}.jpg`]);
    const unknownRowResult = await acceptFireAlarmV6Inspection({ ...item, operationId: uuid(), payload: { ...item.payload, evidenceManifest: [...item.payload.evidenceManifest, { photoUuid: unknownRowPhoto, fieldPath: unknownPath, sourceSha256: "e".repeat(64) }] } }, actors[0]);
    assert.equal(unknownRowResult.acceptedIds.length, 0, "nonexistent dynamic row cannot be accepted");
    assert.equal((await database.query<{ status: string }>(`SELECT status FROM staged_inspection_evidence WHERE photo_uuid=$1`, [unknownRowPhoto])).rows[0]?.status, "staged", "nonexistent dynamic-row evidence remains non-authoritative");
    const duplicateRows = structuredClone(responses) as Record<string, unknown>; duplicateRows.secondaryAlarmDeviceRows = [{ rowUuid: primaryUuid, source: "technician", configuredLocationId: null, configuredRowOrdinal: null, zoneSnapshot: null, locationSnapshot: null, displaySequence: 1, assetReference: "", location: "C", alarmBell: "good", manualCallPoint: "good", remarks: "", fieldRemarks: {} }];
    const duplicateRowResult = await acceptFireAlarmV6Inspection({ ...item, operationId: uuid(), payload: { ...item.payload, responses: duplicateRows } }, actors[0]);
    assert.equal(duplicateRowResult.acceptedIds.length, 0, "duplicate row UUID cannot be accepted");
    const concurrent = await Promise.all([acceptFireAlarmV6Inspection(item, actors[0]), acceptFireAlarmV6Inspection(item, actors[0])]);
    assert.equal(concurrent.filter((result) => result.acceptedIds.includes(inspectionX)).length, 1, "one concurrent request creates authority");
    assert.equal(concurrent.filter((result) => result.duplicateIds.includes(inspectionX)).length, 1, "other concurrent request is an exact duplicate");
    const evidence = await database.query<{ status: string; form_instance_id: string | null }>(`SELECT status,form_instance_id FROM staged_inspection_evidence WHERE photo_uuid=$1`, [photoUuid]); assert.equal(evidence.rows[0]?.status, "accepted"); assert.ok(evidence.rows[0]?.form_instance_id);
    const stored = (await database.query<{ storage_relative_path: string }>(`SELECT storage_relative_path FROM staged_inspection_evidence WHERE photo_uuid=$1`, [photoUuid])).rows[0]!;
    const binary = await sharp({ create: { width: 1, height: 1, channels: 3, background: "white" } }).jpeg().toBuffer();
    await mkdir(path.join(uploadsPath, ...stored.storage_relative_path.split("/").slice(0, -1)), { recursive: true }); await writeFile(path.join(uploadsPath, ...stored.storage_relative_path.split("/")), binary);
    const app = express(); app.use((request, _response, next) => { const actor = request.headers["x-v6-user"]; if (actor === "a") request.currentUser = { id: actors[0], username: "v6-tech-a", role: "inspector" }; if (actor === "b") request.currentUser = { id: actors[1], username: "v6-tech-b", role: "inspector" }; if (actor === "admin") request.currentUser = { id: actors[0], username: "v6-admin", role: "admin" }; next(); }); app.use(stagedEvidenceRouter);
    const server = app.listen(0, "127.0.0.1"); await once(server, "listening"); const address = server.address() as { port: number }; const origin = `http://127.0.0.1:${address.port}`;
    try {
      const multipartJpeg = await sharp({ create: { width: 2, height: 2, channels: 3, background: "white" } }).jpeg().toBuffer();
      const multipartHash = createHash("sha256").update(multipartJpeg).digest("hex"); const multipartPhoto = uuid(); const multipartField = "charger_batteries.charger_battery_checks.charger";
      const stage = async (overrides: Record<string, string> = {}, actor = "a", bytes = multipartJpeg, mime = "image/jpeg", name = "evidence.jpg") => { const form = new FormData(); const values: Record<string, string> = { photoUuid: multipartPhoto, inspectionClientUuid: inspectionX, jobId, systemKey: "fire_alarm_detector", fieldPath: multipartField, masterTemplateId: template.id, masterTemplateVersion: "6", contractSha256: contract, captureSource: "camera", capturedAt: time, sha256: createHash("sha256").update(bytes).digest("hex"), sizeBytes: String(bytes.length), width: "2", height: "2", ...overrides }; for (const [key, value] of Object.entries(values)) form.set(key, value); form.set("file", new Blob([new Uint8Array(bytes)], { type: mime }), name); return fetch(`${origin}/v6-evidence/stage`, { method: "POST", headers: { "x-v6-user": actor }, body: form }); };
      const stagedHttp = await stage(); assert.equal(stagedHttp.status, 201, "actual multipart JPEG stages through the route"); const stagedBody = await stagedHttp.json() as { outcome: string; photoUuid: string; fieldPath: string; sourceSha256: string }; assert.equal(stagedBody.outcome, "staged"); assert.equal(stagedBody.photoUuid, multipartPhoto); assert.equal(stagedBody.fieldPath, multipartField); assert.equal(stagedBody.sourceSha256, multipartHash);
      const stagedRow = (await database.query<{ photo_uuid: string; source_sha256: string; status: string; form_instance_id: string | null; uploader_user_id: number }>(`SELECT photo_uuid,source_sha256,status,form_instance_id,uploader_user_id FROM staged_inspection_evidence WHERE photo_uuid=$1`, [multipartPhoto])).rows[0]!; assert.equal(stagedRow.photo_uuid, multipartPhoto); assert.equal(stagedRow.source_sha256, multipartHash); assert.equal(stagedRow.status, "staged"); assert.equal(stagedRow.form_instance_id, null); assert.equal(stagedRow.uploader_user_id, actors[0]);
      assert.equal((await stage()).status, 200, "exact multipart retry is duplicate"); assert.equal((await stage({}, "a", await sharp({ create: { width: 2, height: 2, channels: 3, background: "black" } }).jpeg().toBuffer())).status, 409, "changed bytes conflict"); assert.equal((await stage({ fieldPath: "charger_batteries.charger_battery_checks.main_supply" })).status, 409, "changed field conflicts"); assert.equal((await stage({}, "b")).status, 409, "second technician cannot replay owner evidence");
      const otherInspection = uuid(); assert.equal((await stage({ inspectionClientUuid: otherInspection })).status, 409, "changed inspection UUID conflicts"); const { jobId: otherJob } = await makeJob(); assert.equal((await stage({ jobId: otherJob })).status, 409, "changed Job conflicts"); assert.equal((await stage({ systemKey: "hose_reel" })).status, 400, "mismatched system fails closed"); assert.equal((await stage({ contractSha256: "0".repeat(64) })).status, 409, "client contract override conflicts with frozen authority");
      const originalAfterConflicts = await database.query<{ count: number; inspection_client_uuid: string; job_id: string; field_path: string; status: string; form_instance_id: string | null }>(`SELECT count(*) OVER()::int AS count,inspection_client_uuid,job_id,field_path,status,form_instance_id FROM staged_inspection_evidence WHERE photo_uuid=$1`, [multipartPhoto]); assert.equal(originalAfterConflicts.rows.length, 1, "conflicts create no second staged row for the original photo UUID"); assert.equal(originalAfterConflicts.rows[0]?.count, 1); assert.deepEqual(originalAfterConflicts.rows[0] && { inspectionClientUuid: originalAfterConflicts.rows[0].inspection_client_uuid, jobId: originalAfterConflicts.rows[0].job_id, fieldPath: originalAfterConflicts.rows[0].field_path, status: originalAfterConflicts.rows[0].status, formInstanceId: originalAfterConflicts.rows[0].form_instance_id }, { inspectionClientUuid: inspectionX, jobId, fieldPath: multipartField, status: "staged", formInstanceId: null }, "original staged authority remains unchanged after multipart conflicts");
      assert.equal((await stage({ fieldPath: "fire_alarm_control_panel.device_rows.rows.not-a-uuid.manual_call_point" })).status, 400, "invalid static/dynamic field rejects"); assert.equal((await stage({ fieldPath: "fire_alarm_control_panel.device_rows.rows.00000000-0000-4000-8000-000000000001.manual_call_point" })).status, 400, "Normal/Test/Isolation target rejects"); assert.equal((await stage({}, "a", Buffer.from("not-a-jpeg"), "image/jpeg", "spoof.jpg")).status, 400, "JPEG filename/content spoof rejects"); assert.equal((await stage({}, "a", multipartJpeg, "image/png")).status, 400, "unsupported MIME rejects");
      const tooWide = await sharp({ create: { width: 1601, height: 1, channels: 3, background: "white" } }).jpeg().toBuffer(); assert.equal((await stage({ photoUuid: uuid(), width: "1601", height: "1" }, "a", tooWide)).status, 400, "source dimensions over policy reject");
      const overLimit = await sharp(randomBytes(1600 * 1600 * 3), { raw: { width: 1600, height: 1600, channels: 3 } }).jpeg({ quality: 100, chromaSubsampling: "4:4:4" }).toBuffer(); const overLimitPhoto = uuid(); assert.ok(overLimit.length > 2_097_152, "fixture exceeds configured upload byte limit"); assert.equal((await stage({ photoUuid: overLimitPhoto, width: "1600", height: "1600" }, "a", overLimit)).status, 400, "byte-size over limit rejects"); assert.equal((await database.query<{ count: number }>(`SELECT count(*)::int AS count FROM staged_inspection_evidence WHERE photo_uuid=$1`, [overLimitPhoto])).rows[0]?.count, 0, "over-limit multipart request creates no staged DB authority"); assert.equal(await stat(path.join(uploadsPath, "inspections", inspectionX, `${overLimitPhoto}.jpg`)).then(() => true).catch(() => false), false, "over-limit multipart request retains no canonical evidence file");
      const unknownDynamic = uuid(); const unknownDynamicResponse = await stage({ photoUuid: uuid(), fieldPath: `alarm_devices.alarm_device_rows.rows.${unknownDynamic}.alarm_bell` }); assert.equal(unknownDynamicResponse.status, 201, "syntactically valid unknown row stages non-authoritatively");
      const normalizedComment = Buffer.from("same JPEG pixels; distinct source bytes", "ascii");
      const commentLength = Buffer.alloc(2); commentLength.writeUInt16BE(normalizedComment.length + 2);
      const metadataDistinctJpeg = Buffer.concat([multipartJpeg.subarray(0, 2), Buffer.from([0xff, 0xfe]), commentLength, normalizedComment, multipartJpeg.subarray(2)]);
      const metadataDistinctHash = createHash("sha256").update(metadataDistinctJpeg).digest("hex");
      assert.notEqual(metadataDistinctHash, multipartHash, "the COM-marker JPEG is a distinct legitimate source file");
      const { jobId: crossJobId, snapshot: crossSnapshot } = await makeJob(); const crossInspection = uuid(); const crossPhotoOne = uuid(); const crossPhotoTwo = uuid(); const crossFieldOne = "charger_batteries.charger_battery_checks.main_supply"; const crossFieldTwo = "main_function_key.function_checks.lamp_test";
      assert.equal((await stage({ inspectionClientUuid: crossInspection, jobId: crossJobId, photoUuid: crossPhotoOne, fieldPath: crossFieldOne })).status, 201, "first cross-field photo stages through the actual multipart route");
      assert.equal((await stage({ inspectionClientUuid: crossInspection, jobId: crossJobId, photoUuid: crossPhotoTwo, fieldPath: crossFieldTwo }, "a", metadataDistinctJpeg)).status, 201, "metadata-distinct JPEG stages through the actual multipart route");
      const crossRows = await database.query<{ photo_uuid: string; source_sha256: string; stored_sha256: string }>(`SELECT photo_uuid,source_sha256,stored_sha256 FROM staged_inspection_evidence WHERE photo_uuid=ANY($1::uuid[]) ORDER BY photo_uuid`, [[crossPhotoOne, crossPhotoTwo]]);
      assert.equal(crossRows.rows.length, 2, "both distinct uploaded JPEGs have authoritative staged rows");
      assert.deepEqual(crossRows.rows.map((row) => row.source_sha256).sort(), [multipartHash, metadataDistinctHash].sort(), "the staged source hashes retain the distinct uploaded bytes");
      assert.equal(crossRows.rows[0]?.stored_sha256, crossRows.rows[1]?.stored_sha256, "the server normalizer produced the same authoritative stored bytes");
      const crossResponses = structuredClone(responses); crossResponses.chargerAndBatteries.main_supply = result("poor", "Main supply failed"); crossResponses.chargerAndBatteries.battery = result("good"); crossResponses.mainFunctionKeys.lamp_test = result("poor", "Lamp test failed");
      const crossItem = (evidenceManifest: Array<{ photoUuid: string; fieldPath: string; sourceSha256: string }>) => ({ ...item, operationId: uuid(), entityId: crossInspection, payload: { ...item.payload, clientUuid: crossInspection, jobId: crossJobId, configuration: crossSnapshot.configuration, inspectionSnapshot: crossSnapshot, responses: crossResponses, evidenceManifest } });
      const reusedPhoto = await acceptFireAlarmV6Inspection(crossItem([{ photoUuid: crossPhotoOne, fieldPath: crossFieldOne, sourceSha256: multipartHash }, { photoUuid: crossPhotoOne, fieldPath: crossFieldTwo, sourceSha256: multipartHash }]), actors[0]); assert.equal(reusedPhoto.failed[0]?.code, "VALIDATION_ERROR", "one photo UUID cannot satisfy two Poor fields");
      const reusedHash = await acceptFireAlarmV6Inspection(crossItem([{ photoUuid: crossPhotoOne, fieldPath: crossFieldOne, sourceSha256: multipartHash }, { photoUuid: crossPhotoTwo, fieldPath: crossFieldTwo, sourceSha256: multipartHash }]), actors[0]); assert.equal(reusedHash.failed[0]?.code, "VALIDATION_ERROR", "one source hash cannot satisfy two Poor fields");
      const reusedStored = await acceptFireAlarmV6Inspection(crossItem([{ photoUuid: crossPhotoOne, fieldPath: crossFieldOne, sourceSha256: multipartHash }, { photoUuid: crossPhotoTwo, fieldPath: crossFieldTwo, sourceSha256: metadataDistinctHash }]), actors[0]); assert.equal(reusedStored.failed[0]?.code, "EVIDENCE_NOT_UNIQUE", "different source hashes cannot reuse one authoritative stored hash across Poor fields");
      assert.equal((await stage({ inspectionClientUuid: crossInspection, jobId: crossJobId, photoUuid: uuid(), fieldPath: crossFieldOne, storedSha256: "0".repeat(64) })).status, 400, "client cannot submit a stored hash to the multipart staging route");
      assert.equal((await database.query<{ count: number }>(`SELECT count(*)::int AS count FROM master_system_form_instances WHERE client_uuid=$1`, [crossInspection])).rows[0]?.count, 0, "cross-field reuse rejects before creating accepted authority"); const crossEvidence = await database.query<{ photo_uuid: string; status: string; form_instance_id: string | null }>(`SELECT photo_uuid,status,form_instance_id FROM staged_inspection_evidence WHERE photo_uuid=ANY($1::uuid[]) ORDER BY photo_uuid`, [[crossPhotoOne, crossPhotoTwo]]); assert.deepEqual(crossEvidence.rows, [{ photo_uuid: [crossPhotoOne, crossPhotoTwo].sort()[0]!, status: "staged", form_instance_id: null }, { photo_uuid: [crossPhotoOne, crossPhotoTwo].sort()[1]!, status: "staged", form_instance_id: null }], "cross-field rejected photos remain staged and unbound");
      const { jobId: distinctJobId, snapshot: distinctSnapshot } = await makeJob(); const distinctInspection = uuid(); const distinctPhotoOne = uuid(); const distinctPhotoTwo = uuid(); const distinctJpeg = await sharp({ create: { width: 2, height: 2, channels: 3, background: "black" } }).jpeg().toBuffer(); const distinctHash = createHash("sha256").update(distinctJpeg).digest("hex");
      assert.equal((await stage({ inspectionClientUuid: distinctInspection, jobId: distinctJobId, photoUuid: distinctPhotoOne, fieldPath: crossFieldOne })).status, 201, "first independent photo stages"); assert.equal((await stage({ inspectionClientUuid: distinctInspection, jobId: distinctJobId, photoUuid: distinctPhotoTwo, fieldPath: crossFieldTwo }, "a", distinctJpeg)).status, 201, "second independent photo stages");
      const distinctRows = await database.query<{ source_sha256: string; stored_sha256: string }>(`SELECT source_sha256,stored_sha256 FROM staged_inspection_evidence WHERE photo_uuid=ANY($1::uuid[]) ORDER BY photo_uuid`, [[distinctPhotoOne, distinctPhotoTwo]]); assert.equal(new Set(distinctRows.rows.map((row) => row.source_sha256)).size, 2, "independent photos have distinct source hashes"); assert.equal(new Set(distinctRows.rows.map((row) => row.stored_sha256)).size, 2, "independent photos have distinct authoritative stored hashes");
      const distinctItem = { ...item, operationId: uuid(), entityId: distinctInspection, payload: { ...item.payload, clientUuid: distinctInspection, jobId: distinctJobId, configuration: distinctSnapshot.configuration, inspectionSnapshot: distinctSnapshot, responses: crossResponses, evidenceManifest: [{ photoUuid: distinctPhotoOne, fieldPath: crossFieldOne, sourceSha256: multipartHash }, { photoUuid: distinctPhotoTwo, fieldPath: crossFieldTwo, sourceSha256: distinctHash }] } };
      assert.deepEqual((await acceptFireAlarmV6Inspection(distinctItem, actors[0])).acceptedIds, [distinctInspection], "two genuinely distinct authoritative photos accept"); assert.deepEqual((await acceptFireAlarmV6Inspection(distinctItem, actors[0])).duplicateIds, [distinctInspection], "exact retry remains idempotent after distinct-photo acceptance");
      assert.equal((await fetch(`${origin}/v6-evidence/accepted?inspectionClientUuid=${inspectionX}`)).status, 401, "photo UUID alone is not authentication");
      const listed = await fetch(`${origin}/v6-evidence/accepted?inspectionClientUuid=${inspectionX}`, { headers: { "x-v6-user": "a" } }); assert.equal(listed.status, 200); const listedBody = await listed.json() as { evidence: Array<{ photoUuid: string; systemKey: string; fieldPath: string; formInstanceId: string }> }; assert.deepEqual(listedBody.evidence.map((item) => item.photoUuid), [photoUuid, mainPhotoUuid]); assert.equal(listedBody.evidence[0]?.systemKey, "fire_alarm_detector"); assert.equal(listedBody.evidence[0]?.fieldPath, fieldPath); assert.equal(listedBody.evidence[0]?.formInstanceId, evidence.rows[0]?.form_instance_id);
      assert.equal((await fetch(`${origin}/v6-evidence/accepted/${photoUuid}/content`, { headers: { "x-v6-user": "a" } })).status, 200, "authorized user reads accepted content");
      assert.equal((await fetch(`${origin}/v6-evidence/accepted/${unknownRowPhoto}/content`, { headers: { "x-v6-user": "b" } })).status, 404, "shared-job technician cannot read staged/unbound evidence");
      assert.deepEqual((await (await fetch(`${origin}/v6-evidence/accepted?inspectionClientUuid=${inspectionX}`, { headers: { "x-v6-user": "b" } })).json() as { evidence: unknown[] }).evidence.length, 2, "shared technician policy permits the same visible accepted Job");
      await database.query("UPDATE inspection_jobs SET technician_visible=false WHERE id=$1", [jobId]);
      assert.equal((await fetch(`${origin}/v6-evidence/accepted/${photoUuid}/content`, { headers: { "x-v6-user": "b" } })).status, 404, "inspector without current Job visibility cannot read accepted evidence");
      assert.equal((await fetch(`${origin}/v6-evidence/accepted/${photoUuid}/content`, { headers: { "x-v6-user": "admin" } })).status, 200, "admin reads accepted evidence despite technician visibility");
      await database.query("UPDATE inspection_jobs SET technician_visible=true WHERE id=$1", [jobId]);
    } finally { await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); }
    const stageRaceEvidence = async (inspectionClientUuid: string, raceJobId: string, actorUserId: number, racePhotoUuid: string, raceHash: string) => database.query(`INSERT INTO staged_inspection_evidence(photo_uuid,inspection_client_uuid,job_id,system_key,field_path,master_template_version_id,master_template_version,system_contract_sha256,uploader_user_id,request_fingerprint,source_sha256,stored_sha256,mime_type,source_size_bytes,source_width,source_height,stored_size_bytes,width,height,storage_relative_path,status) VALUES($1,$2,$3,'fire_alarm_detector',$4,$5,6,$6,$7,$8,$9,$10,'image/jpeg',1,1,1,1,1,1,$11,'staged')`, [racePhotoUuid, inspectionClientUuid, raceJobId, fieldPath, template.id, contract, actorUserId, createHash("sha256").update(`race:${racePhotoUuid}`).digest("hex"), raceHash, createHash("sha256").update(`stored:${racePhotoUuid}`).digest("hex"), `inspections/${inspectionClientUuid}/${racePhotoUuid}.jpg`]);
    const reserveRaceSession = async (inspectionClientUuid: string, raceJobId: string, actorUserId: number) => { const connection = await database.connect(); try { await connection.query("BEGIN"); await reserveFireAlarmV6Session(connection, { inspectionClientUuid, jobId: raceJobId, systemKey: "fire_alarm_detector", masterTemplateId: template.id, contractSha256: contract, actorUserId }); await connection.query("COMMIT"); } catch (error) { await connection.query("ROLLBACK").catch(() => undefined); throw error; } finally { connection.release(); } };
    const raceItem = (raceJobId: string, raceSnapshot: typeof snapshot, inspectionClientUuid: string, racePhotoUuid: string, raceHash: string) => ({ ...item, operationId: uuid(), entityId: inspectionClientUuid, payload: { ...item.payload, clientUuid: inspectionClientUuid, jobId: raceJobId, configuration: raceSnapshot.configuration, inspectionSnapshot: raceSnapshot, responses: structuredClone(raceResponses), evidenceManifest: [{ photoUuid: racePhotoUuid, fieldPath, sourceSha256: raceHash }] } });

    const acceptedFixture = async () => { const { jobId: fixtureJobId, snapshot: fixtureSnapshot } = await makeJob(); const inspectionClientUuid = uuid(); const fixturePhotoUuid = uuid(); const fixtureHash = createHash("sha256").update(`response-loss:${fixturePhotoUuid}`).digest("hex"); await reserveRaceSession(inspectionClientUuid, fixtureJobId, actors[0]); await stageRaceEvidence(inspectionClientUuid, fixtureJobId, actors[0], fixturePhotoUuid, fixtureHash); const acceptedItem = raceItem(fixtureJobId, fixtureSnapshot, inspectionClientUuid, fixturePhotoUuid, fixtureHash); assert.deepEqual((await acceptFireAlarmV6Inspection(acceptedItem, actors[0])).acceptedIds, [inspectionClientUuid], "response-loss fixture commits exactly one accepted V6 authority"); return { jobId: fixtureJobId, snapshot: fixtureSnapshot, inspectionClientUuid, photoUuid: fixturePhotoUuid, hash: fixtureHash, item: acceptedItem }; };
    const acceptedAuthority = async (inspectionClientUuid: string) => { const form = await database.query<{ form_instance_id: string; inspection_group_id: string; request_fingerprint: string; response_payload: unknown; inspection_snapshot: unknown; job_status: string; technician_visible: boolean }>(`SELECT instance.id AS form_instance_id,instance.inspection_group_id,instance.request_fingerprint,instance.response_payload,instance.inspection_snapshot,job.status AS job_status,job.technician_visible FROM master_system_form_instances instance INNER JOIN master_system_inspections inspection ON inspection.id=instance.inspection_group_id INNER JOIN inspection_jobs job ON job.id=inspection.job_id WHERE instance.client_uuid=$1`, [inspectionClientUuid]); const formId = form.rows[0]?.form_instance_id; const evidenceRows = formId ? await database.query<{ photo_uuid: string; field_path: string; source_sha256: string; stored_sha256: string; status: string; form_instance_id: string | null }>(`SELECT photo_uuid,field_path,source_sha256,stored_sha256,status,form_instance_id FROM staged_inspection_evidence WHERE form_instance_id=$1 ORDER BY photo_uuid`, [formId]) : { rows: [] }; const reservations = await database.query<{ count: number }>(`SELECT count(*)::int AS count FROM inspection_evidence_reservations WHERE inspection_client_uuid=$1`, [inspectionClientUuid]); return { form: form.rows, evidence: evidenceRows.rows, reservationCount: reservations.rows[0]?.count }; };

    const closedReplay = await acceptedFixture(); const pendingClosedInspection = uuid(); const pendingClosedPhoto = uuid(); const pendingClosedHash = createHash("sha256").update(`new-after-close:${pendingClosedPhoto}`).digest("hex"); await reserveRaceSession(pendingClosedInspection, closedReplay.jobId, actors[0]); await stageRaceEvidence(pendingClosedInspection, closedReplay.jobId, actors[0], pendingClosedPhoto, pendingClosedHash); assert.equal((await closeInspectionJob(closedReplay.jobId, { id: actors[0], username: "v6-tech-a" }, database as never)).kind, "closed", "actual production completion closes the response-loss fixture Job"); const closedBeforeRetry = await acceptedAuthority(closedReplay.inspectionClientUuid); assert.equal(closedBeforeRetry.form.length, 1); assert.deepEqual((await acceptFireAlarmV6Inspection(closedReplay.item, actors[0])).duplicateIds, [closedReplay.inspectionClientUuid], "exact original actor retry reconciles after Job close"); const closedAfterRetry = await acceptedAuthority(closedReplay.inspectionClientUuid); assert.deepEqual(closedAfterRetry, closedBeforeRetry, "closed-Job duplicate creates no accepted-authority mutation"); assert.equal(closedAfterRetry.form[0]?.job_status, "closed"); assert.equal(closedAfterRetry.form[0]?.form_instance_id, closedBeforeRetry.form[0]?.form_instance_id, "closed-Job duplicate preserves the original form instance ID");
    const foreignClosed = await acceptFireAlarmV6Inspection(closedReplay.item, actors[1]); const unknownClosed = await acceptFireAlarmV6Inspection(raceItem(closedReplay.jobId, closedReplay.snapshot, uuid(), uuid(), "8".repeat(64)), actors[1]); assert.deepEqual(foreignClosed.failed.map(({ code, message }) => ({ code, message })), unknownClosed.failed.map(({ code, message }) => ({ code, message })), "foreign accepted UUID and unknown UUID are indistinguishable after Job close"); assert.deepEqual(await acceptedAuthority(closedReplay.inspectionClientUuid), closedAfterRetry, "foreign closed replay creates no mutation of the accepted authority"); const changedClosedManifest = structuredClone(closedReplay.item) as typeof closedReplay.item; changedClosedManifest.payload.evidenceManifest[0]!.sourceSha256 = "9".repeat(64); assert.equal((await acceptFireAlarmV6Inspection(changedClosedManifest, actors[0])).failed[0]?.code, "IDEMPOTENCY_CONFLICT", "changed manifest conflicts after Job close before any new-acceptance path"); assert.equal((await acceptFireAlarmV6Inspection(raceItem(closedReplay.jobId, closedReplay.snapshot, pendingClosedInspection, pendingClosedPhoto, pendingClosedHash), actors[0])).failed[0]?.code, "JOB_ACCESS_DENIED", "brand-new acceptance into a closed Job remains denied");

    const hiddenReplay = await acceptedFixture(); await database.query("UPDATE inspection_jobs SET technician_visible=false WHERE id=$1", [hiddenReplay.jobId]); const hiddenBeforeRetry = await acceptedAuthority(hiddenReplay.inspectionClientUuid); assert.deepEqual((await acceptFireAlarmV6Inspection(hiddenReplay.item, actors[0])).duplicateIds, [hiddenReplay.inspectionClientUuid], "exact original actor retry reconciles after technician hide"); const hiddenAfterRetry = await acceptedAuthority(hiddenReplay.inspectionClientUuid); assert.deepEqual(hiddenAfterRetry, hiddenBeforeRetry, "hidden-Job duplicate creates no accepted-authority mutation"); assert.equal(hiddenAfterRetry.form[0]?.technician_visible, false); const changedHiddenResponse = structuredClone(hiddenReplay.item) as typeof hiddenReplay.item; changedHiddenResponse.payload.responses.comments = "changed after hide"; assert.equal((await acceptFireAlarmV6Inspection(changedHiddenResponse, actors[0])).failed[0]?.code, "IDEMPOTENCY_CONFLICT", "changed response conflicts after technician hide before any new-acceptance path");
    const foreignHidden = await acceptFireAlarmV6Inspection(hiddenReplay.item, actors[1]); const unknownHidden = await acceptFireAlarmV6Inspection(raceItem(hiddenReplay.jobId, hiddenReplay.snapshot, uuid(), uuid(), "7".repeat(64)), actors[1]); assert.deepEqual(foreignHidden.failed.map(({ code, message }) => ({ code, message })), unknownHidden.failed.map(({ code, message }) => ({ code, message })), "foreign accepted UUID and unknown UUID are indistinguishable after technician hide"); assert.deepEqual(await acceptedAuthority(hiddenReplay.inspectionClientUuid), hiddenAfterRetry, "foreign hidden replay creates no mutation of the accepted authority"); const { jobId: hiddenNewJobId, snapshot: hiddenNewSnapshot } = await makeJob(); const hiddenNewInspection = uuid(); const hiddenNewPhoto = uuid(); const hiddenNewHash = createHash("sha256").update(`new-after-hide:${hiddenNewPhoto}`).digest("hex"); await reserveRaceSession(hiddenNewInspection, hiddenNewJobId, actors[0]); await stageRaceEvidence(hiddenNewInspection, hiddenNewJobId, actors[0], hiddenNewPhoto, hiddenNewHash); await database.query("UPDATE inspection_jobs SET technician_visible=false WHERE id=$1", [hiddenNewJobId]); assert.equal((await acceptFireAlarmV6Inspection(raceItem(hiddenNewJobId, hiddenNewSnapshot, hiddenNewInspection, hiddenNewPhoto, hiddenNewHash), actors[0])).failed[0]?.code, "JOB_ACCESS_DENIED", "brand-new acceptance into a hidden Job remains denied");

    const { jobId: twoSessionJobId, snapshot: twoSessionSnapshot } = await makeJob(); const sessionX = uuid(); const sessionY = uuid(); const sessionXPhoto = uuid(); const sessionYPhoto = uuid(); const sessionXHash = "1".repeat(64); const sessionYHash = "2".repeat(64);
    await reserveRaceSession(sessionX, twoSessionJobId, actors[0]); await reserveRaceSession(sessionY, twoSessionJobId, actors[1]); await stageRaceEvidence(sessionX, twoSessionJobId, actors[0], sessionXPhoto, sessionXHash); await stageRaceEvidence(sessionY, twoSessionJobId, actors[1], sessionYPhoto, sessionYHash); await assert.rejects(() => reserveRaceSession(sessionX, twoSessionJobId, actors[1]), "technician B cannot take session X"); await assert.rejects(() => reserveRaceSession(sessionY, twoSessionJobId, actors[0]), "technician A cannot take session Y");
    let bothAcceptancesAtBarrier!: () => void; const bothAcceptancesReady = new Promise<void>((resolve) => { bothAcceptancesAtBarrier = resolve; }); let releaseAcceptances!: () => void; const releaseAcceptanceRace = new Promise<void>((resolve) => { releaseAcceptances = resolve; }); let acceptanceBarrierCount = 0;
    setFireAlarmV6AcceptanceTestBarrier(async (boundary) => { if (boundary !== "before_job_lock") return; acceptanceBarrierCount += 1; if (acceptanceBarrierCount === 2) bothAcceptancesAtBarrier(); await releaseAcceptanceRace; });
    let twoSessionResults: Awaited<ReturnType<typeof acceptFireAlarmV6Inspection>>[];
    try { const left = acceptFireAlarmV6Inspection(raceItem(twoSessionJobId, twoSessionSnapshot, sessionX, sessionXPhoto, sessionXHash), actors[0]); const right = acceptFireAlarmV6Inspection(raceItem(twoSessionJobId, twoSessionSnapshot, sessionY, sessionYPhoto, sessionYHash), actors[1]); await bothAcceptancesReady; releaseAcceptances(); twoSessionResults = await Promise.all([left, right]); } finally { setFireAlarmV6AcceptanceTestBarrier(undefined); }
    assert.equal(acceptanceBarrierCount, 2, "two independently connected acceptance transactions reached the database race barrier"); assert.equal(twoSessionResults!.filter((result) => result.acceptedIds.length === 1).length, 1, "exactly one distinct session wins the final authority"); assert.equal(twoSessionResults!.filter((result) => result.failed[0]?.code === "ACTIVE_INSPECTION_EXISTS").length, 1, "the losing session fails closed on the single-authority constraint");
    const twoSessionForms = await database.query<{ client_uuid: string }>(`SELECT client_uuid FROM master_system_form_instances WHERE client_uuid=ANY($1::uuid[])`, [[sessionX, sessionY]]); assert.equal(twoSessionForms.rows.length, 1, "two-session race creates exactly one authoritative form"); const winningSession = twoSessionForms.rows[0]!.client_uuid;
    const twoSessionEvidence = await database.query<{ photo_uuid: string; inspection_client_uuid: string; status: string; form_instance_id: string | null; form_client_uuid: string | null }>(`SELECT evidence.photo_uuid,evidence.inspection_client_uuid,evidence.status,evidence.form_instance_id,form.client_uuid AS form_client_uuid FROM staged_inspection_evidence evidence LEFT JOIN master_system_form_instances form ON form.id=evidence.form_instance_id WHERE evidence.photo_uuid=ANY($1::uuid[]) ORDER BY evidence.photo_uuid`, [[sessionXPhoto, sessionYPhoto]]); assert.equal(twoSessionEvidence.rows.filter((row) => row.status === "accepted").length, 1, "only winning evidence is accepted"); assert.equal(twoSessionEvidence.rows.filter((row) => row.status === "staged" && row.form_instance_id === null).length, 1, "losing evidence remains staged and unbound"); assert.ok(twoSessionEvidence.rows.every((row) => row.form_client_uuid === null || row.form_client_uuid === row.inspection_client_uuid), "no cross-session evidence binding exists"); assert.equal(twoSessionEvidence.rows.find((row) => row.inspection_client_uuid === winningSession)?.status, "accepted", "accepted evidence preserves its uploader session identity"); assert.equal((await database.query<{ count: number }>(`SELECT count(*)::int AS count FROM master_system_inspections WHERE job_id=$1 AND system_key='fire_alarm_detector'`, [twoSessionJobId])).rows[0]?.count, 1, "two-session race creates no duplicate inspection group");

    const { jobId: acceptanceWinsJobId, snapshot: acceptanceWinsSnapshot } = await makeJob(); const acceptanceWinsSession = uuid(); const acceptanceWinsPhoto = uuid(); const acceptanceWinsHash = "3".repeat(64); await reserveRaceSession(acceptanceWinsSession, acceptanceWinsJobId, actors[0]); await stageRaceEvidence(acceptanceWinsSession, acceptanceWinsJobId, actors[0], acceptanceWinsPhoto, acceptanceWinsHash); let acceptanceHasJobLock!: () => void; const acceptanceJobLocked = new Promise<void>((resolve) => { acceptanceHasJobLock = resolve; }); let releaseAcceptanceCommit!: () => void; const acceptanceCommitGate = new Promise<void>((resolve) => { releaseAcceptanceCommit = resolve; });
    setFireAlarmV6AcceptanceTestBarrier(async (boundary) => { if (boundary === "after_job_lock") { acceptanceHasJobLock(); await acceptanceCommitGate; } });
    let acceptanceWinsResult: Awaited<ReturnType<typeof acceptFireAlarmV6Inspection>>;
    try { const acceptance = acceptFireAlarmV6Inspection(raceItem(acceptanceWinsJobId, acceptanceWinsSnapshot, acceptanceWinsSession, acceptanceWinsPhoto, acceptanceWinsHash), actors[0]); await acceptanceJobLocked; const completion = closeInspectionJob(acceptanceWinsJobId, { id: actors[0], username: "v6-tech-a" }, database as never); releaseAcceptanceCommit(); acceptanceWinsResult = await acceptance; const completionResult = await completion; assert.deepEqual(acceptanceWinsResult.acceptedIds, [acceptanceWinsSession], "acceptance commits before the waiting production completion transaction"); assert.equal(completionResult.kind, "closed", "completion sees and closes the accepted authority"); assert.equal(completionResult.kind === "closed" && completionResult.alreadyCompleted, false); } finally { setFireAlarmV6AcceptanceTestBarrier(undefined); }
    const acceptanceWinsState = await database.query<{ status: string; evidence_status: string; form_instance_id: string | null }>(`SELECT job.status,evidence.status AS evidence_status,evidence.form_instance_id FROM inspection_jobs job INNER JOIN staged_inspection_evidence evidence ON evidence.job_id=job.id WHERE job.id=$1 AND evidence.photo_uuid=$2`, [acceptanceWinsJobId, acceptanceWinsPhoto]); assert.deepEqual(acceptanceWinsState.rows[0] && { status: acceptanceWinsState.rows[0].status, evidenceStatus: acceptanceWinsState.rows[0].evidence_status, bound: acceptanceWinsState.rows[0].form_instance_id !== null }, { status: "closed", evidenceStatus: "accepted", bound: true }, "acceptance-wins commits an immutable form/evidence binding before close");

    const { jobId: closureWinsJobId, snapshot: closureWinsSnapshot } = await makeJob(); const closureWinnerSession = uuid(); const closureWinnerPhoto = uuid(); const closureWinnerHash = "4".repeat(64); await reserveRaceSession(closureWinnerSession, closureWinsJobId, actors[0]); await stageRaceEvidence(closureWinnerSession, closureWinsJobId, actors[0], closureWinnerPhoto, closureWinnerHash); assert.deepEqual((await acceptFireAlarmV6Inspection(raceItem(closureWinsJobId, closureWinsSnapshot, closureWinnerSession, closureWinnerPhoto, closureWinnerHash), actors[0])).acceptedIds, [closureWinnerSession], "closure race fixture has the accepted authority required by production completion"); const closureLoserSession = uuid(); const closureLoserPhoto = uuid(); const closureLoserHash = "5".repeat(64); await reserveRaceSession(closureLoserSession, closureWinsJobId, actors[1]); await stageRaceEvidence(closureLoserSession, closureWinsJobId, actors[1], closureLoserPhoto, closureLoserHash); let closeHasJobLock!: () => void; const closeJobLocked = new Promise<void>((resolve) => { closeHasJobLock = resolve; }); let releaseClose!: () => void; const closeGate = new Promise<void>((resolve) => { releaseClose = resolve; });
    setJobCompletionTestBarrier(async () => { closeHasJobLock(); await closeGate; });
    try { const closing = closeInspectionJob(closureWinsJobId, { id: actors[0], username: "v6-tech-a" }, database as never); await closeJobLocked; const losingAcceptance = acceptFireAlarmV6Inspection(raceItem(closureWinsJobId, closureWinsSnapshot, closureLoserSession, closureLoserPhoto, closureLoserHash), actors[1]); releaseClose(); const closingResult = await closing; const losingResult = await losingAcceptance; assert.equal(closingResult.kind, "closed", "actual production completion wins the job-row lock"); assert.equal(losingResult.failed[0]?.code, "JOB_ACCESS_DENIED", "post-close V6 acceptance fails closed before authority changes"); } finally { setJobCompletionTestBarrier(undefined); }
    const closureWinsState = await database.query<{ status: string; client_uuid: string; evidence_status: string; form_instance_id: string | null }>(`SELECT job.status,form.client_uuid,evidence.status AS evidence_status,evidence.form_instance_id FROM inspection_jobs job INNER JOIN staged_inspection_evidence evidence ON evidence.job_id=job.id LEFT JOIN master_system_form_instances form ON form.id=evidence.form_instance_id WHERE job.id=$1 AND evidence.photo_uuid=$2`, [closureWinsJobId, closureLoserPhoto]); assert.deepEqual(closureWinsState.rows[0] && { status: closureWinsState.rows[0].status, clientUuid: closureWinsState.rows[0].client_uuid, evidenceStatus: closureWinsState.rows[0].evidence_status, bound: closureWinsState.rows[0].form_instance_id !== null }, { status: "closed", clientUuid: null, evidenceStatus: "staged", bound: false }, "closure-wins leaves the losing V6 evidence staged, unbound, and without partial authority");
    const replay = await acceptFireAlarmV6Inspection(item, actors[0]); assert.deepEqual(replay.duplicateIds, [inspectionX]);
    const changedManifest = await acceptFireAlarmV6Inspection({ ...item, operationId: uuid(), payload: { ...item.payload, evidenceManifest: item.payload.evidenceManifest.map((entry, index) => index === 0 ? { ...entry, sourceSha256: "9".repeat(64) } : entry) } }, actors[0]); assert.equal(changedManifest.failed[0]?.code, "IDEMPOTENCY_CONFLICT", "altered manifest conflicts after accepted identity");
    const changedResponse = structuredClone(item) as typeof item; changedResponse.operationId = uuid(); changedResponse.payload.responses.comments = "changed"; const responseConflict = await acceptFireAlarmV6Inspection(changedResponse, actors[0]); assert.equal(responseConflict.failed[0]?.code, "IDEMPOTENCY_CONFLICT", "altered response conflicts after accepted identity");
    assert.equal((await database.query<{ count: number }>(`SELECT count(*)::int AS count FROM master_system_form_instances WHERE client_uuid=$1`, [inspectionX])).rows[0]?.count, 1, "concurrency/retry never duplicates the form");
    assert.equal((await database.query<{ count: number }>(`SELECT count(*)::int AS count FROM staged_inspection_evidence WHERE form_instance_id=$1 AND status='accepted'`, [evidence.rows[0]?.form_instance_id])).rows[0]?.count, 2, "concurrency/retry never duplicates bindings");
    const mainAuthorityBeforeForeignProbe = await acceptedAuthority(inspectionX); const unknownVisibleInspection = uuid(); const otherActor = await acceptFireAlarmV6Inspection(item, actors[1]); const unknownVisible = await acceptFireAlarmV6Inspection(raceItem(jobId, snapshot, unknownVisibleInspection, uuid(), "6".repeat(64)), actors[1]); assert.equal(otherActor.acceptedIds.length, 0, "second technician cannot accept first session"); assert.deepEqual(otherActor.failed.map(({ code, message }) => ({ code, message })), unknownVisible.failed.map(({ code, message }) => ({ code, message })), "foreign accepted UUID and unknown UUID are indistinguishable in a shared visible Job"); assert.deepEqual(await acceptedAuthority(inspectionX), mainAuthorityBeforeForeignProbe, "foreign shared-Job probe creates no mutation of the accepted authority"); assert.equal((await database.query<{ count: number }>(`SELECT count(*)::int AS count FROM inspection_evidence_reservations WHERE inspection_client_uuid=$1`, [unknownVisibleInspection])).rows[0]?.count, 0, "failed unknown probe rolls back its provisional reservation");
  } finally { await database.end(); await rm(uploadsPath, { recursive: true, force: true }); }
});
