import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { once } from "node:events";
import express from "express";
import pg from "pg";
import sharp from "sharp";
import { runMigrations } from "../db/migrations.js";
import { v7EvidenceContractSha256 } from "../inspections/evidence/v7EvidenceContracts.js";
import { closeInspectionJob } from "../jobs/jobCompletion.js";
import { loadFinalServiceReport, renderFinalServiceReportPdf } from "../reports/finalServiceReport.js";
import { acceptFireAlarmV7Inspection } from "./fireAlarmV7Acceptance.js";
import { masterSystemInspectionsRouter } from "../routes/masterSystemInspections.js";
import { v7IntegrationDatabaseUrl } from "./v7IntegrationTestDatabase.js";

const databaseUrl = v7IntegrationDatabaseUrl();
const id = () => randomUUID(); const timestamp = "2026-09-02T00:00:00.000Z";
const result = (value: "good" | "poor" | "not_relevant", remarks = "") => ({ result: value, remarks });

test("Fire Alarm V7 accepts frozen current-Poor evidence, retries after closure, and PDF-embeds accepted image", { skip: !databaseUrl }, async () => {
  const database = new pg.Pool({ connectionString: databaseUrl }); const isolationLock = await database.connect(); await isolationLock.query("SELECT pg_advisory_lock(819276)"); const uploads = path.join(tmpdir(), `phase8f-fire-alarm-v7-${id()}`); process.env.UPLOADS_PATH = uploads;
  try {
    await database.query("DROP SCHEMA public CASCADE; CREATE SCHEMA public;"); await runMigrations(database);
    const template = (await database.query<{ id: string; definition: unknown }>("SELECT template.id,system.definition FROM master_service_report_templates template INNER JOIN master_service_report_systems system ON system.template_version_id=template.id WHERE template.version=7 AND system.system_key='fire_alarm_detector'")).rows[0]!;
    const customer = id(), revision = id(), enabled = id(), job = id(), clientUuid = id(); const actor = (await database.query<{ id: number }>("INSERT INTO users(username,password_hash,role) VALUES($1,'x','inspector') RETURNING id", [`fire-v7-${id()}`])).rows[0]!.id; const foreign = (await database.query<{ id: number }>("INSERT INTO users(username,password_hash,role) VALUES($1,'x','inspector') RETURNING id", [`fire-v7-foreign-${id()}`])).rows[0]!.id; const admin = (await database.query<{ id: number }>("INSERT INTO users(username,password_hash,role) VALUES($1,'x','admin') RETURNING id", [`fire-v7-admin-${id()}`])).rows[0]!.id;
    await database.query("INSERT INTO customers(id,customer_code,display_name,is_demo) VALUES($1,$2,'Fire Alarm V7',false)", [customer, `FA-${customer}`]);
    await database.query("INSERT INTO customer_configuration_revisions(id,customer_id,template_version_id,revision,status) VALUES($1,$2,$3,1,'active')", [revision, customer, template.id]);
    await database.query("INSERT INTO customer_enabled_systems(id,configuration_revision_id,template_version_id,system_key,sort_order,system_configuration) VALUES($1,$2,$3,'fire_alarm_detector',1,'{}')", [enabled, revision, template.id]);
    const system = { enabledSystemId: enabled, systemKey: "fire_alarm_detector", displayName: "Fire Alarm / Detector System", sortOrder: 5, definitionStatus: "confirmed", zones: [], locations: [] };
    const snapshot = { schemaVersion: 1, customer: { id: customer, code: `FA-${customer}`, displayName: "Fire Alarm V7" }, site: { id: id(), displayName: "Fire Alarm V7 Site" }, configuration: { revisionId: revision, revisionNumber: 1 }, template: { id: template.id, code: "MFE-FSSR", name: "MFE Fire System Service Report Template", version: 7 }, enabledSystems: [system] };
    await database.query("INSERT INTO inspection_jobs(id,master_template_version_id,job_reference,title,status,is_sample,technician_visible,customer_id,customer_configuration_revision_id,configuration_snapshot,service_date) VALUES($1,$2,$3,'Fire Alarm V7','open',false,true,$4,$5,$6,'2026-09-02')", [job, template.id, `FA-${job}`, customer, revision, snapshot]);
    const photoUuid = id(); const image = await sharp({ create: { width: 2, height: 2, channels: 3, background: "red" } }).jpeg().toBuffer(); const sourceSha256 = createHash("sha256").update(image).digest("hex"); const relative = `inspections/${clientUuid}/${photoUuid}.jpg`; await mkdir(path.dirname(path.join(uploads, ...relative.split("/"))), { recursive: true }); await writeFile(path.join(uploads, ...relative.split("/")), image);
    const contract = v7EvidenceContractSha256(template.definition); await database.query("INSERT INTO inspection_evidence_reservations(inspection_client_uuid,job_id,system_key,master_template_version_id,master_template_version,system_contract_sha256,reserved_by_user_id) VALUES($1,$2,'fire_alarm_detector',$3,7,$4,$5)", [clientUuid, job, template.id, contract, actor]);
    await database.query("INSERT INTO staged_inspection_evidence(photo_uuid,inspection_client_uuid,job_id,system_key,field_path,master_template_version_id,master_template_version,system_contract_sha256,uploader_user_id,request_fingerprint,source_sha256,stored_sha256,mime_type,source_size_bytes,source_width,source_height,stored_size_bytes,width,height,storage_relative_path,status) VALUES($1,$2,$3,'fire_alarm_detector','charger_batteries.charger_battery_checks.battery',$4,7,$5,$6,$7,$8,$8,'image/jpeg',$9,2,2,$9,2,2,$10,'staged')", [photoUuid, clientUuid, job, template.id, contract, actor, createHash("sha256").update(`stage:${photoUuid}`).digest("hex"), sourceSha256, image.length, relative]);
    const response = { schemaVersion: 2, controlPanelLocation: "Lobby", primaryDeviceRows: [{ rowUuid: id(), source: "technician", configuredLocationId: null, configuredRowOrdinal: null, zoneSnapshot: null, locationSnapshot: null, displaySequence: 1, assetReference: "", alarmZone: "Lobby", location: "Lobby", manualCallPoint: ["normal", "test"], flowSwitch: ["test"], heatDetector: ["isolation"], smokeDetector: ["normal"], remarks: "" }], chargerAndBatteries: { main_supply: result("good"), battery: result("poor", "Battery requires replacement"), charger: result("not_relevant") }, mainFunctionKeys: { main_alarm_reset: result("good"), lamp_test: result("good"), evacuate: result("good"), ac_supply: result("good"), dc_supply: result("good"), spka_system: result("good"), alarm_lift_trip: result("good"), signal_gas_discharge: result("good") }, secondaryAlarmDeviceRows: [], comments: "V7 Fire Alarm" };
    const item = { operationId: id(), entityType: "masterSystemInspection", entityId: clientUuid, action: "create", payload: { clientUuid, jobId: job, systemKey: "fire_alarm_detector", instanceKey: "primary", configuredZoneId: null, configuredLocationId: null, displaySequence: 1, originalCreatorSnapshot: null, masterTemplate: { id: template.id, code: "MFE-FSSR", version: 7 }, configuration: { revisionId: revision, revisionNumber: 1 }, inspectionSnapshot: { schemaVersion: 2, capturedAt: timestamp, job: { id: job, reference: "client", title: "client" }, customer: snapshot.customer, configuration: snapshot.configuration, template: snapshot.template, system: { client: "not-authority" } }, responses: response, evidenceManifest: [{ photoUuid, fieldPath: "charger_batteries.charger_battery_checks.battery", sourceSha256 }], performedAt: timestamp } };
    const accepted = await acceptFireAlarmV7Inspection(item, actor); assert.deepEqual(accepted.acceptedIds, [clientUuid], JSON.stringify(accepted));
    const reorderedRetry = structuredClone(item); reorderedRetry.operationId = id(); reorderedRetry.payload.responses.primaryDeviceRows[0].manualCallPoint = ["test", "normal"];
    assert.deepEqual((await acceptFireAlarmV7Inspection(reorderedRetry, actor)).duplicateIds, [clientUuid], "a reordered V7 detector-state retry is normalized to the accepted authority");
    assert.deepEqual((await database.query<{ status: string }>("SELECT status FROM staged_inspection_evidence WHERE photo_uuid=$1", [photoUuid])).rows.map((row) => row.status), ["accepted"]);
    const app = express(); app.use((request, _response, next) => { const mode = request.header("x-test-actor"); request.currentUser = mode === "foreign" ? { id: foreign, username: "foreign", role: "inspector" } : mode === "admin" ? { id: admin, username: "admin", role: "admin" } : { id: actor, username: "fire-v7", role: "inspector" }; next(); }); app.use(masterSystemInspectionsRouter); const server = app.listen(0, "127.0.0.1"); await once(server, "listening");
    try { const origin = `http://127.0.0.1:${(server.address() as { port: number }).port}/fire-alarm-inspections/${clientUuid}`; const detail = await fetch(origin); assert.equal(detail.status, 200, "Accepted Detail resolves the frozen V7 authority"); assert.equal((await fetch(origin, { headers: { "x-test-actor": "foreign" } })).status, 404, "a different inspector cannot read Fire Alarm V7 accepted detail"); assert.equal((await fetch(origin, { headers: { "x-test-actor": "admin" } })).status, 200, "admin can read Fire Alarm V7 accepted detail"); await database.query("UPDATE inspection_jobs SET technician_visible=false WHERE id=$1", [job]); assert.equal((await fetch(origin)).status, 200, "owner retains accepted detail after the job is hidden"); assert.equal((await fetch(origin, { headers: { "x-test-actor": "admin" } })).status, 200, "admin retains accepted detail after the job is hidden"); await database.query("UPDATE inspection_jobs SET technician_visible=true WHERE id=$1", [job]); } finally { await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); }
    const probe = structuredClone(item); probe.operationId = id(); probe.entityId = id(); probe.payload.clientUuid = probe.entityId; await database.query("UPDATE inspection_jobs SET technician_visible=false WHERE id=$1", [job]); const hiddenFailure = (await acceptFireAlarmV7Inspection(probe, actor)).failed[0]; const unknown = structuredClone(probe); unknown.payload.jobId = id(); const unknownFailure = (await acceptFireAlarmV7Inspection(unknown, actor)).failed[0]; await database.query("UPDATE inspection_jobs SET technician_visible=true WHERE id=$1", [job]); const closed = await closeInspectionJob(job, { id: actor, username: "fire-v7" }, database as never); assert.equal(closed.kind, "closed"); assert.deepEqual((await acceptFireAlarmV7Inspection(item, actor)).duplicateIds, [clientUuid], "exact retry succeeds after closure"); const closedFailure = (await acceptFireAlarmV7Inspection(probe, actor)).failed[0]; assert.deepEqual(hiddenFailure, closedFailure, "hidden and closed new V7 requests share one failure response"); assert.deepEqual(unknownFailure, closedFailure, "unknown and closed new V7 requests share one failure response");
    const report = await loadFinalServiceReport(job, database); const section = report.sections.find((value) => value.systemKey === "fire_alarm_detector")!; assert.equal(section.evidence.length, 1); assert.equal(section.evidence[0]!.content.equals(image), true); const pdf = await renderFinalServiceReportPdf(report); assert.equal(pdf.includes(image), true, "accepted Fire Alarm V7 JPEG is embedded in PDF");
  } finally { await isolationLock.query("SELECT pg_advisory_unlock(819276)").catch(() => undefined); isolationLock.release(); await database.end(); await rm(uploads, { recursive: true, force: true }); }
});
