import assert from "node:assert/strict";
import test from "node:test";
import { pool } from "../db/pool.js";
import { wetChemicalV4 } from "../inspections/templates/masterServiceReportV4.js";
import { syncCo2FormInstances } from "./co2FormInstanceSync.js";

type R = Record<string, any>; let n=9000; const id=()=>`00000000-0000-4000-8000-${String(n++).padStart(12,"0")}`;
const checklist=(keys:string[])=>Object.fromEntries(keys.map((key,index)=>[key === "spka_system" ? "signal_alarm_to_mfap" : key,{result:index%2?"poor":"good",remarks:`${key} remark`}]));
function fixture(){const job=id(),template=id(),revision=id(),enabled=id(),zone=id(),location=id();const system={enabledSystemId:enabled,systemKey:"wet_chemical",displayName:"Wet Chemical System",sortOrder:6,definitionStatus:"confirmed",zones:[{id:zone,enabledSystemId:enabled,key:"kitchen",displayName:"Kitchen",sortOrder:1}],locations:[{id:location,enabledSystemId:enabled,zoneId:zone,key:"hood",displayName:"Kitchen Hood",presetRowCount:1,rowPreset:{},sortOrder:1}]};const snapshot={customer:{id:id(),code:"TEST",displayName:"Test"},configuration:{revisionId:revision,revisionNumber:1},template:{id:template,code:"MFE-FSSR",name:"Master",version:4},enabledSystems:[system]};return{job,template,revision,zone,location,snapshot};}
function payload(f:any){const clientUuid=id(),performedAt="2026-08-11T00:00:00.000Z";return{clientUuid,jobId:f.job,systemKey:"wet_chemical",instanceKey:`location:${f.location}`,configuredZoneId:f.zone,configuredLocationId:f.location,displaySequence:1,originalCreatorSnapshot:null,masterTemplate:{id:f.template,code:"MFE-FSSR",version:4},configuration:{revisionId:f.revision,revisionNumber:1},inspectionSnapshot:{schemaVersion:1,capturedAt:performedAt,job:{id:f.job,reference:"Client supplied reference",title:"Client supplied title"},customer:{id:id(),code:"CLIENT",displayName:"Client supplied customer"},configuration:{revisionId:f.revision,revisionNumber:1},template:{id:f.template,code:"MFE-FSSR",version:4},system:{client:"snapshot is not authority"},instance:{instanceKey:`location:${f.location}`,displaySequence:1}},responses:{controlPanelLocation:"Kitchen Panel",detectorRows:[{rowUuid:id(),displaySequence:1,alarmZone:"Kitchen",location:"Kitchen Hood",heatDetectorStatus:"normal",smokeDetectorStatus:"test",remarks:"both columns retained"}],chargerAndBatteries:checklist(["main_supply","battery","charger"]),physicalOutlook:checklist(["wet_chemical_cylinder","electric_actuator","manual_release_key","alarm_bell","twin_flashing_light","manual_pull_station","high_pressure_hose","discharge_nozzle"]),mainFunctionKeys:checklist(["main_alarm_reset","lamp_test","evacuate","ac_supply","dc_supply","spka_system"]),comments:"server must preserve this"},performedAt};}
class DB{jobs=new Map<string,R>();groups=new Map<string,string>();forms=new Map<string,R>();add(f:any){this.jobs.set(f.job,{status:"open",job_reference:"WET-TEST",title:"Wet Chemical",master_template_version_id:f.template,customer_configuration_revision_id:f.revision,configuration_snapshot:f.snapshot});} client={query:async(sql:string,p:any[]=[])=>{if(["BEGIN","COMMIT","ROLLBACK"].includes(sql))return{rowCount:0,rows:[]};if(sql.startsWith("SELECT status, job_reference")){const row=this.jobs.get(p[0]);return{rowCount:row?1:0,rows:row?[row]:[]};}if(sql.startsWith("SELECT definition"))return{rowCount:1,rows:[{definition:wetChemicalV4,definition_status:"confirmed"}]};if(sql.startsWith("SELECT request_fingerprint")){const row=this.forms.get(p[0]);return{rowCount:row?1:0,rows:row?[{request_fingerprint:row.fingerprint}]:[]};}if(sql.startsWith("INSERT INTO master_system_inspections")){this.groups.set(`${p[1]}:${p[2]}`,p[0]);return{rowCount:1,rows:[]};}if(sql.startsWith("SELECT id FROM master_system_inspections")){const group=this.groups.get(`${p[0]}:${p[1]}`);return{rowCount:group?1:0,rows:group?[{id:group}]:[]};}if(sql.startsWith("SELECT 1 FROM master_system_form_instances"))return{rowCount:0,rows:[]};if(sql.startsWith("INSERT INTO master_system_form_instances")){this.forms.set(p[2],{fingerprint:p[13],snapshot:p[11],responses:p[12]});return{rowCount:1,rows:[]};}throw Error(`Unexpected query ${sql}`);},release:()=>undefined};counts(){return{groups:this.groups.size,forms:this.forms.size}}}
function envelope(p:R){return{operationId:id(),entityType:"masterSystemFormInstance",entityId:p.clientUuid,action:"create",payload:p};}
test("Wet Chemical production sync validates outer configured identity and preserves authoritative acceptance",async()=>{const original=(pool as any).connect;try{await test("matrix",async t=>{const run=async(mut?: (p:R)=>void)=>{const db=new DB(),f=fixture(),p=payload(f);db.add(f);mut?.(p);(pool as any).connect=async()=>db.client;return{db,p,result:await syncCo2FormInstances([envelope(p)],42)}};const runItem=async(mut:(item:R)=>void)=>{const db=new DB(),f=fixture(),p=payload(f),item=envelope(p);db.add(f);mut(item);(pool as any).connect=async()=>db.client;return{db,p,item,result:await syncCo2FormInstances([item],42)}};
await t.test("1 valid configured form accepted; 12 snapshot is server authority; 13 exact response preserved",async()=>{const x=await run();assert.deepEqual(x.result,{acceptedIds:[x.p.clientUuid],duplicateIds:[],failed:[]});assert.equal(x.db.counts().forms,1);const stored=x.db.forms.get(x.p.clientUuid)!;assert.equal(stored.snapshot.job.reference,"WET-TEST");assert.deepEqual(stored.responses,x.p.responses);});
for(const [name,mut] of [["2 foreign location",(p:R)=>p.configuredLocationId=id()],["3 missing location",(p:R)=>p.configuredLocationId=null],["4 altered outer identity",(p:R)=>p.instanceKey=`location:${id()}`],["5 malformed row",(p:R)=>p.responses.detectorRows[0].extra=true],["6 invalid status",(p:R)=>p.responses.detectorRows[0].heatDetectorStatus="bad"],["10 malformed envelope",(p:R)=>p.clientUuid="bad"],["11 invalid timestamp",(p:R)=>p.performedAt="bad"]] as const)await t.test(name,async()=>{const x=await run(mut);assert.equal(x.result.failed.length,1);assert.deepEqual(x.db.counts(),{groups:0,forms:0});});
await t.test("7 exact retry duplicate and 8 altered retry conflicts",async()=>{const db=new DB(),f=fixture(),p=payload(f);db.add(f);(pool as any).connect=async()=>db.client;assert.equal((await syncCo2FormInstances([envelope(p)],42)).acceptedIds[0],p.clientUuid);assert.equal((await syncCo2FormInstances([envelope(p)],42)).duplicateIds[0],p.clientUuid);p.responses.comments="altered";assert.equal((await syncCo2FormInstances([envelope(p)],42)).failed[0].code,"IDEMPOTENCY_CONFLICT");assert.equal(db.counts().forms,1);});
await t.test("9 concurrent exact retries persist one form",async()=>{const db=new DB(),f=fixture(),p=payload(f);db.add(f);(pool as any).connect=async()=>db.client;const [a,b]=await Promise.all([syncCo2FormInstances([envelope(p)],42),syncCo2FormInstances([envelope(p)],42)]);assert.equal(a.acceptedIds.length+b.acceptedIds.length+a.duplicateIds.length+b.duplicateIds.length,2);assert.equal(db.counts().forms,1);});
await t.test("D2 strict envelope rejects malformed Wet Chemical before persistence",async()=>{const creator={source:"device_reported",userId:7,username:"technician",role:"inspector",capturedAt:"2026-08-11T00:00:00.000Z"};const malformed:Array<[string,(item:R)=>void]>=[
  ["2 malformed operationId",item=>item.operationId="bad"],
  ["2 unknown envelope key",item=>item.extra=true],
  ["3 wrong action",item=>item.action="update"],
  ["3 wrong entityType",item=>item.entityType="masterSystemInspection"],
  ["4 unknown payload key",item=>item.payload.extra=true],
  ["5 unknown template identity key",item=>item.payload.masterTemplate.extra=true],
  ["5 unknown configuration identity key",item=>item.payload.configuration.extra=true],
  ["6 non-positive creator user id",item=>item.payload.originalCreatorSnapshot={...creator,userId:0}],
  ["7 empty creator username",item=>item.payload.originalCreatorSnapshot={...creator,username:"   "}],
  ["8 overlong creator username",item=>item.payload.originalCreatorSnapshot={...creator,username:"x".repeat(161)}],
  ["9 unknown creator key",item=>item.payload.originalCreatorSnapshot={...creator,extra:true}],
  ["10 noncanonical performedAt",item=>item.payload.performedAt="2026-08-11T00:00:00Z"],
  ["10 impossible performedAt",item=>item.payload.performedAt="2026-02-30T00:00:00.000Z"],
  ["11 noncanonical capturedAt",item=>item.payload.inspectionSnapshot.capturedAt="2026-08-11T00:00:00Z"],
  ["11 impossible capturedAt",item=>item.payload.inspectionSnapshot.capturedAt="2026-02-30T00:00:00.000Z"]
];for(const [name,mut] of malformed){const x=await runItem(mut);assert.equal(x.result.failed.length,1,`${name} must reject`);assert.deepEqual(x.db.counts(),{groups:0,forms:0},`${name} must not persist`);}const valid=await runItem(item=>item.payload.originalCreatorSnapshot=creator);assert.deepEqual(valid.result,{acceptedIds:[valid.p.clientUuid],duplicateIds:[],failed:[]});assert.equal(valid.db.counts().forms,1);});
});}finally{(pool as any).connect=original;}});
