import assert from "node:assert/strict";
import test from "node:test";
import { createHash, randomUUID } from "node:crypto";
import { once } from "node:events";
import { rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import express from "express";
import pg from "pg";
import sharp from "sharp";
import { runMigrations } from "../db/migrations.js";
import { stagedEvidenceRouter } from "../routes/stagedEvidence.js";
import { masterSystemInspectionsRouter } from "../routes/masterSystemInspections.js";
import { syncRouter } from "../routes/sync.js";
import { v7EvidenceContractSha256 } from "../inspections/evidence/v7EvidenceContracts.js";
import { syncCo2FormInstances } from "./co2FormInstanceSync.js";
import { loadFinalServiceReport, renderFinalServiceReportPdf } from "../reports/finalServiceReport.js";
import { hashPassword } from "../auth/passwords.js";
import { v7IntegrationDatabaseUrl } from "./v7IntegrationTestDatabase.js";

const databaseUrl = v7IntegrationDatabaseUrl();
const keepLiveBrowserFixture = process.env.WET_CHEMICAL_V7_LIVE_BROWSER_SEED === "1";
const id = () => randomUUID(); const time = "2026-09-01T00:00:00.000Z";
const result = (value: "good" | "poor" | "not_relevant", remarks = "") => ({ result: value, remarks });
const checklist = (keys: readonly string[], poor: string, notRelevant: string) => Object.fromEntries(keys.map((key) => [key, key === poor ? result("poor", key === "main_supply" ? "Runtime Wet Chemical Poor A" : "Runtime Wet Chemical Poor B") : key === notRelevant ? result("not_relevant") : result("good")]));

test("Wet Chemical V7 uses the shared staged-evidence authority without widening V4", { skip: !databaseUrl }, async () => {
  const database = new pg.Pool({ connectionString: databaseUrl }); const isolationLock = await database.connect(); await isolationLock.query("SELECT pg_advisory_lock(819276)"); const uploads = keepLiveBrowserFixture ? process.env.UPLOADS_PATH : path.join(tmpdir(), `phase8f-wet-v7-${id()}`); assert.ok(uploads, "live-browser fixture requires UPLOADS_PATH"); process.env.UPLOADS_PATH = uploads;
  try {
    await database.query("DROP SCHEMA public CASCADE; CREATE SCHEMA public;"); await runMigrations(database);
    const template = (await database.query<{ id: string; definition: unknown }>("SELECT template.id,system.definition FROM master_service_report_templates template INNER JOIN master_service_report_systems system ON system.template_version_id=template.id WHERE template.version=7 AND system.system_key='wet_chemical'")).rows[0]!;
    const customer=id(), revision=id(), enabled=id(), zone=id(), location=id(), locationB=id(), locationC=id(), job=id(), client=id();
    await database.query("INSERT INTO customers(id,customer_code,display_name,is_demo) VALUES($1,$2,'Wet Chemical V7',true)",[customer,`WET-${customer}`]);
    await database.query("INSERT INTO customer_configuration_revisions(id,customer_id,template_version_id,revision,status) VALUES($1,$2,$3,1,'active')",[revision,customer,template.id]);
    await database.query("INSERT INTO customer_enabled_systems(id,configuration_revision_id,template_version_id,system_key,sort_order,system_configuration) VALUES($1,$2,$3,'wet_chemical',1,'{}')",[enabled,revision,template.id]);
    await database.query("INSERT INTO customer_system_zones(id,enabled_system_id,zone_key,display_name,sort_order) VALUES($1,$2,'k','Kitchen',1)",[zone,enabled]);
    await database.query("INSERT INTO customer_system_locations(id,enabled_system_id,zone_id,location_key,display_name,sort_order) VALUES($1,$2,$3,'a','Kitchen A',1),($4,$2,$3,'b','Kitchen B',2),($5,$2,$3,'c','Kitchen C',3)",[location,enabled,zone,locationB,locationC]);
    const system={enabledSystemId:enabled,systemKey:"wet_chemical",displayName:"Wet Chemical",sortOrder:1,definitionStatus:"confirmed",zones:[{id:zone,key:"k",displayName:"Kitchen",sortOrder:1}],locations:[{id:location,zoneId:zone,key:"a",displayName:"Kitchen A",sortOrder:1},{id:locationB,zoneId:zone,key:"b",displayName:"Kitchen B",sortOrder:2},{id:locationC,zoneId:zone,key:"c",displayName:"Kitchen C",sortOrder:3}]};
    const snapshot={schemaVersion:1,customer:{id:customer,code:`WET-${customer}`,displayName:"Wet Chemical V7"},site:{id:id(),displayName:"Wet Chemical Site"},configuration:{revisionId:revision,revisionNumber:1},template:{id:template.id,code:"MFE-FSSR",name:"MFE Fire System Service Report Template",version:7},enabledSystems:[system]};
    await database.query("INSERT INTO inspection_jobs(id,master_template_version_id,job_reference,title,status,is_sample,technician_visible,customer_id,customer_configuration_revision_id,configuration_snapshot,service_date) VALUES($1,$2,$3,'Wet Chemical V7','open',false,true,$4,$5,$6,'2026-09-01')",[job,template.id,`WET-${job}`,customer,revision,snapshot]);
    const actorUsername=keepLiveBrowserFixture ? "wet-chemical-v7-live-browser" : `wet-${id()}`, actorPassword="LiveBrowserWetChemicalV7!", foreignUsername=keepLiveBrowserFixture ? "wet-chemical-v7-live-browser-foreign" : `wet-foreign-${id()}`, foreignPassword="LiveBrowserWetChemicalV7Foreign!";const actor=(await database.query<{id:number}>("INSERT INTO users(username,password_hash,role) VALUES($1,$2,'inspector') RETURNING id",[actorUsername,keepLiveBrowserFixture ? await hashPassword(actorPassword) : "x"])).rows[0]!.id; const foreign=(await database.query<{id:number}>("INSERT INTO users(username,password_hash,role) VALUES($1,$2,'inspector') RETURNING id",[foreignUsername,keepLiveBrowserFixture ? await hashPassword(foreignPassword) : "x"])).rows[0]!.id;
    const contract=v7EvidenceContractSha256(template.definition);
    const responses={controlPanelLocation:"Kitchen A",detectorRows:[{rowUuid:id(),displaySequence:1,alarmZone:"Kitchen",location:"Kitchen A",heatDetectorStatus:["normal","test"],smokeDetectorStatus:["test"],remarks:""},{rowUuid:id(),displaySequence:2,alarmZone:"Kitchen",location:"Kitchen A",heatDetectorStatus:["isolation"],smokeDetectorStatus:["normal"],remarks:""}],chargerAndBatteries:checklist(["main_supply","battery","charger"],"main_supply","charger"),physicalOutlook:checklist(["wet_chemical_cylinder","electric_actuator","manual_release_key","alarm_bell","twin_flashing_light","manual_pull_station","high_pressure_hose","discharge_nozzle"],"wet_chemical_cylinder","discharge_nozzle"),mainFunctionKeys:checklist(["main_alarm_reset","lamp_test","evacuate","ac_supply","dc_supply","signal_alarm_to_mfap"],"not-a-field","signal_alarm_to_mfap"),comments:""};
    const app=express();app.use(express.json());app.use((request,_response,next)=>{const mode=request.header("x-test-actor");if(mode!=="none")request.currentUser={id:mode==="foreign"?foreign:actor,username:"wet",role:"inspector"};next();});app.use(stagedEvidenceRouter);app.use(masterSystemInspectionsRouter);app.use(syncRouter);const server=app.listen(0,"127.0.0.1");await once(server,"listening");const origin=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
    const stage=async(clientUuid:string,fieldPath:string,color:string,options:{quality?:number;systemKey?:string;contractSha256?:string;actor?:"foreign"}={})=>{const bytes=await sharp({create:{width:2,height:2,channels:3,background:color}}).jpeg({quality:options.quality??80}).toBuffer();const photoUuid=id(),form=new FormData(),values={photoUuid,inspectionClientUuid:clientUuid,jobId:job,systemKey:options.systemKey??"wet_chemical",fieldPath,masterTemplateId:template.id,masterTemplateVersion:"7",contractSha256:options.contractSha256??contract,captureSource:"camera",capturedAt:time,sha256:createHash("sha256").update(bytes).digest("hex"),sizeBytes:String(bytes.length),width:"2",height:"2"};for(const [key,value] of Object.entries(values))form.set(key,value);form.set("file",new Blob([new Uint8Array(bytes)],{type:"image/jpeg"}),"wet.jpg");return{http:await fetch(`${origin}/v7-evidence/stage`,{method:"POST",body:form,headers:options.actor?{"x-test-actor":options.actor}:undefined}),photoUuid,fieldPath,sourceSha256:values.sha256};};
    const manifest=(...items:Array<{photoUuid:string;fieldPath:string;sourceSha256:string}>)=>items.map(({photoUuid,fieldPath,sourceSha256})=>({photoUuid,fieldPath,sourceSha256})).sort((a,b)=>a.fieldPath.localeCompare(b.fieldPath));
    const item=(clientUuid:string,locationId:string,sequence:number,evidence:ReturnType<typeof manifest>)=>({operationId:id(),entityType:"masterSystemFormInstance",entityId:clientUuid,action:"create",payload:{clientUuid,jobId:job,systemKey:"wet_chemical",instanceKey:`location:${locationId}`,configuredZoneId:zone,configuredLocationId:locationId,displaySequence:sequence,originalCreatorSnapshot:null,masterTemplate:{id:template.id,code:"MFE-FSSR",version:7},configuration:{revisionId:revision,revisionNumber:1},inspectionSnapshot:{schemaVersion:2,capturedAt:time,job:{id:job,reference:"client",title:"client"},customer:snapshot.customer,configuration:snapshot.configuration,template:snapshot.template,system:{client:"not-authority"},instance:{instanceKey:`location:${locationId}`,displaySequence:sequence}},responses:JSON.parse(JSON.stringify(responses)),evidenceManifest:evidence,performedAt:time}});
    try {
      const a=await stage(client,"charger_batteries.charger_battery_checks.main_supply","white"),b=await stage(client,"physical_outlook.physical_outlook_checks.wet_chemical_cylinder","black");assert.equal(a.http.status,201);assert.equal(b.http.status,201);const accepted=item(client,location,1,manifest(a,b));const acceptedResult=await syncCo2FormInstances([accepted],actor);assert.deepEqual(acceptedResult.acceptedIds,[client],JSON.stringify(acceptedResult));if(keepLiveBrowserFixture){const fixturePath=process.env.WET_CHEMICAL_V7_LIVE_BROWSER_FIXTURE_PATH;assert.ok(fixturePath,"live-browser fixture requires WET_CHEMICAL_V7_LIVE_BROWSER_FIXTURE_PATH");await writeFile(fixturePath,JSON.stringify({clientUuid:client,jobId:job,jobReference:`WET-${job}`,locationId:location,username:actorUsername,password:actorPassword,foreignUsername,foreignPassword,photoA:a.photoUuid,photoB:b.photoUuid}));}assert.deepEqual((await syncCo2FormInstances([accepted],actor)).duplicateIds,[client]);const changed=structuredClone(accepted);changed.payload.responses.comments="changed";assert.equal((await syncCo2FormInstances([changed],actor)).failed[0]?.code,"IDEMPOTENCY_CONFLICT");const changedManifest=structuredClone(accepted);changedManifest.payload.evidenceManifest[0]!.sourceSha256="a".repeat(64);assert.equal((await syncCo2FormInstances([changedManifest],actor)).failed[0]?.code,"IDEMPOTENCY_CONFLICT");const changedEvidence=structuredClone(accepted);changedEvidence.payload.evidenceManifest[0]!.photoUuid=id();assert.equal((await syncCo2FormInstances([changedEvidence],actor)).failed[0]?.code,"IDEMPOTENCY_CONFLICT");assert.equal((await stage(client,"main_function_key.function_checks.lamp_test","blue",{actor:"foreign"})).http.status,409);
      const detail=await fetch(`${origin}/wet-chemical-inspections/${client}`);assert.equal(detail.status,200);const body=await detail.json() as {inspection:{template:{version:number};responses:typeof responses}};assert.equal(body.inspection.template.version,7);assert.equal(body.inspection.responses.chargerAndBatteries.main_supply.remarks,"Runtime Wet Chemical Poor A");assert.equal(body.inspection.responses.physicalOutlook.wet_chemical_cylinder.remarks,"Runtime Wet Chemical Poor B");assert.equal((await fetch(`${origin}/wet-chemical-inspections/${client}`,{headers:{"x-test-actor":"foreign"}})).status,404);assert.equal((await fetch(`${origin}/v7-evidence/accepted/${a.photoUuid}/content`)).status,200);assert.equal((await fetch(`${origin}/v7-evidence/accepted/${a.photoUuid}/content`,{headers:{"x-test-actor":"none"}})).status,401);assert.equal((await fetch(`${origin}/v7-evidence/accepted/${a.photoUuid}/content`,{headers:{"x-test-actor":"foreign"}})).status,404);
      const bClient=id(),bA=await stage(bClient,"charger_batteries.charger_battery_checks.main_supply","red"),bB=await stage(bClient,"physical_outlook.physical_outlook_checks.wet_chemical_cylinder","green");assert.equal(bA.http.status,201);assert.equal(bB.http.status,201);const second=item(bClient,locationB,2,manifest(bA,bB));const missing=structuredClone(second);missing.payload.responses.chargerAndBatteries.main_supply.remarks="";assert.equal((await syncCo2FormInstances([missing],actor)).failed[0]?.code,"VALIDATION_ERROR");assert.equal((await database.query("SELECT 1 FROM master_system_form_instances WHERE client_uuid=$1",[bClient])).rowCount,0);const missingPhoto=structuredClone(second);missingPhoto.payload.evidenceManifest=missingPhoto.payload.evidenceManifest.slice(0,1);assert.equal((await syncCo2FormInstances([missingPhoto],actor)).failed[0]?.code,"VALIDATION_ERROR");const duplicate=structuredClone(second);duplicate.payload.evidenceManifest[1]!.photoUuid=duplicate.payload.evidenceManifest[0]!.photoUuid;assert.equal((await syncCo2FormInstances([duplicate],actor)).failed[0]?.code,"VALIDATION_ERROR");const duplicateSource=structuredClone(second);duplicateSource.payload.evidenceManifest[1]!.sourceSha256=duplicateSource.payload.evidenceManifest[0]!.sourceSha256;assert.equal((await syncCo2FormInstances([duplicateSource],actor)).failed[0]?.code,"VALIDATION_ERROR");const wrongJob=structuredClone(second);wrongJob.payload.jobId=id();wrongJob.payload.inspectionSnapshot.job.id=wrongJob.payload.jobId;assert.equal((await syncCo2FormInstances([wrongJob],actor)).failed[0]?.code,"JOB_ACCESS_DENIED");const wrongTemplate=structuredClone(second);wrongTemplate.payload.masterTemplate.id=id();wrongTemplate.payload.inspectionSnapshot.template.id=wrongTemplate.payload.masterTemplate.id;assert.equal((await syncCo2FormInstances([wrongTemplate],actor)).failed[0]?.code,"JOB_ACCESS_DENIED");const wrongLocation=structuredClone(second);wrongLocation.payload.configuredLocationId=location;assert.equal((await syncCo2FormInstances([wrongLocation],actor)).failed[0]?.code,"VALIDATION_ERROR");const cross=structuredClone(second);cross.payload.evidenceManifest=manifest(a,b);assert.equal((await syncCo2FormInstances([cross],actor)).failed[0]?.code,"JOB_ACCESS_DENIED");assert.deepEqual((await syncCo2FormInstances([second],actor)).acceptedIds,[bClient]);
      const cClient=id(),cA=await stage(cClient,"charger_batteries.charger_battery_checks.main_supply","white",{quality:35}),cB=await stage(cClient,"physical_outlook.physical_outlook_checks.wet_chemical_cylinder","white",{quality:95});assert.equal(cA.http.status,201);assert.equal(cB.http.status,201);const hashes=await database.query<{stored_sha256:string}>("SELECT stored_sha256 FROM staged_inspection_evidence WHERE inspection_client_uuid=$1 ORDER BY field_path",[cClient]);assert.equal(hashes.rows[0]?.stored_sha256,hashes.rows[1]?.stored_sha256);assert.equal((await syncCo2FormInstances([item(cClient,locationC,3,manifest(cA,cB))],actor)).failed[0]?.code,"JOB_ACCESS_DENIED");assert.equal((await fetch(`${origin}/v7-evidence/accepted/${cA.photoUuid}/content`)).status,404);const dClient=id(),dA=await stage(dClient,"charger_batteries.charger_battery_checks.main_supply","purple"),dB=await stage(dClient,"physical_outlook.physical_outlook_checks.wet_chemical_cylinder","yellow");assert.deepEqual((await syncCo2FormInstances([item(dClient,locationC,3,manifest(dA,dB))],actor)).acceptedIds,[dClient]);assert.equal((await stage(id(),"bad.path","orange")).http.status,400);assert.equal((await stage(id(),"charger_batteries.charger_battery_checks.main_supply","orange",{systemKey:"co2_fire_extinguisher"})).http.status,403);assert.equal((await stage(id(),"charger_batteries.charger_battery_checks.main_supply","orange",{contractSha256:"b".repeat(64)})).http.status,409);
      const foreignExisting=await (await fetch(`${origin}/sync`,{method:"POST",headers:{"content-type":"application/json","x-test-actor":"foreign"},body:JSON.stringify({items:[accepted]})})).json() as {failed:Array<{code:string;message:string}>};const unknown=structuredClone(accepted);unknown.operationId=id();unknown.entityId=id();unknown.payload.clientUuid=unknown.entityId;const foreignUnknown=await (await fetch(`${origin}/sync`,{method:"POST",headers:{"content-type":"application/json","x-test-actor":"foreign"},body:JSON.stringify({items:[unknown]})})).json() as {failed:Array<{code:string;message:string}>};assert.deepEqual(foreignExisting.failed.map(({code,message})=>({code,message})),foreignUnknown.failed.map(({code,message})=>({code,message})));
      await database.query("UPDATE inspection_jobs SET status='closed',completed_at=now(),completed_by_user_id=$2,completed_by_display_name='wet-v7' WHERE id=$1",[job,actor]);assert.deepEqual((await syncCo2FormInstances([accepted],actor)).duplicateIds,[client]);const closedChanged=structuredClone(accepted);closedChanged.payload.responses.comments="closed change";assert.equal((await syncCo2FormInstances([closedChanged],actor)).failed[0]?.code,"IDEMPOTENCY_CONFLICT");const closed=structuredClone(second);closed.operationId=id();closed.entityId=id();closed.payload.clientUuid=closed.entityId;assert.equal((await syncCo2FormInstances([closed],actor)).failed[0]?.code,"JOB_ACCESS_DENIED");const report=await loadFinalServiceReport(job,database);assert.equal(report.sections.length,3);assert.ok(report.sections.flatMap(section=>section.evidence).length===6);assert.ok(report.sections.flatMap(section=>section.fields).some(field=>field.value==="not_relevant"));const pdf=await renderFinalServiceReportPdf(report);assert.equal(pdf.subarray(0,5).toString(),"%PDF-");assert.ok((pdf.toString("latin1").match(/\/DCTDecode/g)??[]).length>=6);
    } finally { server.close(); await once(server,"close"); }
  } finally { await isolationLock.query("SELECT pg_advisory_unlock(819276)").catch(() => undefined); isolationLock.release(); await database.end(); if (!keepLiveBrowserFixture) await rm(uploads,{recursive:true,force:true}); }
});
