import type { JobSystemSnapshot, InspectionJob } from "../jobs/jobTypes";

export type GoodPoor = "good" | "poor";
export type HoseReelStatus = "Draft" | "Pending" | "Syncing" | "Synced" | "Failed";
export type DeviceReportedCreator = { source: "device_reported"; userId: number; username: string; role: "admin" | "inspector"; capturedAt: string };
export const hoseReelLimits = { comments: 4000, remarks: 2000, location: 300, assetReference: 200, rows: 250 } as const;
export type HoseReelRow = { rowUuid: string; source: "configured" | "technician"; configuredLocationId: string | null; zoneSnapshot: { id: string; key: string; displayName: string } | null; locationSnapshot: { id: string; key: string; displayName: string } | null; locationText: string; assetReference: string | null; sortOrder: number; drumResult: GoodPoor | null; hoseResult: GoodPoor | null; nozzleResult: GoodPoor | null; valveResult: GoodPoor | null; nozzleBoxResult: GoodPoor | null; remarks: string };
export type HoseReelResponses = { checklist: Record<string, { result: GoodPoor | null; remarks: string }>; measurements: { jockey_pump_pressure: { values: { cut_in: number | null; cut_out: number | null }; unit: "PSI"; result: GoodPoor | null; remarks: string }; standby_pump_cut_in: { values: { value: number | null }; unit: "PSI"; result: GoodPoor | null; remarks: string } }; drumTypes: { swing: boolean; fixed: boolean }; rows: HoseReelRow[]; comments: string };
export type HoseReelInspectionSnapshot = { schemaVersion: 1; capturedAt: string; job: { id: string; reference: string; title: string }; customer: InspectionJob["configurationSnapshot"]["customer"]; configuration: InspectionJob["configurationSnapshot"]["configuration"]; template: InspectionJob["configurationSnapshot"]["template"]; system: JobSystemSnapshot & { definition: unknown; repetitionMode: "single_with_repeatable_rows"; drumTypeCardinality: "pending_confirmation" } };
export type MasterSystemInspectionRecord = { schemaVersion: 1; clientUuid: string; jobSystemKey: string; jobId: string; systemKey: "hose_reel"; originalCreatorSnapshot?: DeviceReportedCreator | null; masterTemplate: { id: string; code: "MFE-FSSR"; version: 1 }; configuration: { revisionId: string; revisionNumber: number }; inspectionSnapshot: HoseReelInspectionSnapshot; responses: HoseReelResponses; performedAt: string; localCreatedAt: string; localUpdatedAt: string; lastSyncedAt?: string; syncStatus: HoseReelStatus; lastSyncError?: string };

export const hoseReelChecklistItems = [["saj_main_water_supply", "S.A.J Main Water Supply"], ["water_level", "Water Level"], ["automatic_refilling_facilities", "Automatic Refilling Facilities"], ["drain_and_stop_valve_positions", "Drain Valve In Close Position And All Stop Valve In Open Position"], ["pump_house_clean", "Keep Clean In Pump House"], ["standby_pump_service_items", "Stand-By Pump Oil, Fuel and Other Service Items"], ["charger_power_failure_alarm", "Battery Charger Power Failure Alarm"], ["battery_serviceable", "Battery In Good Serviceable / Function"], ["pump_failure_alarm", "Pump Run / Failure Alarm To Fire Alarm Panel"], ["pumps_auto_start", "Jockey And Stand-By Pump In Auto Start Position"], ["test_and_gate_valve_positions", "Test Valve In Close Position And All Gate Valve In Open Position"]] as const;
