import { localDatabase, type SyncOutboxItem } from "../db/localDatabase";
import type { InspectionAttachmentRecord } from "../attachments/attachmentTypes";
import type { HoseReelResponses, MasterSystemInspectionRecord, HoseReelResultColumn } from "./hoseReelTypes";
import type { AttachmentCaptureSource } from "../attachments/attachmentTypes";

export type HoseReelV7FieldPath = `hose_reel_checks.${string}` | `hose_reel_measurements.${"jockey_pump_pressure" | "standby_pump_cut_in"}` | `hose_reel_drum.hose_reel_rows.rows.${string}.${"drum" | "hose" | "nozzle" | "valve" | "nozzle_box"}`;
const rowFields: ReadonlyArray<readonly [HoseReelResultColumn, "drum" | "hose" | "nozzle" | "valve" | "nozzle_box", string]> = [["drumResult", "drum", "Drum"], ["hoseResult", "hose", "Hose"], ["nozzleResult", "nozzle", "Nozzle"], ["valveResult", "valve", "Valve"], ["nozzleBoxResult", "nozzle_box", "Nozzle Box"]];
const checkKeys = ["saj_main_water_supply", "water_level", "automatic_refilling_facilities", "drain_and_stop_valve_positions", "pump_house_clean", "standby_pump_service_items", "charger_power_failure_alarm", "battery_serviceable", "pump_failure_alarm", "pumps_auto_start", "test_and_gate_valve_positions", "trfp_duty_pump", "trfp_standby_pump"] as const;
export const isHoseReelV7EvidenceFinding = (value: unknown) => value === "not_good" || value === "complete_repair";
export function v7RequiredHoseReelFieldPaths(responses: HoseReelResponses): HoseReelV7FieldPath[] { const paths: HoseReelV7FieldPath[] = []; for (const key of checkKeys) if (isHoseReelV7EvidenceFinding(responses.checklist[key]?.result)) paths.push(`hose_reel_checks.${key}`); for (const key of ["jockey_pump_pressure", "standby_pump_cut_in"] as const) if (isHoseReelV7EvidenceFinding(responses.measurements[key].result)) paths.push(`hose_reel_measurements.${key}`); for (const row of responses.rows) for (const [field, wire] of rowFields) if (isHoseReelV7EvidenceFinding(row[field])) paths.push(`hose_reel_drum.hose_reel_rows.rows.${row.rowUuid}.${wire}`); return paths.sort(); }
export async function listHoseReelV7Photos(clientUuid: string) { return (await localDatabase.inspectionAttachments.where("inspectionClientUuid").equals(clientUuid).toArray()).filter((item) => item.systemKey === "hose_reel" && item.protocolVersion === 7); }
export function v7HoseReelManifest(attachments: InspectionAttachmentRecord[], responses: HoseReelResponses) { const required = new Set(v7RequiredHoseReelFieldPaths(responses)); return attachments.filter((item) => item.systemKey === "hose_reel" && item.protocolVersion === 7 && required.has(item.fieldPath as HoseReelV7FieldPath)).map((item) => ({ photoUuid: item.photoUuid, fieldPath: item.fieldPath, sourceSha256: item.sha256 })).sort((a, b) => a.fieldPath.localeCompare(b.fieldPath)); }
export function v7HoseReelEvidenceOutbox(attachment: InspectionAttachmentRecord): SyncOutboxItem { return { operationId: crypto.randomUUID(), entityType: "v7StagedEvidence", entityId: attachment.photoUuid, action: "create", payload: { inspectionClientUuid: attachment.inspectionClientUuid, systemKey: "hose_reel", fieldPath: attachment.fieldPath, protocolVersion: 7 }, createdAt: attachment.localCreatedAt, attempts: 0, status: "Pending", activeKey: `v7StagedEvidence:create:${attachment.photoUuid}` }; }
export function v7HoseReelSubmissionIssues(record: MasterSystemInspectionRecord, responses: HoseReelResponses, attachments: InspectionAttachmentRecord[]) { if (record.masterTemplate.version !== 7) return []; const issues: string[] = []; if (responses.schemaVersion !== 2 && responses.schemaVersion !== 3) issues.push("Hose Reel V7 response schema is invalid"); for (const key of checkKeys) if (isHoseReelV7EvidenceFinding(responses.checklist[key]?.result) && !responses.checklist[key]?.remarks.trim()) issues.push(`${key} requires its own Remark`); for (const key of ["jockey_pump_pressure", "standby_pump_cut_in"] as const) if (isHoseReelV7EvidenceFinding(responses.measurements[key].result) && !responses.measurements[key].remarks.trim()) issues.push(`${key} requires its own Remark`); for (const row of responses.rows) { if (!row.fieldRemarks || typeof row.fieldRemarks !== "object") issues.push(`Hose Reel row ${row.rowUuid} field remarks are invalid`); for (const [field, , label] of rowFields) if (isHoseReelV7EvidenceFinding(row[field]) && !row.fieldRemarks?.[field]?.trim()) issues.push(`${label} requires its own Remark`); } const required = v7RequiredHoseReelFieldPaths(responses); const attached = new Set(attachments.filter((item) => item.systemKey === "hose_reel" && item.protocolVersion === 7).map((item) => item.fieldPath)); for (const path of required) if (!attached.has(path)) issues.push(`${path} requires its own Photo`); const first = new Map<string, string>(); for (const attachment of attachments.filter((item) => required.includes(item.fieldPath as HoseReelV7FieldPath)).sort((a, b) => a.fieldPath.localeCompare(b.fieldPath))) { const prior = first.get(attachment.sha256); if (prior) issues.push(`${prior} and ${attachment.fieldPath} use the same photo; each finding needs its own photo`); else first.set(attachment.sha256, attachment.fieldPath); } return issues; }
const canonical = (value: unknown): string => Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : value && typeof value === "object" ? `{${Object.keys(value as object).sort().map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}` : JSON.stringify(value);
export async function saveHoseReelV7Photo(values: { record: MasterSystemInspectionRecord; fieldPath: HoseReelV7FieldPath; captureSource: AttachmentCaptureSource; blob: Blob; mimeType: "image/jpeg"; sizeBytes: number; width: number; height: number; sha256: string; capturedAt?: string }) { if (values.record.masterTemplate.version !== 7 || values.record.syncStatus !== "Draft") throw new Error("V7 evidence can only be changed in a Hose Reel V7 Draft"); const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(canonical(values.record.inspectionSnapshot.system.definition))); const contractSha256 = [...new Uint8Array(digest)].map((value) => value.toString(16).padStart(2, "0")).join(""); const now = new Date().toISOString(); await localDatabase.transaction("rw", localDatabase.masterSystemInspections, localDatabase.inspectionAttachments, async () => { const live = await localDatabase.masterSystemInspections.get(values.record.clientUuid) as MasterSystemInspectionRecord | undefined; if (!live || live.systemKey !== "hose_reel" || live.masterTemplate.version !== 7 || live.syncStatus !== "Draft") throw new Error("Hose Reel V7 Draft changed before evidence was saved"); const held = await listHoseReelV7Photos(live.clientUuid); const clash = held.find((item) => item.sha256 === values.sha256 && item.fieldPath !== values.fieldPath); if (clash) throw new Error(`This photo is already attached to ${clash.fieldPath}. Each finding needs its own photo.`); const existing = held.find((item) => item.fieldPath === values.fieldPath); await localDatabase.inspectionAttachments.put({ photoUuid: existing?.photoUuid ?? crypto.randomUUID(), inspectionClientUuid: live.clientUuid, systemKey: "hose_reel", fieldPath: values.fieldPath, evidencePolicyId: "v7-shared-evidence", evidencePolicyVersion: 7, captureSource: values.captureSource, blob: values.blob, mimeType: values.mimeType, sizeBytes: values.sizeBytes, width: values.width, height: values.height, sha256: values.sha256, capturedAt: values.capturedAt ?? now, localCreatedAt: existing?.localCreatedAt ?? now, localUpdatedAt: now, syncStatus: "Draft", protocolVersion: 7, masterTemplateId: live.masterTemplate.id, contractSha256 }); }); }
