import { useEffect, useState } from "react";
import type { ServerHoseReelDetail } from "./serverHoseReelApi";
import { formatClientDateTime } from "../uiPresentation";
import { hoseReelV7AcceptedEvidenceContentUrl, loadHoseReelV7AcceptedEvidence, type HoseReelV7AcceptedEvidence } from "./hoseReelV7AcceptedEvidence";

const rowFields = { drum: "drumResult", hose: "hoseResult", nozzle: "nozzleResult", valve: "valveResult", nozzle_box: "nozzleBoxResult" } as const;
const v7Groups = [["Water Tank / Pump House", ["saj_main_water_supply", "water_level", "automatic_refilling_facilities", "drain_and_stop_valve_positions", "pump_house_clean", "standby_pump_service_items", "charger_power_failure_alarm", "battery_serviceable", "pump_failure_alarm", "pumps_auto_start", "test_and_gate_valve_positions"]], ["Test Run Fire Pump 30 Minutes", ["trfp_duty_pump", "trfp_standby_pump"]]] as const;
const v7Labels: Record<string, string> = { saj_main_water_supply: "SAJ Main Water Supply", water_level: "Water Level", automatic_refilling_facilities: "Automatic Refilling Facilities", drain_and_stop_valve_positions: "Drain and Stop Valve Positions", pump_house_clean: "Pump House Clean", standby_pump_service_items: "Stand-by Pump Service Items", charger_power_failure_alarm: "Charger Power Failure Alarm", battery_serviceable: "Battery Serviceable", pump_failure_alarm: "Pump Failure Alarm", pumps_auto_start: "Pumps Auto Start", test_and_gate_valve_positions: "Test and Gate Valve Positions", trfp_duty_pump: "Duty Pump", trfp_standby_pump: "Stand-by Pump" };
const resultLabel = (value: unknown) => value === "good" ? "Good" : value === "not_good" ? "Not Good" : value === "complete_repair" ? "Complete Repair" : value === "na" ? "N.A." : value === "poor" ? "Poor" : "Not recorded";
const isFinding = (value: unknown) => value === "not_good" || value === "complete_repair";

function V7Evidence({ path, label, remark, evidence }: { path: string; label: string; remark: string; evidence: HoseReelV7AcceptedEvidence[] }) {
  const photo = evidence.find((item) => item.fieldPath === path);
  if (!photo) return <p><strong>Remark:</strong> {remark || "Not recorded"}</p>;
  const url = hoseReelV7AcceptedEvidenceContentUrl(photo.photoUuid);
  return <><p><strong>Remark:</strong> {remark || "Not recorded"}</p><a href={url} target="_blank" rel="noreferrer" className="secondary-command">View accepted photo</a><img src={url} alt={`${label} accepted evidence`} className="accepted-evidence-photo" /></>;
}

export function ServerHoseReelView({ inspection, onBack }: { inspection: ServerHoseReelDetail; onBack: () => void }) {
  const [evidence, setEvidence] = useState<HoseReelV7AcceptedEvidence[]>([]);
  const [evidenceError, setEvidenceError] = useState("");
  useEffect(() => { let current = true; if (inspection.templateVersion !== 7) { setEvidence([]); setEvidenceError(""); return () => { current = false; }; } void loadHoseReelV7AcceptedEvidence(inspection.clientUuid).then((items) => { if (current) { setEvidence(items); setEvidenceError(""); } }, () => { if (current) setEvidenceError("Accepted evidence is unavailable."); }); return () => { current = false; }; }, [inspection.clientUuid, inspection.templateVersion]);
  const responses = inspection.responses;
  if (inspection.templateVersion === 7) return <section className="hose-reel-form server-inspection-detail" aria-labelledby="accepted-hose-reel-title"><button type="button" className="secondary-command" onClick={onBack}>Back to Systems</button><header className="inspection-context"><div><p className="eyebrow">{inspection.jobReference}</p><h2 id="accepted-hose-reel-title">{inspection.systemLabel}</h2><p>{inspection.customerName}</p></div><strong className="inspection-status status-synced">Inspection Complete</strong></header><p className="success-message">Submitted {formatClientDateTime(inspection.performedAt)} · Synced by {inspection.syncedByUsername}</p>{v7Groups.map(([title, keys]) => <section key={title}><h3>{title}</h3>{keys.map((key) => { const item = responses.checklist[key]; const path = `hose_reel_checks.${key}`; return <article key={key}><p><strong>{v7Labels[key]}:</strong> {resultLabel(item?.result)}</p>{isFinding(item?.result) ? <V7Evidence path={path} label={v7Labels[key]} remark={item?.remarks ?? ""} evidence={evidence} /> : null}</article>; })}</section>)}<section><h3>Pump House Measurements</h3>{(["jockey_pump_pressure", "standby_pump_cut_in"] as const).map((key) => { const item = responses.measurements[key]; const label = key === "jockey_pump_pressure" ? "Jockey Pump Pressure" : "Stand-by Pump Cut In"; return <article className="hose-row-card" key={key}><strong>{label}</strong><p>{Object.entries(item.values).map(([field, number]) => `${field.replace("_", " ")}: ${number} ${item.unit}`).join(" - ")}</p><p>Result: {resultLabel(item.result)}</p>{isFinding(item.result) ? <V7Evidence path={`hose_reel_measurements.${key}`} label={label} remark={item.remarks} evidence={evidence} /> : null}</article>; })}</section><section><h3>Hose Reel Drum</h3><p>Drum Type: {[responses.drumTypes.swing && "Swing", responses.drumTypes.fixed && "Fixed"].filter(Boolean).join(", ") || "Not selected"}</p>{responses.rows.map((row) => <article className="hose-row-card" key={row.rowUuid}><strong>{row.assetReference || `Row ${row.sortOrder}`} - {row.locationText}</strong>{Object.entries(rowFields).map(([wire, field]) => <div key={wire}><p>{wire.replace("_", " ")}: {resultLabel(row[field])}</p>{isFinding(row[field]) ? <V7Evidence path={`hose_reel_drum.hose_reel_rows.rows.${row.rowUuid}.${wire}`} label={wire.replace("_", " ")} remark={row.fieldRemarks?.[field] ?? ""} evidence={evidence} /> : null}</div>)}<p>Remarks: {row.remarks || "None"}</p></article>)}</section>{evidenceError ? <p className="error-text">{evidenceError}</p> : null}<section><h3>Comments</h3><p>{responses.comments || "No comments"}</p></section></section>;
  const controls = inspection.displayControls!;
  return <section className="hose-reel-form server-inspection-detail"><button type="button" className="secondary-command" onClick={onBack}>Back to Systems</button><header className="inspection-context"><div><p className="eyebrow">{inspection.jobReference}</p><h2>{inspection.systemLabel}</h2><p>{inspection.customerName}</p></div><strong className="inspection-status status-synced">Inspection Complete</strong></header><p className="success-message">Submitted {formatClientDateTime(inspection.performedAt)} · Synced by {inspection.syncedByUsername}</p>{([['Water Tank', controls.checklist.waterTank], ['Pump House', controls.checklist.pumpHouse]] as const).map(([title, items]) => <section key={title}><h3>{title}</h3>{items.map((item) => <p key={item.key}><strong>{item.label}:</strong> {resultLabel(responses.checklist[item.key]?.result)}{responses.checklist[item.key]?.remarks ? ` - ${responses.checklist[item.key]?.remarks}` : ''}</p>)}</section>)}<section><h3>Measurements</h3>{controls.measurements.map((item) => { const value = responses.measurements[item.key as keyof typeof responses.measurements]; return <article className="hose-row-card" key={item.key}><strong>{item.label}</strong><p>{Object.entries(value.values).map(([key, number]) => `${item.values.find((entry) => entry.key === key)?.label}: ${number} ${value.unit}`).join(' - ')}</p><p>Result: {resultLabel(value.result)}{value.remarks ? ` - ${value.remarks}` : ''}</p></article>; })}</section><section><h3>Hose Reel Drum</h3><p>Drum Type: {[responses.drumTypes.swing && 'Swing', responses.drumTypes.fixed && 'Fixed'].filter(Boolean).join(', ') || 'Not selected'}</p>{responses.rows.map((row) => <article className="hose-row-card" key={row.rowUuid}><strong>{row.assetReference || `Row ${row.sortOrder}`} - {row.locationText}</strong>{controls.repeatableRows.resultColumns.map((column) => { const field = rowFields[column.key as keyof typeof rowFields]; return <p key={column.key}>{column.label}: {resultLabel(row[field])}</p>; })}<p>Remarks: {row.remarks || 'None'}</p></article>)}</section><section><h3>Comments</h3><p>{responses.comments || 'No comments'}</p></section></section>;
}
