import { parseFrozenHoseReelControls } from "../inspectionControls/definitionResolver";
import type { ResolvedHoseReelControls } from "../inspectionControls/definitionTypes";
import type { HoseReelResponses } from "./hoseReelTypes";

type R = Record<string, unknown>;
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const keys = ["clientUuid","serverFormInstanceId","jobId","jobReference","jobTitle","customerName","systemKey","systemLabel","instanceKey","zoneId","locationId","displaySequence","status","performedAt","receivedAt","template","configuration","responses","displayControls","deviceReportedCreatorUsername","verifiedOriginalCreatorUsername","syncedByUsername"];
const rec=(value:unknown):value is R=>typeof value==="object"&&value!==null&&!Array.isArray(value);
const exact=(value:R,expected:readonly string[])=>Object.keys(value).length===expected.length&&expected.every((key)=>Object.hasOwn(value,key));
const text=(value:unknown,max:number,required=true):value is string=>typeof value==="string"&&value.length<=max&&(!required||value.trim().length>0);
function timestamp(value:unknown):value is string{if(typeof value!=="string"||!/^[0-9]{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{6}Z$/.test(value))return false;const [y,m,d,h,n,s]=value.slice(0,19).split(/[-T:]/).map(Number),date=new Date(0);date.setUTCFullYear(y,m-1,d);date.setUTCHours(h,n,s,0);return date.getUTCFullYear()===y&&date.getUTCMonth()===m-1&&date.getUTCDate()===d&&date.getUTCHours()===h&&date.getUTCMinutes()===n&&date.getUTCSeconds()===s;}
const result=(value:unknown)=>value==="good"||value==="poor";
const v7Result=(value:unknown)=>value==="good"||value==="not_good"||value==="complete_repair"||value==="na";
const v7ChecklistKeys=["saj_main_water_supply","water_level","automatic_refilling_facilities","drain_and_stop_valve_positions","pump_house_clean","standby_pump_service_items","charger_power_failure_alarm","battery_serviceable","pump_failure_alarm","pumps_auto_start","test_and_gate_valve_positions","trfp_duty_pump","trfp_standby_pump"];
const v7RowKeys=["rowUuid","source","configuredLocationId","zoneSnapshot","locationSnapshot","locationText","assetReference","sortOrder","drumResult","hoseResult","nozzleResult","valveResult","nozzleBoxResult","remarks","fieldRemarks"];
function parseV7Responses(value:unknown):HoseReelResponses|undefined{
 if(!rec(value)||!exact(value,["schemaVersion","checklist","measurements","drumTypes","rows","comments"])||value.schemaVersion!==2||!text(value.comments,4000,false)||!rec(value.checklist)||!exact(value.checklist,v7ChecklistKeys)||!rec(value.measurements)||!exact(value.measurements,["jockey_pump_pressure","standby_pump_cut_in"])||!rec(value.drumTypes)||!exact(value.drumTypes,["swing","fixed"])||typeof value.drumTypes.swing!=="boolean"||typeof value.drumTypes.fixed!=="boolean"||!Array.isArray(value.rows)||value.rows.length<1||value.rows.length>250)return;
 for(const key of v7ChecklistKeys){const item=value.checklist[key];if(!rec(item)||!exact(item,["result","remarks"])||!v7Result(item.result)||!text(item.remarks,2000,false))return;}
 const measurement=(candidate:unknown,keys:string[])=>rec(candidate)&&exact(candidate,["values","unit","result","remarks"])&&rec(candidate.values)&&exact(candidate.values,keys)&&keys.every(key=>(candidate.values as R)[key]===null||typeof (candidate.values as R)[key]==="number"&&Number.isFinite((candidate.values as R)[key]))&&candidate.unit==="PSI"&&v7Result(candidate.result)&&text(candidate.remarks,2000,false);
 if(!measurement(value.measurements.jockey_pump_pressure,["cut_in","cut_out"])||!measurement(value.measurements.standby_pump_cut_in,["value"]))return;
 const seen=new Set<string>();for(let index=0;index<value.rows.length;index++){const row=value.rows[index];if(!rec(row)||!exact(row,v7RowKeys)||typeof row.rowUuid!=="string"||!uuid.test(row.rowUuid)||seen.has(row.rowUuid)||(row.source!=="configured"&&row.source!=="technician")||(row.source==="configured"?(typeof row.configuredLocationId!=="string"||!uuid.test(row.configuredLocationId)):row.configuredLocationId!==null)||!text(row.locationText,300)||!(row.assetReference===null||text(row.assetReference,200,false))||row.sortOrder!==index+1||![row.drumResult,row.hoseResult,row.nozzleResult,row.valveResult,row.nozzleBoxResult].every(v7Result)||!text(row.remarks,2000,false)||!rec(row.fieldRemarks)||Object.keys(row.fieldRemarks).some(key=>!["drumResult","hoseResult","nozzleResult","valveResult","nozzleBoxResult"].includes(key))||Object.values(row.fieldRemarks).some(remark=>!text(remark,2000,false)))return;if(row.source==="technician"&&(row.zoneSnapshot!==null||row.locationSnapshot!==null))return;seen.add(row.rowUuid);}
 return value as unknown as HoseReelResponses;
}
function parseResponses(value:unknown,controls:ResolvedHoseReelControls):HoseReelResponses|undefined{
 if(!rec(value)||!exact(value,["checklist","measurements","drumTypes","rows","comments"])||!text(value.comments,controls.comments.maxLength,false))return;
 const checklistKeys=[...controls.checklist.waterTank,...controls.checklist.pumpHouse].map((item)=>item.key);if(!rec(value.checklist)||!exact(value.checklist,checklistKeys))return;
 for(const key of checklistKeys){const item=value.checklist[key];if(!rec(item)||!exact(item,["result","remarks"])||!result(item.result)||!text(item.remarks,2000,false))return;}
 if(!rec(value.measurements)||!exact(value.measurements,["jockey_pump_pressure","standby_pump_cut_in"]))return;
 const measurement=(candidate:unknown,valueKeys:string[])=>rec(candidate)&&exact(candidate,["values","unit","result","remarks"])&&rec(candidate.values)&&exact(candidate.values,valueKeys)&&valueKeys.every((key)=>typeof (candidate.values as R)[key]==="number"&&Number.isFinite((candidate.values as R)[key]))&&candidate.unit==="PSI"&&result(candidate.result)&&text(candidate.remarks,2000,false);
 if(!measurement(value.measurements.jockey_pump_pressure,["cut_in","cut_out"])||!measurement(value.measurements.standby_pump_cut_in,["value"])||!rec(value.drumTypes)||!exact(value.drumTypes,["swing","fixed"])||typeof value.drumTypes.swing!=="boolean"||typeof value.drumTypes.fixed!=="boolean"||!Array.isArray(value.rows)||value.rows.length<1||value.rows.length>250)return;
 const rowKeys=["rowUuid","source","configuredLocationId","zoneSnapshot","locationSnapshot","locationText","assetReference","sortOrder","drumResult","hoseResult","nozzleResult","valveResult","nozzleBoxResult","remarks"],seen=new Set<string>();
 for(let index=0;index<value.rows.length;index++){const row=value.rows[index];if(!rec(row)||!exact(row,rowKeys)||typeof row.rowUuid!=="string"||!uuid.test(row.rowUuid)||seen.has(row.rowUuid)||(row.source!=="configured"&&row.source!=="technician")||(row.source==="configured"?!text(row.configuredLocationId,36)||!uuid.test(row.configuredLocationId):row.configuredLocationId!==null)||!text(row.locationText,300)||!(row.assetReference===null||text(row.assetReference,200,false))||row.sortOrder!==index+1||![row.drumResult,row.hoseResult,row.nozzleResult,row.valveResult,row.nozzleBoxResult].every(result)||!text(row.remarks,2000,false))return;
  if(row.source==="technician"){if(row.zoneSnapshot!==null||row.locationSnapshot!==null)return;}else{if(!rec(row.locationSnapshot)||!exact(row.locationSnapshot,["id","key","displayName","presetRowCount","rowPreset"])||row.locationSnapshot.id!==row.configuredLocationId||typeof row.locationSnapshot.id!=="string"||!uuid.test(row.locationSnapshot.id)||!text(row.locationSnapshot.key,200)||!text(row.locationSnapshot.displayName,300)||!Number.isSafeInteger(row.locationSnapshot.presetRowCount)||Number(row.locationSnapshot.presetRowCount)<0||row.locationText!==row.locationSnapshot.displayName)return;if(row.zoneSnapshot!==null&&(!rec(row.zoneSnapshot)||!exact(row.zoneSnapshot,["id","key","displayName"])||typeof row.zoneSnapshot.id!=="string"||!uuid.test(row.zoneSnapshot.id)||!text(row.zoneSnapshot.key,200)||!text(row.zoneSnapshot.displayName,300)))return;}seen.add(row.rowUuid);}
 return value as unknown as HoseReelResponses;
}
export type ServerHoseReelDetail={clientUuid:string;jobId:string;jobReference:string;jobTitle:string;customerName:string;systemKey:"hose_reel";systemLabel:"Hose Reel System";instanceKey:"primary";status:"submitted";performedAt:string;receivedAt:string;template:{id:string;code:"MFE-FSSR";version:number};configuration:{revisionId:string;revisionNumber:number};responses:HoseReelResponses;displayControls:ResolvedHoseReelControls|null;templateVersion?:7;syncedByUsername:string};
export function parseServerHoseReelDetail(value:unknown,requestedClientUuid:string,expectedJobId?:string):ServerHoseReelDetail|undefined{if(!rec(value)||!exact(value,keys)||value.clientUuid!==requestedClientUuid||typeof value.clientUuid!=="string"||!uuid.test(value.clientUuid)||typeof value.serverFormInstanceId!=="string"||!uuid.test(value.serverFormInstanceId)||typeof value.jobId!=="string"||!uuid.test(value.jobId)||(expectedJobId!==undefined&&value.jobId!==expectedJobId)||!text(value.jobReference,250)||!text(value.jobTitle,300)||!text(value.customerName,250)||value.systemKey!=="hose_reel"||value.systemLabel!=="Hose Reel System"||value.instanceKey!=="primary"||value.zoneId!==null||value.locationId!==null||value.displaySequence!==1||value.status!=="submitted"||!timestamp(value.performedAt)||!timestamp(value.receivedAt)||!rec(value.template)||!exact(value.template,["id","code","version"])||typeof value.template.id!=="string"||!uuid.test(value.template.id)||value.template.code!=="MFE-FSSR"||!Number.isSafeInteger(value.template.version)||Number(value.template.version)<1||!rec(value.configuration)||!exact(value.configuration,["revisionId","revisionNumber"])||typeof value.configuration.revisionId!=="string"||!uuid.test(value.configuration.revisionId)||!Number.isSafeInteger(value.configuration.revisionNumber)||Number(value.configuration.revisionNumber)<1||!(value.deviceReportedCreatorUsername===null||text(value.deviceReportedCreatorUsername,160))||!(value.verifiedOriginalCreatorUsername===null||text(value.verifiedOriginalCreatorUsername,160))||!text(value.syncedByUsername,160))return;const v7=value.template.version===7&&value.displayControls===null?parseV7Responses(value.responses):undefined;if(v7)return{clientUuid:value.clientUuid,jobId:value.jobId,jobReference:value.jobReference,jobTitle:value.jobTitle,customerName:value.customerName,systemKey:"hose_reel",systemLabel:"Hose Reel System",instanceKey:"primary",status:"submitted",performedAt:value.performedAt,receivedAt:value.receivedAt,template:value.template as ServerHoseReelDetail["template"],configuration:value.configuration as ServerHoseReelDetail["configuration"],responses:v7,displayControls:null,templateVersion:7,syncedByUsername:value.syncedByUsername};const controls=parseFrozenHoseReelControls(value.displayControls),responses=controls?parseResponses(value.responses,controls):undefined;if(!controls||!responses)return;return{clientUuid:value.clientUuid,jobId:value.jobId,jobReference:value.jobReference,jobTitle:value.jobTitle,customerName:value.customerName,systemKey:"hose_reel",systemLabel:"Hose Reel System",instanceKey:"primary",status:"submitted",performedAt:value.performedAt,receivedAt:value.receivedAt,template:value.template as ServerHoseReelDetail["template"],configuration:value.configuration as ServerHoseReelDetail["configuration"],responses,displayControls:controls,syncedByUsername:value.syncedByUsername};}
export async function loadServerHoseReelDetail(clientUuid:string,expectedJobId?:string){if(!uuid.test(clientUuid))throw new Error("Hose Reel inspection identifier is invalid");const response=await fetch(`/api/hose-reel-inspections/${encodeURIComponent(clientUuid)}`,{credentials:"same-origin",cache:"no-store"});if(!response.ok)throw new Error(response.status===404?"Accepted Hose Reel inspection was not found":"Server Hose Reel detail is unavailable");const body:unknown=await response.json();if(!rec(body)||!exact(body,["inspection"]))throw new Error("Server returned invalid Hose Reel accepted detail");const detail=parseServerHoseReelDetail(body.inspection,clientUuid,expectedJobId);if(!detail)throw new Error("Server returned invalid Hose Reel accepted detail");return detail;}
