import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import pg from "pg";
import sharp from "sharp";
import { runMigrations } from "../db/migrations.js";
import { fireAlarmV6ContractSha256, reserveFireAlarmV6Session } from "../inspections/evidence/fireAlarmV6Evidence.js";
import { closeInspectionJob } from "../jobs/jobCompletion.js";
import { acceptFireAlarmV6Inspection } from "../sync/fireAlarmV6Acceptance.js";
import { loadFinalServiceReport, renderFinalServiceReportPdf } from "./finalServiceReport.js";

const databaseUrl = process.env.SEED_INTEGRATION_DATABASE_URL;
const uuid = () => randomUUID();
const timestamp = "2026-08-28T00:00:00.000Z";

test("Fire Alarm V6 completed reports use only frozen accepted evidence and PDF-embed it deterministically", { skip: !databaseUrl }, async () => {
  assert.equal(new URL(databaseUrl!).port, "55432", "test requires the dedicated isolated PostgreSQL port");
  const database = new pg.Pool({ connectionString: databaseUrl }); const uploadsPath = path.join(tmpdir(), `phase8f-v6-final-report-${uuid()}`); process.env.UPLOADS_PATH = uploadsPath;
  try {
    await database.query("DROP SCHEMA public CASCADE; CREATE SCHEMA public;"); await runMigrations(database);
    const template = (await database.query<{ id: string; code: string; name: string; definition: unknown }>(`SELECT template.id,template.code,template.name,system.definition FROM master_service_report_templates template INNER JOIN master_service_report_systems system ON system.template_version_id=template.id WHERE template.version=6 AND system.system_key='fire_alarm_detector'`)).rows[0]!;
    const customerId = uuid(); const revisionId = uuid(); const enabledSystemId = uuid(); const siteId = uuid(); const actor = (await database.query<{ id: number }>("INSERT INTO users(username,password_hash,role) VALUES($1,'not-used','inspector') RETURNING id", [`v6-report-${uuid()}`])).rows[0]!.id;
    await database.query("INSERT INTO customers(id,customer_code,display_name,is_demo) VALUES($1,$2,'V6 Final Report Customer',false)", [customerId, `V6-${customerId}`]); await database.query("INSERT INTO customer_configuration_revisions(id,customer_id,template_version_id,revision,status) VALUES($1,$2,$3,1,'active')", [revisionId, customerId, template.id]); await database.query("INSERT INTO customer_enabled_systems(id,configuration_revision_id,template_version_id,system_key,sort_order,system_configuration) VALUES($1,$2,$3,'fire_alarm_detector',1,'{}')", [enabledSystemId, revisionId, template.id]); await database.query("INSERT INTO customer_sites(id,customer_id,site_code,display_name) VALUES($1,$2,'V6-REPORT','V6 Report Site')", [siteId, customerId]);
    const system = { enabledSystemId, systemKey: "fire_alarm_detector", displayName: "Fire Alarm / Detector System", sortOrder: 1, definitionStatus: "confirmed", zones: [], locations: [] }; const contract = fireAlarmV6ContractSha256(template.definition);
    const result = (value: "good" | "poor" | "not_relevant", remarks = "") => ({ result: value, remarks });
    const createFixture = async (reference: string, assetReferences: { primary?: string; secondary?: string } = { primary: "CP-1", secondary: "AD-1" }) => {
      const jobId = uuid(); const inspectionClientUuid = uuid(); const groupId = uuid(); const primaryRowUuid = uuid(); const alarmRowUuid = uuid(); const snapshot = { schemaVersion: 1, customer: { id: customerId, code: `V6-${customerId}`, displayName: "V6 Final Report Customer" }, site: { id: siteId, displayName: "V6 Report Site" }, configuration: { revisionId, revisionNumber: 1 }, template: { id: template.id, code: template.code, name: template.name, version: 6 }, enabledSystems: [system] };
      await database.query(`INSERT INTO inspection_jobs(id,master_template_version_id,job_reference,title,status,is_sample,technician_visible,customer_id,customer_configuration_revision_id,configuration_snapshot,site_id,service_date) VALUES($1,$2,$3,'V6 Final Report', 'open',false,true,$4,$5,$6,$7,'2026-08-28')`, [jobId, template.id, reference, customerId, revisionId, snapshot, siteId]);
      const reserve = await database.connect(); try { await reserve.query("BEGIN"); await reserveFireAlarmV6Session(reserve, { inspectionClientUuid, jobId, systemKey: "fire_alarm_detector", masterTemplateId: template.id, contractSha256: contract, actorUserId: actor }); await reserve.query("COMMIT"); } finally { reserve.release(); }
      const responses = { schemaVersion: 2, controlPanelLocation: "Main lobby panel", primaryDeviceRows: [{ rowUuid: primaryRowUuid, source: "technician", configuredLocationId: null, configuredRowOrdinal: null, zoneSnapshot: null, locationSnapshot: null, displaySequence: 1, ...("primary" in assetReferences ? { assetReference: assetReferences.primary } : {}), alarmZone: "Lobby", location: "Main Lobby", manualCallPoint: "normal", flowSwitch: "test", heatDetector: "isolation", smokeDetector: "normal", remarks: "Primary row general remark" }], chargerAndBatteries: { main_supply: result("good"), battery: result("poor", "Battery capacity below threshold"), charger: result("not_relevant") }, mainFunctionKeys: { main_alarm_reset: result("good"), lamp_test: result("good"), evacuate: result("not_relevant"), ac_supply: result("good"), dc_supply: result("good"), spka_system: result("good"), alarm_lift_trip: result("good"), signal_gas_discharge: result("good") }, secondaryAlarmDeviceRows: [{ rowUuid: alarmRowUuid, source: "technician", configuredLocationId: null, configuredRowOrdinal: null, zoneSnapshot: null, locationSnapshot: null, displaySequence: 1, ...("secondary" in assetReferences ? { assetReference: assetReferences.secondary } : {}), location: "Pump Room", alarmBell: "poor", manualCallPoint: "poor", remarks: "Alarm-device row general remark", fieldRemarks: { alarmBell: "Alarm bell does not sound", manualCallPoint: "Manual call point cover damaged" } }], comments: "V6 accepted report comments" };
      const fields = ["charger_batteries.charger_battery_checks.battery", `alarm_devices.alarm_device_rows.rows.${alarmRowUuid}.alarm_bell`, `alarm_devices.alarm_device_rows.rows.${alarmRowUuid}.manual_call_point`] as const; const stagedOnlyField = "charger_batteries.charger_battery_checks.charger";
      const colors = ["red", "green", "blue", "black"] as const; const evidence = await Promise.all(colors.map(async (color, index) => ({ fieldPath: index < fields.length ? fields[index]! : stagedOnlyField, photoUuid: uuid(), content: await sharp({ create: { width: 12 + index, height: 12 + index, channels: 3, background: color } }).jpeg().toBuffer() })));
      for (const photo of evidence) { const digest = createHash("sha256").update(photo.content).digest("hex"); const relative = `inspections/${inspectionClientUuid}/${photo.photoUuid}.jpg`; await mkdir(path.dirname(path.join(uploadsPath, ...relative.split("/"))), { recursive: true }); await writeFile(path.join(uploadsPath, ...relative.split("/")), photo.content); await database.query(`INSERT INTO staged_inspection_evidence(photo_uuid,inspection_client_uuid,job_id,system_key,field_path,master_template_version_id,master_template_version,system_contract_sha256,uploader_user_id,request_fingerprint,source_sha256,stored_sha256,mime_type,source_size_bytes,source_width,source_height,stored_size_bytes,width,height,storage_relative_path,status) VALUES($1,$2,$3,'fire_alarm_detector',$4,$5,6,$6,$7,$8,$9,$9,'image/jpeg',$10,$11,$12,$10,$11,$12,$13,'staged')`, [photo.photoUuid, inspectionClientUuid, jobId, photo.fieldPath, template.id, contract, actor, createHash("sha256").update(`request:${photo.photoUuid}`).digest("hex"), digest, photo.content.length, 12 + evidence.indexOf(photo), 12 + evidence.indexOf(photo), relative]); }
      const accepted = await acceptFireAlarmV6Inspection({ operationId: uuid(), entityType: "masterSystemInspection", entityId: inspectionClientUuid, action: "create", payload: { clientUuid: inspectionClientUuid, jobId, systemKey: "fire_alarm_detector", instanceKey: "primary", configuredZoneId: null, configuredLocationId: null, displaySequence: 1, originalCreatorSnapshot: null, masterTemplate: { id: template.id, code: template.code, version: 6 }, configuration: snapshot.configuration, inspectionSnapshot: snapshot, responses, evidenceManifest: evidence.slice(0, 3).map((photo) => ({ photoUuid: photo.photoUuid, fieldPath: photo.fieldPath, sourceSha256: createHash("sha256").update(photo.content).digest("hex") })), performedAt: timestamp } }, actor); assert.equal(accepted.failed.length, 0, `real V6 acceptance failed: ${JSON.stringify(accepted.failed)}`); assert.deepEqual(accepted.acceptedIds, [inspectionClientUuid], "real V6 acceptance binds only Poor evidence"); const closed = await closeInspectionJob(jobId, { id: actor, username: "v6-report" }, database as never); assert.equal(closed.kind, "closed", "production completion closes accepted V6 report fixture"); return { jobId, inspectionClientUuid, responses, evidence, fields, stagedOnlyField };
    };
    const primary = await createFixture("SV-20260828-V6-PRIMARY"); const other = await createFixture("SV-20260828-V6-OTHER"); const missingAssetReference = await createFixture("SV-20260828-V6-MISSING", { secondary: "AD-1" }); const emptyAssetReference = await createFixture("SV-20260828-V6-EMPTY", { primary: "", secondary: "" }); const whitespaceAssetReference = await createFixture("SV-20260828-V6-WHITESPACE", { primary: "   ", secondary: "\t" }); const populatedAssetReference = await createFixture("SV-20260828-V6-POPULATED", { primary: "FA-123", secondary: "AD-456" });
    const report = await loadFinalServiceReport(primary.jobId, database); const repeat = await loadFinalServiceReport(primary.jobId, database); const section = report.sections.find((value) => value.systemKey === "fire_alarm_detector")!; assert.ok(section, "V6 Fire Alarm final-report section resolves from its frozen identity"); assert.deepEqual(section.evidence.map((item) => item.field), [...primary.fields].sort(), "accepted V6 evidence uses deterministic canonical field-path ordering"); assert.deepEqual(repeat.sections[0]?.evidence.map((item) => item.field), section.evidence.map((item) => item.field), "repeated report generation preserves evidence order"); assert.equal(section.evidence.length, 3, "staged/unbound evidence is excluded from final report authority"); assert.ok(section.evidence.every((item) => !item.field.includes(primary.stagedOnlyField) && !item.field.includes(other.inspectionClientUuid)), "other-job and staged evidence do not leak into this report");
    const values = new Map(section.fields.map((field) => [field.label, field.value])); assert.equal(values.get("Charger & Batteries - Main Supply"), "Good"); assert.equal(values.get("Charger & Batteries - Battery"), "Poor"); assert.equal(values.get("Charger & Batteries - Battery Remark"), "Battery capacity below threshold"); assert.equal(values.get("Charger & Batteries - Charger"), "Not Relevant"); assert.equal(values.get("Alarm Device Row 1 (Pump Room) - Alarm Bell"), "Poor"); assert.equal(values.get("Alarm Device Row 1 (Pump Room) - Alarm Bell Remark"), "Alarm bell does not sound"); assert.equal(values.get("Alarm Device Row 1 (Pump Room) - Manual Call Point"), "Poor"); assert.equal(values.get("Alarm Device Row 1 (Pump Room) - Manual Call Point Remark"), "Manual call point cover damaged"); assert.equal(values.get("Alarm Device Row 1 (Pump Room) - Remarks"), "Alarm-device row general remark"); assert.equal(values.get("Control Panel Row 1 - Manual Call Point"), "normal"); assert.equal(values.get("Control Panel Row 1 - Flow Switch"), "test"); assert.equal(values.get("Control Panel Row 1 - Heat Detector"), "isolation"); assert.deepEqual(section.evidence.map((item) => item.caption), ["Alarm Device Row 1 (Pump Room) - Alarm Bell", "Alarm Device Row 1 (Pump Room) - Manual Call Point", "Charger & Batteries - Battery"]);
    const missingReport = await loadFinalServiceReport(missingAssetReference.jobId, database); const missingValues = new Map(missingReport.sections.find((value) => value.systemKey === "fire_alarm_detector")!.fields.map((field) => [field.label, field.value])); assert.equal(missingValues.has("Control Panel Row 1 - No."), false, "accepted omitted primary asset reference is absent from the final report"); assert.equal(missingValues.get("Alarm Device Row 1 (Pump Room) - No."), "AD-1", "present secondary asset reference remains reportable when the primary field is omitted");
    const emptyReport = await loadFinalServiceReport(emptyAssetReference.jobId, database); const emptySection = emptyReport.sections.find((value) => value.systemKey === "fire_alarm_detector")!; const emptyValues = new Map(emptySection.fields.map((field) => [field.label, field.value])); assert.equal(emptyValues.has("Control Panel Row 1 - No."), false, "accepted empty primary asset reference is absent from the final report"); assert.equal(emptyValues.has("Alarm Device Row 1 (Pump Room) - No."), false, "accepted empty secondary asset reference is absent from the final report"); assert.equal(emptyValues.get("Charger & Batteries - Battery"), "Poor", "empty asset reference preserves accepted Poor evidence report fields"); const emptyPdf = await renderFinalServiceReportPdf(emptyReport); assert.equal(emptyPdf.subarray(0, 5).toString(), "%PDF-", "accepted empty asset reference reaches the production PDF pipeline"); for (const photo of emptyAssetReference.evidence.slice(0, 3)) assert.equal(emptyPdf.includes(photo.content), true, `accepted JPEG ${photo.fieldPath} remains embedded when asset reference is empty`);
    const whitespaceReport = await loadFinalServiceReport(whitespaceAssetReference.jobId, database); const whitespaceValues = new Map(whitespaceReport.sections.find((value) => value.systemKey === "fire_alarm_detector")!.fields.map((field) => [field.label, field.value])); assert.equal(whitespaceValues.has("Control Panel Row 1 - No."), false, "accepted whitespace-only primary asset reference is normalized absent"); assert.equal(whitespaceValues.has("Alarm Device Row 1 (Pump Room) - No."), false, "accepted whitespace-only secondary asset reference is normalized absent");
    const populatedReport = await loadFinalServiceReport(populatedAssetReference.jobId, database); const populatedValues = new Map(populatedReport.sections.find((value) => value.systemKey === "fire_alarm_detector")!.fields.map((field) => [field.label, field.value])); assert.equal(populatedValues.get("Control Panel Row 1 - No."), "FA-123", "non-empty primary asset reference preserves its exact accepted value"); assert.equal(populatedValues.get("Alarm Device Row 1 (Pump Room) - No."), "AD-456", "non-empty secondary asset reference preserves its exact accepted value");
    const pdf = await renderFinalServiceReportPdf(report); assert.equal(pdf.subarray(0, 5).toString(), "%PDF-", "current production PDF pipeline generates a PDF"); for (const photo of primary.evidence.slice(0, 3)) assert.equal(pdf.includes(photo.content), true, `accepted JPEG ${photo.fieldPath} is physically embedded by the section.evidence PDF loop`); assert.equal(pdf.includes(primary.evidence[3]!.content), false, "staged/unbound JPEG never reaches the final PDF image stream"); if (process.env.V6_FINAL_REPORT_PDF_PATH) { await mkdir(path.dirname(process.env.V6_FINAL_REPORT_PDF_PATH), { recursive: true }); await writeFile(process.env.V6_FINAL_REPORT_PDF_PATH, pdf); }
  } finally { await database.end(); await rm(uploadsPath, { recursive: true, force: true }); }
});
