import { parseDryWetRiserSystemConfiguration } from "./dryWetRiserConfiguration.js";
type R = Record<string, unknown>;
export const dryWetRiserOutletMaximum = 250;
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const water = ["saj_main_water_supply","water_level","automatic_refilling_facilities","drain_and_stop_valve_positions"];
const pump = ["pump_house_clean","manual_start_pumps","jockey_pump_pressure","duty_pump_cut_in","standby_pump_cut_in","standby_pump_service_items","battery_charging_alternator","battery_charger_failure_alarm","battery_serviceable","pump_phase_failure_alarm","pumps_auto_start","test_and_gate_valve_positions"];
const rec=(x:unknown):x is R=>typeof x==="object"&&x!==null&&!Array.isArray(x); const exact=(x:R,k:string[])=>Object.keys(x).length===k.length&&k.every(v=>v in x); const result=(x:unknown)=>x==="good"||x==="poor";
const response=(x:unknown)=>rec(x)&&exact(x,["result","remarks"])&&result(x.result)&&typeof x.remarks==="string"&&x.remarks.length<=2000;
const fixed=(x:unknown, keys:string[])=>rec(x)&&exact(x,keys)&&keys.every(key=>response(x[key]));
const stableJson=(x:unknown):string=>Array.isArray(x)?`[${x.map(stableJson).join(",")}]`:rec(x)?`{${Object.keys(x).sort().map(key=>`${JSON.stringify(key)}:${stableJson(x[key])}`).join(",")}}`:JSON.stringify(x);
function snapshot(value:unknown, id:string) { return rec(value) && exact(value,["id","displayName"]) && value.id===id && typeof value.displayName === "string" && value.displayName.length>0 && value.displayName.length<=250 && uuid.test(id); }

/** Configured rows always use frozen location sortOrder then ID, then ordinal; technician rows follow in submitted relative order. */
export function canonicalDryWetRiserResponses(value:unknown, system:R, mode:"dry"|"wet"):R|undefined {
 if(!rec(value)||!exact(value,["schemaVersion","mode","waterTank","pumpHouse","measurements","riserOutlets","comments"])||value.schemaVersion!==1||value.mode!==mode||!fixed(value.waterTank,water)||!fixed(value.pumpHouse,pump)||typeof value.comments!=="string"||value.comments.length>4000||!rec(value.measurements)||!exact(value.measurements,["jockeyCutIn","jockeyCutOut","dutyCutIn","standbyCutIn","unit"])||value.measurements.unit!=="PSI"||![value.measurements.jockeyCutIn,value.measurements.jockeyCutOut,value.measurements.dutyCutIn,value.measurements.standbyCutIn].every(x=>typeof x==="number"&&Number.isFinite(x))||!Array.isArray(value.riserOutlets)||value.riserOutlets.length===0||value.riserOutlets.length>dryWetRiserOutletMaximum||!Array.isArray(system.locations)||!Array.isArray(system.zones))return undefined;
 const zones=new Map(system.zones.filter(rec).map(z=>[z.id,z])); const locations=system.locations.filter(rec);
 if(locations.length!==system.locations.length)return undefined;
 const sortedLocations=locations.slice().sort((a,b)=>Number(a.sortOrder)-Number(b.sortOrder)||String(a.id).localeCompare(String(b.id)));
 const expected=new Map<string,R>();
 for(const location of sortedLocations){if(typeof location.id!=="string"||!uuid.test(location.id)||!Number.isSafeInteger(location.sortOrder)||Number(location.sortOrder)<0||!Number.isSafeInteger(location.presetRowCount)||Number(location.presetRowCount)<0||typeof location.displayName!=="string"||location.displayName.length===0||location.displayName.length>250)return undefined;for(let ordinal=1;ordinal<=Number(location.presetRowCount);ordinal++)expected.set(`${location.id}:${ordinal}`,location);}
 const seen=new Set<string>(), ids=new Set<string>(), submittedConfigured=new Map<string,R>(), technicians:R[]=[];
 for(const row of value.riserOutlets){const keys=["rowUuid","source","configuredLocationId","configuredRowOrdinal","zoneSnapshot","locationSnapshot","assetReference","locationText","canvasHoseAt2Result","diffuserNozzleResult","landingValveResult","crandleResult","doorResult","remarks","sortOrder"];if(!rec(row)||!exact(row,keys)||typeof row.rowUuid!=="string"||!uuid.test(row.rowUuid)||ids.has(row.rowUuid)||!Number.isSafeInteger(row.sortOrder)||Number(row.sortOrder)<1||typeof row.locationText!=="string"||!row.locationText||row.locationText.length>250||typeof row.assetReference!=="string"||row.assetReference.length>250||typeof row.remarks!=="string"||row.remarks.length>2000||![row.canvasHoseAt2Result,row.diffuserNozzleResult,row.landingValveResult,row.crandleResult,row.doorResult].every(result))return undefined;ids.add(row.rowUuid);
  if(row.source==="technician"){if(row.configuredLocationId!==null||row.configuredRowOrdinal!==null||row.locationSnapshot!==null||row.zoneSnapshot!==null||row.assetReference!=="")return undefined;technicians.push({...row,source:"technician",configuredLocationId:null,configuredRowOrdinal:null,locationSnapshot:null,zoneSnapshot:null,assetReference:""});continue;}
  if(row.source!=="configured"||typeof row.configuredLocationId!=="string"||!uuid.test(row.configuredLocationId)||!Number.isSafeInteger(row.configuredRowOrdinal)||Number(row.configuredRowOrdinal)<1)return undefined;const key=`${row.configuredLocationId}:${row.configuredRowOrdinal}`,location=expected.get(key);if(!location||seen.has(key))return undefined;const zoneId=location.zoneId,zone=typeof zoneId==="string"?zones.get(zoneId):undefined;if((zoneId===null||zoneId===undefined)?row.zoneSnapshot!==null:!zone||!snapshot(row.zoneSnapshot,String(zoneId))||(row.zoneSnapshot as R).displayName!==zone.displayName)return undefined;if(!snapshot(row.locationSnapshot,row.configuredLocationId)||(row.locationSnapshot as R).displayName!==location.displayName)return undefined;const preset=rec(location.rowPreset)?location.rowPreset:undefined,asset=preset&&typeof preset.assetReference==="string"?preset.assetReference:"";if(row.assetReference!==asset||row.locationText!==location.displayName)return undefined;seen.add(key);submittedConfigured.set(key,row);
 }
 if(seen.size!==expected.size)return undefined;
 const configured=sortedLocations.flatMap(location=>Array.from({length:Number(location.presetRowCount)},(_,index)=>{const ordinal=index+1,row=submittedConfigured.get(`${location.id}:${ordinal}`)!;const zone=typeof location.zoneId==="string"?zones.get(location.zoneId):undefined,preset=rec(location.rowPreset)?location.rowPreset:undefined,asset=preset&&typeof preset.assetReference==="string"?preset.assetReference:"";return {...row,source:"configured",configuredLocationId:location.id,configuredRowOrdinal:ordinal,zoneSnapshot:zone?{id:zone.id,displayName:zone.displayName}:null,locationSnapshot:{id:location.id,displayName:location.displayName},assetReference:asset,locationText:location.displayName};}));
 const out=[...configured,...technicians].map((row,index)=>({...row,sortOrder:index+1}));
 return {schemaVersion:1,mode,waterTank:value.waterTank,pumpHouse:value.pumpHouse,measurements:value.measurements,riserOutlets:out,comments:value.comments};
}
export function validStoredDryWetRiser(responses:unknown, system:unknown, configuration:unknown) { const parsed=parseDryWetRiserSystemConfiguration(configuration); const normalized=rec(system)&&parsed?canonicalDryWetRiserResponses(responses,system,parsed.riserMode):undefined; return !!normalized&&stableJson(normalized)===stableJson(responses); }
