import { useRef, useState } from "react";
import { CameraCaptureDialog } from "../attachments/CameraCaptureDialog";
import { processInspectionPhoto, requestPersistentAttachmentStorage } from "../attachments/imageProcessing";
import type { InspectionAttachmentRecord } from "../attachments/attachmentTypes";
import type { AutomaticSprinklerInspectionRecord } from "./automaticSprinklerTypes";
import { saveAutomaticSprinklerV7Photo, type AutomaticSprinklerV7FieldPath } from "./automaticSprinklerV7Evidence";

export function AutomaticSprinklerV7EvidenceField({ record, fieldPath, attachment, onChanged }: { record: AutomaticSprinklerInspectionRecord; fieldPath: AutomaticSprinklerV7FieldPath; attachment?: InspectionAttachmentRecord; onChanged: () => Promise<void> }) {
  const input = useRef<HTMLInputElement>(null); const [cameraOpen, setCameraOpen] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function save(blob: Blob, captureSource: "camera" | "gallery", capturedAt?: string) { setBusy(true); try { void requestPersistentAttachmentStorage(); await saveAutomaticSprinklerV7Photo({ record, fieldPath, captureSource, ...await processInspectionPhoto(blob), capturedAt }); await onChanged(); setMessage("Photo saved on this device."); } catch (error) { setMessage(error instanceof Error ? error.message : "Photo could not be saved"); } finally { setBusy(false); } }
  return <section className="photo-evidence-field" aria-label={`V7 evidence photo for ${fieldPath}`}><p className="secondary-metadata">{attachment ? "V7 finding photo attached on this device" : "No V7 finding photo attached"}</p><div className="photo-actions"><button type="button" disabled={busy} onClick={() => setCameraOpen(true)}>{attachment ? "Replace with Camera" : "Take Photo"}</button><button type="button" className="secondary-command" disabled={busy} onClick={() => input.current?.click()}>{attachment ? "Replace from Gallery" : "Choose Existing Photo"}</button><input ref={input} className="visually-hidden" type="file" accept="image/*" onChange={(event) => { const file = event.currentTarget.files?.[0]; event.currentTarget.value = ""; if (file) void save(file, "gallery"); }} /></div>{message ? <p className="form-message" role="status">{message}</p> : null}{cameraOpen ? <CameraCaptureDialog onCapture={async (blob, capturedAt) => { setCameraOpen(false); await save(blob, "camera", capturedAt); }} onClose={() => setCameraOpen(false)} /> : null}</section>;
}
